### ISSUE TITLE
漏斗图点击取消三项会出现报错，并且不能再点击

### ISSUE THREAD

**Issue by lidong3527** [ecomfe/echarts-for-weixin#1]
以下为图片
![qq 20180227115927](https://user-images.githubusercontent.com/29711541/36709961-c6a00ed4-1bb5-11e8-9b99-e7a9280296d2.png)

**Comment by JLmDy** [comment]
同样的问题。。老问题了啊。。尚未修复

**Comment by BLZATMHK1018** [comment]
漏斗图点击取消三项会出现报错，并且不能再点击 

也出现了这种问题，怎么解决的？

**Comment by BLZATMHK1018** [comment]
![default](https://user-images.githubusercontent.com/42031867/50208882-557d2080-03ad-11e9-9542-8eb11c95b2b8.png)

**Comment by BLZATMHK1018** [comment]
显示的信息也不对，应该是这样的
![default](https://user-images.githubusercontent.com/42031867/50208950-80677480-03ad-11e9-8f48-55d253cea6f8.png)

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
