### ISSUE TITLE
试了下官方的demo，感觉比较卡

### ISSUE THREAD

**Issue by derekhe** [ecomfe/echarts-for-weixin#10]
二维码扫描的官方demo，在我的荣耀V8的手机里面速度感觉比较卡的样子。几乎所有的图都有同样的问题。

**Comment by kiccer** [comment]
我也有同样的问题，我的是P9，会不会是因为代码没用GPU渲染？

**Comment by Yidadaa** [comment]
这是因为小程序本手就有性能上的原因，有卡顿是在意料之中的事情

**Comment by derekhe** [comment]
能否有优化？这个可用性并不是太好呢感觉。

**Comment by AlbieLiang** [comment]
@derekhe @kiccer 请问你们代码里面是否使用了比较多的clearRect？目前微信Android这边clearRect性能损耗比较大，你可以先确认下是不是这个接口造成的~（先注掉看下）

**Comment by 342688695** [comment]
在安卓机上挺卡的 尤其是一个页面多个图表

**Comment by derekhe** [comment]
@AlbieLiang 并没有，就官方的DEMO都很卡好不好

**Comment by lengmoukong** [comment]
详情页要用到多个图表 大约8个吧 ios真机调试不卡 一上传到体验版本上 上下滚动 一卡一卡的，能否有优化？看是否有解决办法

**Comment by derekhe** [comment]
为什么就close了呢？

**Comment by callmesoul** [comment]
安卓 ios 一个页面有8个图标，ipad mini2 有点卡？有什么优化方案没？
