### ISSUE TITLE
小程序开发工具与发布体验版本显示差异

### ISSUE THREAD

**Issue by myNathon** [ecomfe/echarts-for-weixin#100]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
小程序开发工具显示预期效果图，发布体验版本则显示实际效果图[上下对应差别]
实际效果图2，刚进去显示空白，手指滑动显示如图

### 预期效果：
![1522120408 1](https://user-images.githubusercontent.com/18466946/37944886-13cbc922-31b0-11e8-940e-dbb9f17a9350.jpg)
![1522120667 1](https://user-images.githubusercontent.com/18466946/37944975-8720acda-31b0-11e8-96dc-81fbf185482b.jpg)

### 实际效果：
![20180327111424](https://user-images.githubusercontent.com/18466946/37944893-1912e0f0-31b0-11e8-8647-3b5ef3b952ee.jpg)
![20180327111810](https://user-images.githubusercontent.com/18466946/37944983-937e0c7a-31b0-11e8-9092-bb46a1f3f026.jpg)

### 复现环境：
- [x] 小程序工具基础库 1.9.91; iPhone X 微信版本 6.6.5; 网络 WIFI

**Comment by Ovilia** [comment]
更新到最新的开发工具和微信版本，应该没有这个问题了吧
