### ISSUE TITLE
echarts-for-weixin 使用dataZoom时与series冲突

### ISSUE THREAD

**Issue by yelongsan** [ecomfe/echarts-for-weixin#102]
### 简单描述问题：
用官方demo设置折线图时，同时设置dataZoom和series中的label标签时 `label显示不全。`
`option = {
    backgroundColor: "#fff",
    dataZoom: [{
      type: 'inside',
      start: 0,
      end: 50
    }],
    legend: {
      data: ['A商品']
    },
    grid: {
      containLabel: true
    },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日', '周一', '周二', '周三', '周四', '周五', '周六', '周日']
    },
    yAxis: {
      x: 'center',
      type: 'value'
    },
    series: [{
      name: 'A商品',
      type: 'line',
      smooth: true,
      label: {
        show: true,
        position: [10, -20],
      },
      data: [18, 36, 65, 30, 78, 40, 33, 18, 36, 65, 30, 78, 40, 33]
    }]
  };`
### 预计效果：
![image](https://user-images.githubusercontent.com/18372713/38007978-d4f7e814-327e-11e8-8c73-06a1bba7f132.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/18372713/38007772-a807c118-327d-11e8-8228-a419f6f8992e.png)

### 复现环境：
- 在微信开发工具小程序 工具基础库 1.9.91 中存在该问题
- 在安装小米真机上存在该问题

**Comment by Ovilia** [comment]
等 #52 解决后，我会看下是不是同一个问题引起的

**Comment by yelongsan** [comment]
不知为什么更改了dataroom里的filterMode就行了
dataZoom: [{
      type: 'inside',
      filterMode: 'empty',
      start: 0,
      end: 50
    }]
