### ISSUE TITLE
ios 图表拦截了touch事件？

### ISSUE THREAD

**Issue by cnsilvan** [ecomfe/echarts-for-weixin#104]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [X] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [X] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在echarts父级增加了touch事件，在调试和android真机上都正常，但是在ios上就不会触发该事件了。
已经使用了
ec: {
      lazyLoad: true,
      disableTouch: true
    }

### 预期效果：
应该和android一样正常触发事件
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [X] 在真机上存在该问题

**Comment by Ovilia** [comment]
“不会触发该事件” 是 ECharts 不会响应还是什么意思？

**Comment by cnsilvan** [comment]
@Ovilia 感觉是ECharts消费了touch事件
其父容器 这两个bindtouchstart="touchStart" bindtouchend="touchEnd" 并不会调用
但是在ECharts空白区域可以正常调用

**Comment by Ovilia** [comment]
@cnsilvan 是的，这是预期的效果。你是希望 ECharts 不要相应事件吗？参见 #37

**Comment by cnsilvan** [comment]
@Ovilia 我已经设置了disableTouch ，在android上没什么问题，但是在ios上，控件内上下滑动没什么问题，左右滑动就不行。

**Comment by Ovilia** [comment]
左右滑动？那有横向滚动条吗？

**Comment by cnsilvan** [comment]
@Ovilia 我一个页面显示多个echarts 可以正常的上下滑动页面，左右滑动是我在父级view写的监听
bindtouchstart="touchStart" bindtouchend="touchEnd" 

android上就算touchStart点在chart上也会正确调用bind的方法上，但是ios上不会触发这两个方法。

**Comment by Ovilia** [comment]
bind 事件应该不会阻止冒泡，你了解下微信小程序的事件机制吧~

**Comment by cnsilvan** [comment]
@Ovilia 你说的都对，但是他就是不响应。你不信用ios试一下。

**Comment by cnsilvan** [comment]
ios的日志会比android 多
invoke event touchMove in component：ec-canvas/ec-canvas

**Comment by FreeFlying0** [comment]
感觉我遇到的问题和你类似。我也是一个页面上有多个echarts，当你手指在其中一个echarts区域中滑动时，所有的事件都是正常触发的，但当手指滑动到该echarts区域外并结束滑动时，是不会触发echarts的touchEnd事件，之后点击其它echarts时，只会触发touchmove。只有再次点击同一echarts，才会触发touchEnd。
在模拟器上所有事件都是正常的，不存在问题；在安卓上，echarts的事件不正常，但页面滑动可以；ios上，页面滑动也会不正常。 @cnsilvan

**Comment by cnsilvan** [comment]
@FreeFlying0 我没有监听echarts的事件，我是需要实现全局左右滑动切换页面，所以在父层监听的事件。
ios下只要在echarts区域内的touch事件 都没有冒泡到父层，安卓下正常。
根据你的描述 我觉得我们应该是一个问题。

**Comment by FreeFlying0** [comment]
@cnsilvan 现在我的临时解决办法是把不需要触摸的echarts组件重写，把所有touch事件删除
<canvas class="ec-canvas-notouch" canvas-id="{{ canvasId }}" bindinit="init">
</canvas>
但是我还有部分echarts需要有触摸事件，还可能触发这个问题，所以希望官方能解决一下。

**Comment by cnsilvan** [comment]
@FreeFlying0 我也是这样处理的

**Comment by Ovilia** [comment]
6d3d862e491fe933b424c469bb5aad4a2ebcf9c3 已修复，现在设置 disableTouch 就能禁止拦截触摸事件 https://github.com/ecomfe/echarts-for-weixin/blob/e79ba864e92285390504d65231cb50730ae3415a/pages/move/index.js#L16

**Comment by Sherry-xj** [comment]
设置 disableTouch左右滑动又不行了
