### ISSUE TITLE
显示空白

### ISSUE THREAD

**Issue by carlSunLiang** [ecomfe/echarts-for-weixin#108]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
开发工具上也不报错，空白显示

### 预期效果：
![image](https://user-images.githubusercontent.com/8129970/38127410-9887f38c-3428-11e8-8c82-bf98177b0e6d.png)

（如有需要请提供预期的图）

### 实际效果：
![image](https://user-images.githubusercontent.com/8129970/38127402-90be7fea-3428-11e8-96bb-a9d8e8e5ddbd.png)

![image](https://user-images.githubusercontent.com/8129970/38127388-83ac4e7c-3428-11e8-987e-c3f3a736a96b.png)

（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
是在开发工具上白屏吗？开发工具版本号？基础库版本号？

**Comment by carlSunLiang** [comment]
是的，![image](https://user-images.githubusercontent.com/8129970/38131654-7bc147dc-343a-11e8-900b-8d6d35c3726b.png)
![image](https://user-images.githubusercontent.com/8129970/38131667-8893cfca-343a-11e8-831c-0538155c05a2.png)

**Comment by choukui** [comment]
我的也是，就是空白页面，也不报错，真机和开发工具一样。

**Comment by choukui** [comment]
@carlSunLiang 空白的原因是我们container类名的css样式去掉了，导致页面显示空白。加上这段css 
`.container{
   position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  box-sizing: border-box;
}`
项目app.wxss有写

**Comment by Ovilia** [comment]
@carlSunLiang 是 @choukui 说的问题吗？

**Comment by Ovilia** [comment]
#52

**Comment by xty19** [comment]
@chouku 正解，我测试了，ios，安卓。
只有把app.wxss 更改为 官方demo的 才可以正常显示

**Comment by aiqiao** [comment]
![image](https://user-images.githubusercontent.com/29449411/57676346-e0a9cc00-7656-11e9-93c1-81079be46389.png)
左边用的是压缩过的echarts

**Comment by aiqiao** [comment]
压缩的echart不能直接使用在项目中吗？

**Comment by aiqiao** [comment]
压缩文件是用echart的在线构建工具 构建的
