### ISSUE TITLE
wepy中无法引入echats-for-weixin

### ISSUE THREAD

**Issue by LinkXSystem** [ecomfe/echarts-for-weixin#111]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
wepy中无法引入echats-for-weixin

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by LinkXSystem** [comment]
错误情况
![snipaste_2018-03-31_10-27-51](https://user-images.githubusercontent.com/26039188/38158819-75705dca-34ce-11e8-9b58-602e75f71570.png)

**Comment by Ovilia** [comment]
#7
