### ISSUE TITLE
我们使用datazoom的filterMode属性的时候除了none，其他的选项都是不正常的

### ISSUE THREAD

**Issue by smc1989** [ecomfe/echarts-for-weixin#115]
- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

![](https://thumbnail0.baidupcs.com/thumbnail/7f527f148e1a855c212b5d4300659a17?fid=1966289498-250528-302225342058842&time=1522659600&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-bEZT%2BuxyMvGlxxNjP6AKyaJy%2Fiw%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=2127092826452501843&dp-callid=0&size=c710_u400&quality=100&vuk=-&ft=video)

![](https://thumbnail0.baidupcs.com/thumbnail/4209d3a88fe4e5962136c868d210a8bd?fid=1966289498-250528-969180780475029&time=1522659600&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-81fN8CLb6KmA8J7E%2Bu4BpffY8vM%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=2127278354796661121&dp-callid=0&size=c710_u400&quality=100&vuk=-&ft=video)

我们使用datazoom的filterMode属性的时候除了none，其他的选项都是不正常的，现在项目中有这个左右滑动的需求，希望能尽快修正
我是用的是截至发稿为止最新的版本

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
感觉可能和 #52 是同一个问题引起的

**Comment by linsihan** [comment]
同一个问题，跪求官方大神解决

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
