### ISSUE TITLE
ios真机不展示legend信息

### ISSUE THREAD

**Issue by NortonLee** [ecomfe/echarts-for-weixin#118]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
IOS真机折线图legend信息不展示
基础库版本：1.9.91
微信版本：6.6.5

### 预期效果：
![image](https://user-images.githubusercontent.com/10142351/38225098-d13054e0-3725-11e8-94ea-fee7866e7825.png)

### 实际效果：

![image](https://user-images.githubusercontent.com/10142351/38225227-828a6c8a-3726-11e8-8610-20c60e0c7a8a.png)

![image](https://user-images.githubusercontent.com/10142351/38225308-e9505b14-3726-11e8-92e0-24556eca8f97.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题， android显示正常，ios不展示legend信息，取消选中某一项时，有可以展示，左侧纵坐标会遮挡横坐标的起始数据，导致数据展示不完整。

**Comment by Ovilia** [comment]
同 #52
