### ISSUE TITLE
线图的 series 样式问题

### ISSUE THREAD

**Issue by huangyangme** [ecomfe/echarts-for-weixin#12]
1. line 图，`series[i]-line.lineStyle.type = 'solid'` 时，微信开发者工具显示的是实线('solid')。但是手机预览显示的却是'dashed'。
2. line 和 area 的颜色显示也有问题。手机预览颜色更深（需要微信后续版本更新？）。

 微信开发者工具模拟器效果：
![2018-02-28 3 18 36](https://user-images.githubusercontent.com/4213398/36774906-ddeff47e-1c9a-11e8-8db9-1cb6862ce3af.png)

手机预览（iPhone7，WeChat 6.6.5）：
![img_69ca07d75674-1](https://user-images.githubusercontent.com/4213398/36775051-6057d7ce-1c9b-11e8-8a30-204704166e5c.jpeg)

代码：
```javascript
series: [{
      data: [820, 932, 901, 934, 1290, 1330, 1320],
      type: 'line',
      smooth: true,
      itemStyle: {
        color: '#999',
        type: 'solid', // 线类型
        opacity: 0,
      },
      lineStyle: {
        color: 'rgb(23, 147, 209)', // 线颜色
        width: 1,
      },
      areaStyle: {
        color: 'rgba(23, 147, 209,0.2)' // 区域颜色
      }
    }]
```

**Comment by Ovilia** [comment]
1. 我在 iPhone 7，微信 6.6.5 没有复现出问题，有没有可能你手机上预览的版本代码不一致？
2. 这个问题是微信基础库的 bug，还没修复
