### ISSUE TITLE
运行不起来。

### ISSUE THREAD

**Issue by xifat** [ecomfe/echarts-for-weixin#122]
提示echarts.init is not a function
`
import * as echarts from "../../../libs/ec-canvas/ec-canvas"
function initChart(canvas, width, height) {
  const chart = echarts.init(canvas, null, {
    width: width,
    height: height
  });
  canvas.setChart(chart);

  var option = {
    backgroundColor: "#ffffff",
    color: ["#37A2DA", "#32C5E9", "#67E0E3", "#91F2DE", "#FFDB5C", "#FF9F7F"],
    series: [{
      label: {
        normal: {
          fontSize: 14
        }
      },
      type: 'pie',
      center: ['50%', '50%'],
      radius: [0, '60%'],
      data: [{
        value: 55,
        name: '北京'
      }, {
        value: 20,
        name: '武汉'
      }, {
        value: 10,
        name: '杭州'
      }, {
        value: 20,
        name: '广州'
      }, {
        value: 38,
        name: '上海'
      },
      ],
      itemStyle: {
        emphasis: {
          shadowBlur: 10,
          shadowOffsetX: 0,
          shadowColor: 'rgba(0, 2, 2, 0.3)'
        }
      }
    }]
  };
 chart.setOption(option);
  return chart;

Page({

  /**
   * 页面的初始数据
   */
  data: {
    
    ec: {
      onInit: initChart
    },
    
  },
`

**Comment by Ovilia** [comment]
路径是否写对？参考本项目的例子写

**Comment by wangchao523** [comment]
`import * as echarts from "../../../libs/ec-canvas/ec-canvas"`
这里的引入错误了，最后的ec-canvas
参考：https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/bar/index.js
`import * as echarts from '../../ec-canvas/echarts';`
