### ISSUE TITLE
例子"一个页面中多个图表"第二次无法进入

### ISSUE THREAD

**Issue by jason19659** [ecomfe/echarts-for-weixin#128]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
例子 “一个页面多个图表”第二次无法进入，
编译例子，
点击“一个页面中多个图表”例子，
点击 <返回
再次点击“一个页面中多个图表”例子，
报错
```
VM232:1 jsEnginScriptError
Converting circular structure to JSON
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.a [as publish] (http://127.0.0.1:55037/appservice/appservice:1228:8044)
    at c (http://127.0.0.1:55037/appservice/__dev__/WAService.js:16:7000)
    at t.sendData (http://127.0.0.1:55037/appservice/__dev__/WAService.js:16:7566)
    at z (http://127.0.0.1:55037/appservice/__dev__/WAService.js:16:4901)
    at Object.t.addView (http://127.0.0.1:55037/appservice/__dev__/WAService.js:16:6005)
    at Function.value (http://127.0.0.1:55037/appservice/__dev__/WAService.js:18:1346)
    at B (http://127.0.0.1:55037/appservice/__dev__/WAService.js:17:11379)
    at L (http://127.0.0.1:55037/appservice/__dev__/WAService.js:17:12665)
    at G (http://127.0.0.1:55037/appservice/__dev__/WAService.js:17:13986)
```
并且小程序发生进入到很奇怪的状态，编译库1.9.91

**Comment by LarryLawrence** [comment]
遇到了同样的问题

**Comment by cc-holly** [comment]
多个图表你们能展示多个吗？我复制粘贴官网的例子，然后再加了一个图，我发现第三个图展现不出来，前两个图表能正常展示是怎么回事？

**Comment by LarryLawrence** [comment]
@cc-holly 可以展示多个的。猜测你应该是忘记在```wxml```里添加多个```ec-canvas```了，或者数据没有加载成功。

**Comment by Ovilia** [comment]
#174 已修复

**Comment by cc-holly** [comment]
还是不行，
我的wxml是这么写的：
<view class="container">
  <ec-canvas id="mychart-dom-multi-bar" canvas-id="mychart-multi-bar" ec="{{ ecBar }}"></ec-canvas>
  <ec-canvas id="mychart-dom-multi-scatter" canvas-id="mychart-multi-scatter" ec="{{ ecScatter }}"></ec-canvas>
  <ec-canvas id="mychart-dom-multi-line" canvas-id="mychart-multi-line" ec="{{ ecLine }}"></ec-canvas>
</view>
数据我是直接写死的，用的官网上的例子（三个都是，因为先实验一下）：
import * as echarts from '../../ec-canvas/echarts';
Page({
  data: {
    ecBar: {
      onInit: function (canvas, width, height) {
        const barChart = echarts.init(canvas, null, {
          width: width,
          height: height
        });
        canvas.setChart(barChart);
        barChart.setOption(getBarOption());
        return barChart;
      }
    },

    ecScatter: {
      onInit: function (canvas, width, height) {
        const scatterChart = echarts.init(canvas, null, {
          width: width,
          height: height
        });
        canvas.setChart(scatterChart);
        scatterChart.setOption(getScatterOption());

        return scatterChart;
      }
    },

    ecLine:{
      onInit:function(canvas,width,height){
        const lineChart = echarts.init(canvas,null,{
          width:width,
          height:height
        });
        canvas.setChart(lineChart);
        lineChart.setOption(getLineOption());
        return lineChart;
      }
    }
  },

  onReady() {
  }
});

function getBarOption() {
  return {
    title:{
      text:'图一'
    },
    xAxis: {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
      type: 'value'
    },
    series: [{
      data: [820, 932, 901, 934, 1290, 1330, 1320],
      type: 'line'
    }]
  } 
}

function getScatterOption() {
  return {
    title:{
      text:'图二'
    },
    xAxis: {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
      type: 'value'
    },
    series: [{
      data: [820, 932, 901, 934, 1290, 1330, 1320],
      type: 'line',
      smooth: true
    }]
  };
}

function getLineOption(){
  return {
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
      type: 'value'
    },
    series: [{
      data: [820, 932, 901, 934, 1290, 1330, 1320],
      type: 'line',
      areaStyle: {}
    }]
  }
}
然后只显示两个，第三个我检查元素，高度是0，不知道是咋回事

**Comment by cc-holly** [comment]
已经解决，要在wxss里面设置height:50%;
