### ISSUE TITLE
关于兼容性问题

### ISSUE THREAD

**Issue by kiccer** [ecomfe/echarts-for-weixin#13]
我把以前PC版本中的option设置直接复制到小程序中（删除了tooltip）报了一大堆错，这个要怎么解决？

**Comment by Ovilia** [comment]
具体是什么错？精简一下代码，方便定位

**Comment by kiccer** [comment]
报了好多错呢，能帮忙看一下哪里有问题吗？
`
var option = {
    title: {
    },
    // tooltip: {
    // },
    legend: {
    },
    grid: {
      left: 48,
      right: 10,
      top: 30,
      bottom: 48
    },
    xAxis: {
      data: [],
      axisLine: {
        lineStyle: {
          color: '#fff'
        }
      },
      axisTick: {
        show: false,
        alignWithLabel: true
      },
      axisPointer: {
        show: true,
        label: {
          show: false,
          backgroundColor: '#3C414F'
        }
      },
      axisLabel: {
        formatter: (n, i) => {
          if (/^\d{4}-\d{2}-\d{2} \d{2}$/g.test(n)) {
            // 2017-12-27 15
            return n.replace(/\d{4}-(\d{2}-\d{2} \d{2})/g, '$1')
          } else if (/^\d{4}-\d{2}-\d{2}$/g.test(n)) {
            // 2017-12-27
            return n.replace(/\d{4}-(\d{2}-\d{2})/g, '$1')
          }
        }
      }
    },
    yAxis: {
      axisLine: {
        lineStyle: {
          color: '#fff'
        }
      },
      axisTick: {
        show: false
      },
      splitLine: {
        show: false
      }
    },
    backgroundColor: '#262932',
    series: [{
      name: '声量',
      type: 'line',
      smooth: true,
      symbolSize: 4,
      lineStyle: {
        normal: {
          color: '#F7B24F',
          width: 3
        }
      },
      itemStyle: {
        normal: {
          opacity: 0
        }
      },
      data: []
    }]
  };
`

**Comment by kiccer** [comment]
报了很多错，能帮忙看一下这个哪里有错吗？
```
var option = {
    title: {
    },
    // tooltip: {
    // },
    legend: {
    },
    grid: {
      left: 48,
      right: 10,
      top: 30,
      bottom: 48
    },
    xAxis: {
      data: [],
      axisLine: {
        lineStyle: {
          color: '#fff'
        }
      },
      axisTick: {
        show: false,
        alignWithLabel: true
      },
      axisPointer: {
        show: true,
        label: {
          show: false,
          backgroundColor: '#3C414F'
        }
      },
      axisLabel: {
        formatter: (n, i) => {
          if (/^\d{4}-\d{2}-\d{2} \d{2}$/g.test(n)) {
            // 2017-12-27 15
            return n.replace(/\d{4}-(\d{2}-\d{2} \d{2})/g, '$1')
          } else if (/^\d{4}-\d{2}-\d{2}$/g.test(n)) {
            // 2017-12-27
            return n.replace(/\d{4}-(\d{2}-\d{2})/g, '$1')
          }
        }
      }
    },
    yAxis: {
      axisLine: {
        lineStyle: {
          color: '#fff'
        }
      },
      axisTick: {
        show: false
      },
      splitLine: {
        show: false
      }
    },
    backgroundColor: '#262932',
    series: [{
      name: '声量',
      type: 'line',
      smooth: true,
      symbolSize: 4,
      lineStyle: {
        normal: {
          color: '#F7B24F',
          width: 3
        }
      },
      itemStyle: {
        normal: {
          opacity: 0
        }
      },
      data: []
    }]
  };
```

**Comment by Ovilia** [comment]
我这没报错，你是否在微信开发者工具中将详情的基础库版本设到 1.9.91 了呢？

**Comment by kiccer** [comment]
原来是因为我用的1.9.1。。。 →_→

**Comment by kiccer** [comment]
顺便还有一个问题，怎样动态修改图表内的数据？在函数外怎么拿到chart实例

**Comment by Ovilia** [comment]
更新了例子，参加柱状图
