### ISSUE TITLE
小程序是否支持chart.getDataURL()图片信息

### ISSUE THREAD

**Issue by myNathon** [ecomfe/echarts-for-weixin#132]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息
代码如下图
![1523333003 1](https://user-images.githubusercontent.com/18466946/38535736-94fb3192-3cb7-11e8-9c7d-31b435dd52e2.jpg)
在小程序中使用报错如下图
![1523333028 1](https://user-images.githubusercontent.com/18466946/38535743-a46ec012-3cb7-11e8-9e95-f8a598c686a4.jpg)

### 简单描述问题：
在小程序中使用echarts支持图片的获取吗？或是我在使用上有什么不对的地方吗？

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 小程序工具 v1.02.1803210 基础库 1.9.93

**Comment by myNathon** [comment]
设置option后调用出现，大神指点指点
![1523340508 1](https://user-images.githubusercontent.com/18466946/38539049-09fa5d54-3cc9-11e8-92f6-0536e4161d69.jpg)
![1523340641 1](https://user-images.githubusercontent.com/18466946/38539051-0dfbcb86-3cc9-11e8-8e94-19dd4c6480c2.jpg)

**Comment by Ovilia** [comment]
小程序不支持这个方法
