### ISSUE TITLE
小白请教，这个ec变量怎么传值进去啊，这样写会报错呢

### ISSUE THREAD

**Issue by xiaozhang24** [ecomfe/echarts-for-weixin#135]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息
data: {
    ArtsData:{
      year: ["2013", "2014", "2015", "2016", "2017", "2018"],
      data: [562, 540, 528, 532, 511, 520]
    },
    ScienceData:{
      year: ["2013", "2014", "2015", "2016", "2017", "2018"],
      data: [503, 512, 508, 497, 522, 510]
    },
    ecArts: {
      onInit: initLineChart(this.data.ArtsData)
    },
    ecScience: {
      onInit: initLineChart(this.data.ScienceData)
    }
  },
将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
你们是怎么传值进去，动态生成图表的呢

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
参考例子呗

**Comment by xiaozhang24** [comment]
刚接触小程序，不太熟。例子都是死数据，动态数据怎么搞

**Comment by jason19659** [comment]
`
chart.setOption({
          xAxis: {
            data: index
          },
          series: [{
            type: 'line',
            data: ***数据***
          }]
        })
`

**Comment by xiaozhang24** [comment]
不解的地方是比如这 ArtsData:{
year: ["2013", "2014", "2015", "2016", "2017", "2018"],
data: [562, 540, 528, 532, 511, 520]
},  是data的一个数据。
 function initArtsChart(ArtsData ) 是方法  

ec: {
      onInit: initArtsChart
    } 
ec对象中的 initArtsChart 改成initArtsChart（this.data.ArtsData）就报错了。 数据是怎么传过去的。

**Comment by YoungOngSun** [comment]
Demo里有一个延迟加载图标的例子

**Comment by YoungOngSun** [comment]
Demo里有一个延迟加载图表的例子

**Comment by Bingordinary** [comment]
参照demo中bar的案例 ，获取图表实例chart，然后用chart.setOption({ xAxis: { data: index }, series: [{ type: 'line', data: ***数据*** }] })修改数据
