### ISSUE TITLE
y轴label显示错误

### ISSUE THREAD

**Issue by cnsilvan** [ecomfe/echarts-for-weixin#136]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [X] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [X] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
series中提供了数据[0，0，0]、[0，0，0]、[1，1，1]、[1，1，1]，出现了绘制不正确和y轴的label显示问题

### 预期效果：

（如有需要请提供预期的图）

### 实际效果：
![image](https://user-images.githubusercontent.com/15416002/38604970-8cda43ac-3da4-11e8-8a23-3baed4be1608.png)
如图少了两根线， y轴的显示的label也有问题
（如有需要请提供截图）

### 复现环境：
- [X] 在微信开发工具中存在该问题
- [X] 在真机上存在该问题

**Comment by cnsilvan** [comment]
线不显示应该是覆盖了，能不能判断如果数据覆盖，使用微小偏移量或者透明度 线条粗细等解决覆盖的问题呢？
我同时看见某些折线图就算覆盖就看的出来啊。
好奇怪的问题

**Comment by cnsilvan** [comment]
另外 求放出小程序未压缩的js,官方下载的没这个新。

**Comment by Ovilia** [comment]
提供一下完整的配置项？
未压缩的 js 可以在 ECharts 官网或 GitHub 下载最新版的未压缩文件，替换 echarts.js 即可。

**Comment by cnsilvan** [comment]
@Ovilia 不好意思，经过发现是格式化的问题
![image](https://user-images.githubusercontent.com/15416002/38798617-a244129c-4194-11e8-835a-9ee3c5fb7ec2.png)
正常是这样的
