### ISSUE TITLE
如何只显示data数组里当前的值（在图中清除之前的数据）

### ISSUE THREAD

**Issue by ilovepumpkin** [ecomfe/echarts-for-weixin#138]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
我想参照http://echarts.baidu.com/examples/editor.html?c=dynamic-data2&theme=dark　实现一个类似的动态刷新数据的图

### 预期效果：
理论上结果应该如http://echarts.baidu.com/examples/editor.html?c=dynamic-data2&theme=dark 所示，x轴一直向左移动

### 实际效果：
实际效果如下图所示，尽管我已经用shift移除了前面的数据，也就是说data数组里始终保持固定长度的数据，但是前面数据的x轴依然显示，我期望的是当新数据进来的时候，红框部分就消失了。我以为是setOption的第二个参数notMerge导致，于是将它设成true, 问题依然存在。另外就是示例http://echarts.baidu.com/examples/editor.html?c=dynamic-data2&theme=dark 中的setOption方法也没有设置第二个参数为true。

初始状态
![image](https://user-images.githubusercontent.com/11310645/38620738-df1c9fe8-3dd1-11e8-8e50-c21c2c04d694.png)

开始随机产生数据，并仿照例子用每添加个数据都用shift删除一个
![image](https://user-images.githubusercontent.com/11310645/38620287-b3888e42-3dd0-11e8-9a91-2c767e9fd6b6.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
这个是通用的 ECharts 的问题还是小程序特有的？如果是前者，请到 http://github.com/apache/incubator-echarts 提问
