### ISSUE TITLE
不能配置使用哪些图吗？

### ISSUE THREAD

**Issue by lwba21190** [ecomfe/echarts-for-weixin#14]
该文件太大了，但是实际中可能用不到这么多种图形，是否可以提供自定义方式？

**Comment by Ovilia** [comment]
http://echarts.baidu.com/builder.html 按需下载

**Comment by lwba21190** [comment]
这个定制该怎么支持在微信小程序端？

**Comment by Ovilia** [comment]
定制下载的文件覆盖 ec-canvas 目录下的 echarts.js

**Comment by lwba21190** [comment]
你好，这样会报错，提示“”VM57698:1 TypeError: Cannot read property 'createElement' of undefined“”

**Comment by Ovilia** [comment]
@lwba21190 可能线上还不是最新版，稍等我排查一下

**Comment by Ovilia** [comment]
我试了一下没有问题，@lwba21190 请提供一下选择下载哪些，以及出问题的代码？

**Comment by lwba21190** [comment]
我是用的是官网在线定制默认的模块（生成的是echarts.min.js），然后试用了下demo中bar的是例子，代码使用demo中的echarts.js是没有问题

**Comment by lwba21190** [comment]
好吧，把文件名命名为echarts.js(echarts.min.js -> echarts.js)就好了，谢谢了
