### ISSUE TITLE
请问一下，去掉点选遮罩层可以

### ISSUE THREAD

**Issue by myNathon** [ecomfe/echarts-for-weixin#141]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息
![default](https://user-images.githubusercontent.com/18466946/38716837-777135f8-3f15-11e8-8a9f-785f6ffb809b.png)

### 简单描述问题：
点选显示遮罩层，这个可以通过设置去除掉吗？

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
与本项目无关
