### ISSUE TITLE
【求助】求mapData.js的coordinates属性的压缩算法

### ISSUE THREAD

**Issue by yalishizhude** [ecomfe/echarts-for-weixin#144]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
求mapData.js的coordinates属性的压缩算法~~~

**Comment by Ovilia** [comment]
与本项目无关
