### ISSUE TITLE
z-index对绘制出来的图表失效,如何解决

### ISSUE THREAD

**Issue by hexingnmxy** [ecomfe/echarts-for-weixin#145]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
小程序开发时,echarts绘制雷达图,雷达图覆盖到了其他任何元素之上,设置z-index无效,
模拟器上正常显示

### 预期效果：
![image](https://user-images.githubusercontent.com/22442909/38776089-07186410-40c4-11e8-896a-4619efc66f33.png)

### 实际效果：
![_20180415154659](https://user-images.githubusercontent.com/22442909/38776113-59467c86-40c4-11e8-8f37-d99b7fe7fc87.jpg)

### 复现环境：
- [] 在微信开发工具中不存在这个问题
- [] 在真机上存在该问题

**Comment by hexingnmxy** [comment]
刚刚查找文档,cover-view好像实现不了那个效果,canvas组件是原生组件,层级最高,所以z-index是生效的
页面布局,是顶部有个导航栏,图表绘制在中间主体内容部分,
中间主体内容很多,向上滑动时,图表会超出范围,就会在真机上出现图表盖住顶部导航栏,
请教各位如何处理这个问题
请教各位,如何处理这个问题

**Comment by Ovilia** [comment]
#84
