### ISSUE TITLE
dataZoom数据区域缩放在苹果手机上不显示，开发工具和Android可以

### ISSUE THREAD

**Issue by victorLyw** [ecomfe/echarts-for-weixin#149]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
dataZoom数据区域缩放在苹果手机上不显示，开发工具和Android可以

### 预期效果：
![1524033630 1](https://user-images.githubusercontent.com/37405318/38915537-acc9f67c-4316-11e8-9cbc-4e3d217703c0.png)

### 实际效果：
![1524033759 1](https://user-images.githubusercontent.com/37405318/38915589-d75ce8e0-4316-11e8-9fea-b0761e104d8f.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by auroradcx** [comment]
我和你问题类似，我的图例不显示，但图例放在grid区域里面的时候就能显示。
也是只有苹果真机不行，你注意看你的数据标签也是在grid区域里才能显示。

**Comment by Ovilia** [comment]
同 #52，目前尚未修复，在等待小程序团队解决，请关注 #52
