### ISSUE TITLE
canvas对象获取问题

### ISSUE THREAD

**Issue by LTMana** [ecomfe/echarts-for-weixin#15]
`
echarts.init(canvas, null, {
    width: width,
    height: height
  });
`
canvas对象如何在onLoad或onReady或onShow里获取

**Comment by Ovilia** [comment]
可以把 `canvas` 变量存下来，类似 https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/bar/index.js 这里 `chart` 变量的做法

**Comment by LTMana** [comment]
这种方法确实可行但需要加一个setTimeOut的延迟执行函数，有没不加这函数也能获取的办法呢

**Comment by Ovilia** [comment]
initChart 就是一个回调函数，调用到这里的时候就是获取到的时候
