### ISSUE TITLE
微信小程序使用line组件，超过两条，title不显示

### ISSUE THREAD

**Issue by ZSH-HSZ** [ecomfe/echarts-for-weixin#153]
在使用line组件的时候，legend有2条以上数据的时候，在小程序里不显示title（我不知道可以点击的东西学名叫什么），但是在模拟器上是正常的。模拟器版本1.02.1804120，真机iPhone X，iPhone 8，系统11.3
![48dc57c39d7f9aa4246b42fa6312da4d](https://user-images.githubusercontent.com/31639046/38939825-59b20b4c-435b-11e8-8d6c-7d7f6b717356.png)

**Comment by Ovilia** [comment]
同 #52
