### ISSUE TITLE
饼图选择一个属性不显示时，显示效果错误

### ISSUE THREAD

**Issue by phpjishu** [ecomfe/echarts-for-weixin#155]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [X] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [X] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
饼图选择一个属性不显示时，显示效果错误
### 预期效果：
<img width="645" alt="_20180420112829" src="https://user-images.githubusercontent.com/6937002/39029369-ff6db86e-448d-11e8-8992-c34e07f4bb48.png">

### 实际效果：
<img width="278" alt="_20180420112331" src="https://user-images.githubusercontent.com/6937002/39029372-0526f19e-448e-11e8-849e-de7d7450b57e.png">

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [X] 在真机上存在该问题

**Comment by phpjishu** [comment]
经测试其他图形，都会出现类似问题，官方例子也是存在类似的问题

**Comment by Ovilia** [comment]
#27
