### ISSUE TITLE
iphone和android小程序图表颜色显示不一致的问题

### ISSUE THREAD

**Issue by chudongyang** [ecomfe/echarts-for-weixin#161]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [X] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [X] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在真机测试上，ios系统的图表颜色显示不对，iphone6和iphone7 plus都显示不正确；但是android显示没有问题！请官方或者哪位知情大神告知解决办法，比较着急在线等，万分感谢！

### 预期效果：
![39170341-baf0701c-47cd-11e8-8bad-2c6360522145](https://user-images.githubusercontent.com/22430323/39223421-9d363190-4874-11e8-94a7-cc34becfae5a.jpg)

（如有需要请提供预期的图）

### 实际效果：
![39170317-a66a7368-47cd-11e8-865c-4afc381bd6fe](https://user-images.githubusercontent.com/22430323/39223429-ac9d9b6e-4874-11e8-91ee-2b282d2332aa.jpg)

（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [X] 在真机上存在该问题

**Comment by fanmx** [comment]
遇到了同样的问题，背景分割线影响到了折线样式，颜色还很模糊。。。

**Comment by Ovilia** [comment]
虚线的问题，小程序团队反馈说正在提审了，估计快上线了

**Comment by chudongyang** [comment]
😊很棒啊，希望赶快上线咯

**Comment by chudongyang** [comment]
大赞，是不是虚线的问题解决了，ios颜色显示不对的问题也就解决了呢？

**Comment by DivHao** [comment]
在areaStyle里面设置  shadowColor: "#ffffff" 和 opacity: 0.5  这样就可以差不多一样了,

**Comment by chudongyang** [comment]
楼上，我设置了貌似不行啊，ios颜色还是不对

**Comment by DivHao** [comment]
应该是可以的啊   我就是这样设置的

**Comment by chudongyang** [comment]
兄弟，可以贴一下你的areaStyle里的代码吗？然后看下ios效果

**Comment by Ovilia** [comment]
透明度的问题已修复，虚线的问题关注 #194
