### ISSUE TITLE
有没有人实现了wx.request请求后，改变data里的数据

### ISSUE THREAD

**Issue by qh96** [ecomfe/echarts-for-weixin#164]
如何实现后台数据与前台的交互？个人感觉有点困难

**Comment by chudongyang** [comment]
请求到数据之后再去初始化图表，使用  延迟加载  模式

**Comment by wangchao523** [comment]
参考这个实现，我参考这个做了柱状图，非常好使。
https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/lazyLoad/index.wxml

**Comment by youngjuning** [comment]
https://github.com/youngjuning/wxPromise

https://github.com/youngjuning/wxPromise/blob/master/detail/lazyInitChart.md

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/39662154-ff4311fa-508f-11e8-88f3-972857837f30.png)

**Comment by youngjuning** [comment]
我封装了一下初始化和更新组件的方法，大佬们可以了解下

**Comment by shichm** [comment]
我为什么会提示selectComponent 函数不存在
