### ISSUE TITLE
延迟加载的方式加载图表图表不能点击选择

### ISSUE THREAD

**Issue by passer101** [ecomfe/echarts-for-weixin#168]
使用延迟加载的方式加载图表，先wx.request获取到数据后，再加载图表。但是加载图表后，zoom不能使用，显示了放大控件出来了，但是不能使用。分类不能点击。
可用官方demo复现bug。求解决这个问题。
![image](https://user-images.githubusercontent.com/26435014/39395808-d690a940-4b15-11e8-979e-1e896101288e.png)

**Comment by hepking** [comment]
也碰到了

**Comment by crazyurus** [comment]
```
ecComponent.init((canvas, width, height) => {
    const chart = echarts.init(canvas, null, {});
     // 最后加上
    return chart;
});
```
