### ISSUE TITLE
echarts做的微信小程序

### ISSUE THREAD

**Issue by ymli1981** [ecomfe/echarts-for-weixin#170]
小程序比较简单，但也费了不少心思
用到了折线图、散点图、漏斗图、旭日图、关系图，直角坐标系/极坐标系
感谢百度echarts团队，你们的工作非常棒！
![_20180430093620](https://user-images.githubusercontent.com/31526236/39413237-f5ae4eaa-4c59-11e8-891f-fe722260549f.jpg)

**Comment by abing220** [comment]
赞一个，加微信交流一下  a_bing220

**Comment by HeberLee** [comment]
我使用之后发现你的图表可以实现交互，想问一下如何实现的。因为我用web可以实现图表随着用户操作而改变，但是小程序版就会报错

**Comment by gjwnj** [comment]
可以交流一下怎么做动态交互的吗

**Comment by ymli1981** [comment]
其实很简单，就是在echart上面加了层canvas，
判断点击了哪个位置，修改data值，重置echart

**Comment by youngjuning** [comment]
@ymli1981 代码没有开源吗？你那个左滑删除用的什么插件呢？还是说你自己造的轮子，求分享

**Comment by ymli1981** [comment]
这个就是个scroll-view

**Comment by HeberLee** [comment]
@gjwnj 我的本意是在用户提交数据后，先用wx.request到后台获取数据后再次调用图表生成方法initChart（）来生成新的图表，但是发现调用initChart会报错，然后我继续查看其他issues，看看能否找到解决办法。最后我的方法是不调用initChart，而是通过全局化chart（在js开头使用let chart = null），再在request的success回调函数里通过chart.setOption(option)来更新图表，测试方法可行。不过注意要在chart.setOption之前用chart.clear来清除之前的图表，否则会出现一个非常奇怪的图表。

**Comment by youngjuning** [comment]
@HeberLee https://github.com/youngjuning/wxPromise/blob/master/detail/lazyInitChart.md

**Comment by youngjuning** [comment]
@HeberLee 能详细说下你更新图表的方法吗？我这边封装的懒加载初始化，更新图表就是调用这个方法就可以，你可以了解一下给点意见

**Comment by youngjuning** [comment]
@HeberLee 根据的方案，我封装了 `updateChart(chart,option)`，感兴趣可以交流一下

**Comment by gjwnj** [comment]
@youngjuning 是的，不过用到的地方不是很多，就没做封装。

**Comment by youngjuning** [comment]
嗯，我是封装到开源库中了。

**Comment by youngjuning** [comment]
https://github.com/youngjuning/wxPromise 大佬，没事给个星星

**Comment by gjwnj** [comment]
支持开源，可惜不是大佬。

**Comment by youngjuning** [comment]
哈哈，太谦虚了

**Comment by ymli1981** [comment]
根据用户数据生成新表，在onload里直接更新chart就可以，initchart也可以保留，不会出错
出错肯定是你代码有问题

**Comment by xikaka** [comment]
tooltip 这个属性不起作用，怎么办
