### ISSUE TITLE
在<scroll-view scroll-y="true">中，echarts图表不显示

### ISSUE THREAD

**Issue by cassiopeiaofmax** [ecomfe/echarts-for-weixin#171]
### 简单描述问题：
如题，在\<scroll-view scroll-y="true"\>中，echarts图表不显示。
微信开发环境中是好的，真机上存在问题

### 复现环境：
- [x] 在真机上存在该问题

**Comment by abing220** [comment]
你用的是不是map？
https://developers.weixin.qq.com/miniprogram/dev/component/map.html#map
Bug & Tip
tip: map 组件是由客户端创建的原生组件，它的层级是最高的，不能通过 z-index 控制层级。
tip: 请勿在 scroll-view、swiper、picker-view、movable-view 中使用 map 组件。
tip: css 动画对 map 组件无效。
tip: map 组件使用的经纬度是火星坐标系，调用 wx.getLocation 接口需要指定 type 为 gcj02

**Comment by alexgogoing** [comment]
你的图表是否在tab页中的非第一页?是的话应该是用lazyload按需加载
