### ISSUE TITLE
小程序集成ECharts地图，点击中国地图进入省份地图，如何获取点击的省份名称？

### ISSUE THREAD

**Issue by abing220** [ecomfe/echarts-for-weixin#172]
### 简单描述问题：
ECharts地图，点击中国地图进入省份地图，如何获取点击的省份名称？
备注：中国地图option data 中有各个省份的名称。

### 预期效果：
http://gallery.echartsjs.com/editor.html?c=xH14AUvnUW   微信中实现网页中的类似效果

**Comment by qq137647259** [comment]
在option里写如下代码：chart.on('click',function(res){
    console.log(res.name)
  })

**Comment by abing220** [comment]
这个代码在网页版中可以用，在微信我试了好像不行，微信里没有click事件

**Comment by jubenying** [comment]
可以的
 initEChart(e) {
  chart = e.detail;
  if (!chart) return
chart.on("click", function(params) {
            console.log(params.data.name)
            if (params.data.code == "340000") {
                 wx.navigateTo({
                        url: '../map/map?proviceId=' + params.data.code
                    });
             }else {
               wx.navigateTo({
                        url: '../shoplist/shoplist?type=get&provinceCode=' + params.data.code
                    })
             
            }
        });
}

**Comment by abing220** [comment]
谢谢@jubenying  ， 周末试了一下，it works， great thanks ：）

**Comment by 1546811268** [comment]
请问小程序中如何使用地图，能给我发下代码片段？谢谢

**Comment by huangligen** [comment]
这个百度不是有教程吗。。。



------------------ 原始邮件 ------------------
发件人: "1546811268"<notifications@github.com>; 
发送时间: 2019年5月22日(星期三) 晚上7:49
收件人: "ecomfe/echarts-for-weixin"<echarts-for-weixin@noreply.github.com>; 
抄送: "初识你名"<137647259@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ecomfe/echarts-for-weixin] 小程序集成ECharts地图，点击中国地图进入省份地图，如何获取点击的省份名称？ (#172)




请问小程序中如何使用地图，能给我发下代码片段？谢谢

**Comment by yuhaipeng007** [comment]
@abing220 @jubenying 你们好，这个函数具体要写在哪里呀，能否告知一下，谢谢
