### ISSUE TITLE
小程序无法用bar3D（3D柱状图）吗？

### ISSUE THREAD

**Issue by LarryLawrence** [ecomfe/echarts-for-weixin#173]
使用```type: 'bar3D',```的时候运行报错：
```
Error: Component series.bar3D not exists. Load it first.
```
搜索得知可能是demo中的707kb的那个echarts.js不包含gl组件。于是官网下载了2.4MB的完整版echarts.js，运行仍提示这个错误。但是又发现，在编译后似乎echarts.js又被替换成了707kb的那个，于是删除echarts.js再编译，果然又自动生成了一个707kb的echarts.js。是不是跟这个有关呢？还是说就不支持bar3D？谢谢

**Comment by Ovilia** [comment]
不支持，3D 需要 WebGL 支持，无法在小程序中实现

**Comment by jintangWang** [comment]
![image](https://user-images.githubusercontent.com/12557847/60895185-c37c2d00-a296-11e9-8c8e-8ab2233c9e98.png)
请问现在可以使用3d了吗？
