### ISSUE TITLE
两个月不更新了，是不是不管事了？

### ISSUE THREAD

**Issue by Rainylane** [ecomfe/echarts-for-weixin#175]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
两个月不更新了，要黄了？

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by chudongyang** [comment]
看来是太忙了，顾不上这边了，小程序图表的需求量看来还是不大

**Comment by hepking** [comment]
很大需求啊，我这有不少大项目，是他们不给力

**Comment by youngjuning** [comment]
不不，可能在憋大招 哈哈

**Comment by 252860883** [comment]
现在写小程序最怕的就是画图表了，各种心塞

**Comment by doukemao** [comment]
凉了吧

**Comment by kukujbb** [comment]
各位试过在wepy上使用吗？

**Comment by Ovilia** [comment]
绝大部分问题都是通过跟小程序团队排查、反馈问题，最终在小程序基础库里修改，所以这个项目的代码可能改动不频繁。欢迎大家提 PR 啊，实在是忙不过来~
