### ISSUE TITLE
求助：小程序需要全国及各省市地图，但地图js文件大小超过小程序限制，怎么解决？

### ISSUE THREAD

**Issue by abing220** [ecomfe/echarts-for-weixin#179]
### 简单描述问题：
小程序需要全国及各省市地图，但地图js文件大小超过小程序限制，怎么解决？
import china from './chinaMap/china.js';   // 本地可以使用，但是多个地图超过了小程序包2M限制；

本地尝试了URL 方式 import china from 'http://127.0.0.1:8080/examples/chinaMap/china.js'   失败了

有没有类似URL的方式，将地图文件放在网络侧，绕过小程序包大小限制呢？

先谢过：）

**Comment by Arsennnic** [comment]
json放在自己的服务器上get/post一下
可以wx.setStorage存在本地方便以后调用

**Comment by jubenying** [comment]
也遇到过这个问题，放服务器上就可以了
wx.request({
      url: `https://weixin.hazq.com/miniprogramassets/map/${name}.json`,
      method: "GET",
      success: (res) => {
        cb(null, name, res.data);
        wx.setStorage({
          key: key + name,
          data: res.data,
          success: () => { }
        });
      },
      fail: () => {
        cb(new Error("get map data fail"));
      },
      complete: () => {
        wx.hideLoading()
      }
    });
