### ISSUE TITLE
区域缩放图表显示不全

### ISSUE THREAD

**Issue by albertli2333** [ecomfe/echarts-for-weixin#180]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
小程序使用区域缩放datazoom功能时，图表数据显示不全。

### 预期效果：
？？？
（如有需要请提供预期的图）
![_15256613198751](https://user-images.githubusercontent.com/26435014/39682966-636f1d26-51e5-11e8-89cc-3f136f08f879.png)

### 实际效果：
？？？
（如有需要请提供截图）
![_15256615334855](https://user-images.githubusercontent.com/26435014/39682829-bc5090ce-51e4-11e8-983b-311ec0f1ff8e.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题
复现：官方demo中pages/line/index中option可改为如下：
  var option = {
    backgroundColor: "#fff",
    color: ["#37A2DA", "#67E0E3", "#9FE6B8"],

    tooltip: {
      trigger: 'axis'
    },
    legend: {

      data: ['A商品', 'B商品', 'C商品']
    },
    grid: {
      containLabel: true
    },
    dataZoom: [{ show: true, realtime: true, start: 0, end: 100 }],
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
    },
    yAxis: {
      x: 'center',
      type: 'value'
    },
    series: [{
      name: 'A商品',
      type: 'line',
      smooth: true,
      data: [18, 36, 65, 30, 78, 40, 33]
    }, {
      name: 'B商品',
      type: 'line',
      smooth: true,
      data: [12, 50, 51, 35, 70, 30, 20]
    }, {
      name: 'C商品',
      type: 'line',
      smooth: true,
      data: [10, 30, 31, 50, 40, 20, 10]
    }]
  };
即添加一行代码：dataZoom: [{ show: true, realtime: true, start: 0, end: 100 }],

**Comment by Ovilia** [comment]
真机还是开发工具有问题？

**Comment by passer101** [comment]
@Ovilia 真机开发工具都是
