### ISSUE TITLE
图表能不能不自动init呀

### ISSUE THREAD

**Issue by haitaoxu** [ecomfe/echarts-for-weixin#187]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
不想自动触发charts的init方法

### 预期效果：

通过在option中配置是否自动init项来开启自动触发的事件。
然后调用chart.init，来初始化chart

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by wycyftk** [comment]
在一个页面中添加了两个雷达图，两个图成功的运行了，但是由于是左右切换，导致报了3个错
1.Cannot read property 'disableTouch' of null;at undefined page touchStart function
  TypeError: Cannot read property 'disableTouch' of null
2.Cannot read property 'disableTouch' of null;at undefined page touchMove function
  TypeError: Cannot read property 'disableTouch' of null
3.Cannot read property 'disableTouch' of null;at undefined page touchEnd function
  TypeError: Cannot read property 'disableTouch' of null

初始化的时候使用的懒加载，两个地方都是这么写的，数据上也没有问题。应该是在移动的echarts所产生的，看到上面说加上disableTouch:true 就可以解决，但是还是在报错
ec: {
      lazyLoad: true,
      disableTouch: true
    },

![image](https://user-images.githubusercontent.com/20632624/40269147-89355068-5bac-11e8-88c1-970c52ce4105.png)
