### ISSUE TITLE
求助！！！示例代码运行报错ReferenceError: echarts is not defined

### ISSUE THREAD

**Issue by windend** [ecomfe/echarts-for-weixin#188]
![image](https://user-images.githubusercontent.com/5136318/39877641-0be14e96-54a9-11e8-8ada-ab4c37b874cf.png)

**Comment by Ovilia** [comment]
echarts 没有加载成功，看看路径对不对

**Comment by chenhongen** [comment]
奇怪，加了ec-canvas文件，配置了下，路径没错。也出现这个问题。。

**Comment by ngto** [comment]
在你的js文件顶上引入
import * as echarts from '../../ec-canvas/echarts';

**Comment by lily92** [comment]
> echarts 没有加载成功，看看路径对不对

路径确认是对的，只是canvas文件夹不是放在根目录，放在分包里面

**Comment by cry101** [comment]
不知道解决没，我用的mpvue，实测是分包里被webpack编译了，所以echarts加载不对。在'babel-loader'那边加个
exclude: [resolve('src/pages/..路径./ec-canvas/echarts.js')]后是可以，还有整个组件要复制到对应目类，参考的这个https://blog.csdn.net/lydxwj/article/details/107193394
