### ISSUE TITLE
安卓环形图中间显示问题

### ISSUE THREAD

**Issue by shuaixiaoA** [ecomfe/echarts-for-weixin#196]
### 简单描述问题：
安卓环形图中间显示问题

### 预期效果：
![image](https://user-images.githubusercontent.com/31194898/39992641-0feb4014-57a6-11e8-8d2e-52f2c06a5893.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/31194898/39992660-237b501a-57a6-11e8-9122-03a6174d509f.png)

### 复现环境：
在微信开发工具中不存在该问题
在安卓真机上存在该问题，苹果不存在

**Comment by Ovilia** [comment]
#167
