### ISSUE TITLE
echarts可以实现x轴不等间距分布吗？

### ISSUE THREAD

**Issue by xiongjunhao** [ecomfe/echarts-for-weixin#198]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
实现x轴上不等间距分布，看下图。

### 预期效果：
![image](https://user-images.githubusercontent.com/24384346/40032073-23a6f1a0-5825-11e8-8906-218202bf9e1c.png)

x轴上的数值，间隔不等

**Comment by Ovilia** [comment]
请到 ECharts 项目提问
