### ISSUE TITLE
真机调试时，echarts视图层会悬浮在所有视图之上

### ISSUE THREAD

**Issue by EternalChildren** [ecomfe/echarts-for-weixin#199]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
模拟器上调试并无问题，但是使用构建或者真机调试时，echarts图表会在非焦距状态会悬浮在最上层，
 `<scroll-view class='scroll_view' scroll-y>` 
    `<view class='chart_view'>`
      `<ec-canvas id="chart_strategy" canvas-id="strategy" ec="{{ ec }}"></ec-canvas>`
    `</view>`
`</scroll-view>`

我不知道是不是 scroll-view的原因
### 预期效果：
图表应该被限制在view里，并能随之滑动
（如有需要请提供预期的图）

### 实际效果：
scrollview滑动时，图表并不会滑动 而是悬浮于最上层 会覆盖所有视图
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题
版本库2.0.2

**Comment by lzj723** [comment]
确实是，在微信开发者工具中开发完，准备提测才发现图表会一直浮在所有图层上

**Comment by EternalChildren** [comment]
做一些补充，这个问题应该是存在与scroll-view，只要canvas不绘制于scroll-view而是采用页面的高度让页面支持滑动就可以解决，但是还是希望开发者能够支持这个绘制能够在scroll-veiw中使用

**Comment by Yidadaa** [comment]
这是微信小程序本身的缺陷，参考[官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html#canvas)的bug&tip部分：
>Bug & Tip
tip: canvas 组件是由客户端创建的原生组件，它的层级是最高的，不能通过 z-index 控制层级。
tip: 请勿在 scroll-view、swiper、picker-view、movable-view 中使用 canvas 组件。
tip: css 动画对 canvas 组件无效。
bug: 避免设置过大的宽高，在安卓下会有crash的问题
