### ISSUE TITLE
微信版本疑问

### ISSUE THREAD

**Issue by WuHuaJi0** [ecomfe/echarts-for-weixin#2]
我在用的开发包不是最新的，所以得到这样的提示：
> This version of Wexin is not supported by ECharts. Please update Wexin with versions after 1.9.90

这个问题通过升级微信开发工具解决了，由此引出一个疑问，echarts-for-weixin 是否也对微信版本有所要求，也就是说：稍老的微信客户端是否也能使用？如果有要求，请求具体的版本是如何呢？

谢谢：）

参考微信兼容性文档：https://mp.weixin.qq.com/debug/wxadoc/dev/framework/compatibility.html

**Comment by Ovilia** [comment]
微信版本 >= 6.6.3，更新过文档了，谢谢

**Comment by WuHuaJi0** [comment]
补充，对于这个1.9.90的版本提示，微信文档中找不到相关的版本号提示，是否提示有误？
参考文档：https://mp.weixin.qq.com/debug/wxadoc/dev/framework/client-lib.html

这里的兼容性应该和小程序基础库相关的吧？如果是那就是可以参考微信文档中，基础库版本分布，确知版本在用户中的兼容情况？不知这样理解是否对

**Comment by Ovilia** [comment]
和小程序团队沟通了一下，应该是微信版本 >= 6.6.3，对应基础调试库 >= 1.9.91。
微信版本和基础调试库的版本是对应的，你需要做的就是：

- 调试的时候，需要在微信开发者工具中，将“详情”下的“调试基础库”设为 1.9.91 及以上版本。
- 发布前，需要在 [https://mp.weixin.qq.com](https://mp.weixin.qq.com) 的“设置”页面，将“基础库最低版本设置”设为 1.9.91。当用户微信版本过低的时候，会提示用户更新。

一般情况下不需要写代码做额外的判断。除非你想让用户及时在微信版本低的情况下，虽然不能使用 ECharts，但是还是可以使用你的小程序。这种情况下，你就在设置页面将基础库最低版本设高一点，然后根据 https://mp.weixin.qq.com/debug/wxadoc/dev/framework/compatibility.html 做特殊处理。

我更新了一下 README，希望现在更清楚一些了，谢谢！
