### ISSUE TITLE
在图表区域内触摸移动滚动页面

### ISSUE THREAD

**Issue by ymli1981** [ecomfe/echarts-for-weixin#212]
// 如果想要禁止触屏事件，以保证在图表区域内触摸移动仍能滚动页面，
      // 就将 disableTouch 设为 true

测试了一下，在图表区域内触摸时，页面不会滚动
苹果手机

**Comment by Ovilia** [comment]
已修复，现在应该正常了，试一下

**Comment by youmyyou** [comment]
图表区域内禁止触摸后，导致legend点击也无效。这个问题有解决方案吗
