### ISSUE TITLE
在小程序中function initChart()中怎么调用当前data

### ISSUE THREAD

**Issue by ChineseHero** [ecomfe/echarts-for-weixin#216]
### 在小程序中echart初始化function initChart()中怎么调用当前data
在方法里用this.data好像不能调用，有什么方法可以获取

### 预期效果：
达到动态更改属性值

**Comment by 342688695** [comment]
延迟加载了解一下

**Comment by ChineseHero** [comment]
已经解决了，另建立一个js把初始化代码放进去写成一个方法，通过自己传入参数来更改数据。
