### ISSUE TITLE
图标在view，container的样式position必须要设置成absolute才能显示么？

### ISSUE THREAD

**Issue by pinkpear** [ecomfe/echarts-for-weixin#22]
高度怎么能设置成自适应啊，还是只能是指定高度才能完整显示？

**Comment by Ovilia** [comment]
这个是小程序的问题吧，你怎么在小程序里写定位就怎么写

**Comment by pinkpear** [comment]
那图表的大小只能指定不能自适应对吧？高度不设置，就显示不出来了。

**Comment by Ovilia** [comment]
有高度就行，可以是百分比形式的或像素值，跟小程序中的其他元素一样

**Comment by cfangxx** [comment]
做出来的效果, 图表始终fixed 在页面底部, 样式改了也没用
