### ISSUE TITLE
关于在图表上, 上下滑动页面的问题？

### ISSUE THREAD

**Issue by AlanZou007** [ecomfe/echarts-for-weixin#220]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
手机上， 在图表上下滑动会出现不能滑动或者页面卡顿的情况

### 预期效果：
预期是可以正常流畅滑动的

### 实际效果：
手机上， 在图表上下滑动会出现不能滑动或者页面卡顿

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
请参考这个例子 https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/move/index.js#L16

**Comment by AlanZou007** [comment]
@Ovilia 我看了, 我希望的时候可以左右滑动, 在该图表上下滑动页面的时候, 不会卡顿或者滑动不了的情况.

**Comment by Ovilia** [comment]
不了解你什么意思？

**Comment by AlanZou007** [comment]
@Ovilia  你好, 我设置了dataZoom. 需求就是要左右滑动. 但是我图表上, 上下滑动的时候, 页面的滑动条滑动不了.

**Comment by Ovilia** [comment]
是想图表内 dataZoom 滚动，还是说图表阻碍了外面的滚动？

**Comment by AlanZou007** [comment]
@Ovilia  后者, 前者滚动也不流畅

**Comment by ZadaWu** [comment]
> @Ovilia 后者, 前者滚动也不流畅

想问一下，后面是怎么解决的这个问题，如何仅设置左右 ？
