### ISSUE TITLE
scroll-view内绘图，图形不可以滚动

### ISSUE THREAD

**Issue by lqwgit** [ecomfe/echarts-for-weixin#225]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
如果把<ec-canvas />放在微信提供的<scroll-view />内，绘制出的图像不会随着scroll-view的上下滚动而滚动

### 预期效果：
绘制出的图形随着scroll-view 的上下滚动而滚动
（如有需要请提供预期的图）

### 实际效果：
scroll-view内的文字滚动，而绘制出的图形不滚动
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by ttylikl** [comment]
微信官方文档已经提示，scroll-view和canvas不能一起用。你应该遇到的是这个问题

**Comment by wuwuFQ** [comment]
那怎么让他随着scroll-view滚动呢？大家都怎么做的？
