### ISSUE TITLE
echarts 在小程序基础库2.1.0 上渲染速度灰常慢（在2.1.0 之前的不会），望修复~

### ISSUE THREAD

**Issue by zcanjie** [ecomfe/echarts-for-weixin#230]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
echarts 在小程序基础库更新到 2.1.0 的时候，渲染速度突然变慢了，有时候还会卡顿。。而在其它基础库则不会。

### 预期效果：
这里跑的是echarts example 的代码，希望效果跟 2.1.0 之前的库一样，而不是到 2.1.0 的时候渲染速度变慢。。

### 实际效果：
渲染速度比2.1.0 之前的基础库慢了 1~2s 左右。

### 复现环境：
可以直接跑echart 的example, 基础库更新到 2.1.0 即可复现。

**Comment by TupleNx** [comment]
这个问题确实存在，

**Comment by kawaiiz** [comment]
+1 ios 已经炸了

**Comment by zcanjie** [comment]
端午要加班的节凑😫

**Comment by yexiaoxiao** [comment]
中招了，还有一个小时就要给老板演示，这回坑大发了

**Comment by yuzexing** [comment]
试了一下ant f2 是没问题的，希望echart可以给予反馈

**Comment by Herrengit** [comment]
希望echart快点修复

**Comment by Ovilia** [comment]
已修复，请更新到最新版的微信
