### ISSUE TITLE
真机运行，图表始终比悬浮层的层级都要高，我也试着去JS源码中修改，但是没有成功，请问这个该怎么解决

### ISSUE THREAD

**Issue by laiwoyaojubaoni** [ecomfe/echarts-for-weixin#237]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by hdgao** [comment]
这个没办法的，微信小程序中canvas具有最高层级

**Comment by leo725** [comment]
运用微信小程序组件  <cover-view></cover-view>。这个组件会在canvas之上。切记，cover-view要写在ec-canvas 之后

**Comment by Ovilia** [comment]
#84

**Comment by stillsilly** [comment]
> 运用微信小程序组件 】cover-view。这个组件会在canvas之上。切记，cover-view要写在ec-canvas 之后

你真聪明，谢谢~~
