### ISSUE TITLE
地图插件，在手机端另存为图片，就会出现黑色区域和黑色线条，在电脑端开发工具里没有

### ISSUE THREAD

**Issue by tu6ge** [ecomfe/echarts-for-weixin#253]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息
![e0b399ef6fdaec685d6777e58ed5309c](https://user-images.githubusercontent.com/4115242/42120536-50f25ab6-7c4f-11e8-9f3e-7e271a2cf124.png)

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
地图插件，在手机端另存为图片，就会出现黑色区域和黑色线条，在电脑端开发工具里没有

### 预期效果：
没有黑框，黑色线条

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [x] 在真机上存在该问题

**Comment by tu6ge** [comment]
刚才拿苹果手机测了一下，是没问题的，安卓手机有问题，是手机性能导致的？

**Comment by mirari** [comment]
我这里也是安卓手机普遍存在这个问题，animation: false已经加了，draw以后还特地加了延迟再转图片，仍然会出现折线或者圆点变成黑色的情况，IOS则正常

**Comment by chjish28461** [comment]
配置下echarts的background：“#fff”就好了 @tu6ge

**Comment by tu6ge** [comment]
谢谢，已经跳槽了
