### ISSUE TITLE
通过ajax请求过来的数据怎么显示到统计图中?

### ISSUE THREAD

**Issue by hujialianghuwei** [ecomfe/echarts-for-weixin#254]
如图所示，Page()外面的函数怎么拿到page()data里的值

**Comment by jiangjinze20** [comment]
我也遇见了额这个问题,,解决了吗

**Comment by Ovilia** [comment]
参考 https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/bar/index.js#L133 在这行写 chart.setOption

**Comment by Bluergao** [comment]
请问解决了吗？我在onready中使用chart.setOption报错chart为null。。。
