### ISSUE TITLE
有没有其他办法实现tooltip

### ISSUE THREAD

**Issue by xiaoyingzhi** [ecomfe/echarts-for-weixin#263]
有没有其他办法实现tooltip，没有这个功能真的非常影响查看数据，特别是线图。

**Comment by Sandra310** [comment]
me too!

**Comment by dreamsk** [comment]
根据formatter得到的数据通过cover-view自定义

**Comment by shanlh** [comment]
可以改echarts源码，实现的差不多了，有个wxa的属性改成false，之后会有报错，对应的来改。
tooltip在echarts里是会创建element的，在小程序里可以写个cover-view取代，设置style、display的地方会报错，改成setData来实现，源码是会把dom准备好，然后innerHTML进去的，小程序这边可以在formatter里准备好数据，然后再双花括号显示，就没必要改那块拼接dom的代码了。
其他在隐藏tooltip的时候可能会有点问题，我还在研究，暂时是在手指离开的时候手动触发touchmove到屏幕外，触发隐藏（普通的dispatchAction({type:'hideTip'})不会隐藏垂直辅助线）

**Comment by liaoyanqi** [comment]
同求，貌似 腾讯自选股 这个小程序实现了

**Comment by Ovilia** [comment]
等 ECharts 下个版本发版就可以用了，目前急用的话，可以自行编译 https://github.com/apache/incubator-echarts

**Comment by Ovilia** [comment]
#4

**Comment by liaoyanqi** [comment]
chart.on("mousedown", function (params) {
          console.log(params);
      });
试一下这个代码，会对你实现tooltip有帮助。不过现在官方文档已经支持更新tooltip了
