### ISSUE TITLE
echarts文件过大，图表显示不出来

### ISSUE THREAD

**Issue by crazy-wang** [ecomfe/echarts-for-weixin#267]
![image](https://user-images.githubusercontent.com/24617035/42750311-64216a74-8919-11e8-8210-08fee99da2f1.png)
控制台报错：以下js文件过大（超过500k），已跳过es6转es5和压缩的处理：
ec-canvas/ceharts.js

**Comment by 3anLouYouGu1** [comment]
这个没影响。

**Comment by ZhuRuiHeng** [comment]
编译后提示 vendor.js文件过大，代码包大于2M

**Comment by ZhuRuiHeng** [comment]
编译后提示 vendor.js文件过大，代码包大于2M,怎么解决呢

**Comment by 3anLouYouGu1** [comment]
@ZhuRuiHeng 我使用这个插件并没有用到vendor.js。如果代码包太大估计只有用wx-charts。wx-charts好像很久没更新了。本来想用echarts看会不会更新快点的，解决wx-charts的一些bug。但是结果好像是一样的。提了问题都没人回答。

**Comment by Ovilia** [comment]
打包的时候使用压缩版的 echarts

**Comment by ZhuRuiHeng** [comment]
@3anLouYouGu1 @Ovilia 好的谢谢，用了echarts可以了

**Comment by keminu** [comment]
开发工具不压缩，可以自己手动压缩。这样就小了
