### ISSUE TITLE
饼图点击图例显示异常

### ISSUE THREAD

**Issue by ricky-liu** [ecomfe/echarts-for-weixin#27]
![image](https://user-images.githubusercontent.com/36980393/36884963-196dc438-1e1f-11e8-8edb-e75f0344493b.png)

![image](https://user-images.githubusercontent.com/36980393/36885005-46d84a92-1e1f-11e8-9673-81af317c7023.png)

**Comment by hoganjobs** [comment]
关注，不知道这个当前版本是否已修复可用。

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
