### ISSUE TITLE
小程序echarts图页面分享出去后，从分享的页面进入小程序，echars图不能正常显示

### ISSUE THREAD

**Issue by LawrenceQxy** [ecomfe/echarts-for-weixin#277]
小程序echarts图页面分享出去后，从分享的页面进入小程序，echars图不能正常显示，重新进入页面后能够正常显示；
正常状态：
![image](https://user-images.githubusercontent.com/25606942/43499124-a116575e-957c-11e8-8eca-2afa425c177c.png)
分享页面进入：
![image](https://user-images.githubusercontent.com/25606942/43499101-8b3a91a2-957c-11e8-834c-cb04bf639725.png)

**Comment by kcjian** [comment]
@LawrenceQxy 请问解决了吗
