### ISSUE TITLE
为什么无法实现实例化啊

### ISSUE THREAD

**Issue by JeoyZhang** [ecomfe/echarts-for-weixin#28]

**Comment by Ovilia** [comment]
文档看了吗？FAQ 看了吗？照着 issue 模板里面的步骤做了吗？什么信息都不提供，没头没尾地这么说一句，怎么给你排查问题？你这样提 issue 是对开源项目和开发者的不尊重，大家都有很多需求，开发者不得不因为这类的 issue 浪费很多时间，对你也很难有有效的帮助。

**Comment by JeoyZhang** [comment]
@Ovilia 抱歉抱歉，是我自己的原因，对于这没头没脑的问题感到抱歉，也对自己的行为感到抱歉。小程序echarts应用很赞，也期待了很久，多谢你们的辛苦和付出
