### ISSUE TITLE
同一个页面实现两个相同的图标封装成组件

### ISSUE THREAD

**Issue by LeiDongMei** [ecomfe/echarts-for-weixin#282]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
因为项目需要展示的徒步类型相同，只是数据不一致，我就讲其二次封装使其可以按照我传入的数据定制化效果图吗，但是在我封装并调用后会变得不懂是异步还是什么的错误出现
![image](https://user-images.githubusercontent.com/23517470/43620176-ff9252a0-9703-11e8-9a2e-7f39e25ceb6b.png)

### 预期效果：
这个实在网页端的实现，已经完成
![image](https://user-images.githubusercontent.com/23517470/43620192-18f05922-9704-11e8-8d83-a946b71d20fb.png)

### 实际效果：
报错并无展示
![image](https://user-images.githubusercontent.com/23517470/43620205-29fd4ebe-9704-11e8-92ce-63fd8c6f1eb0.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by wangfpp** [comment]
@LeiDongMei 请问你是怎么做的 我也遇到同样的问题了

**Comment by daidaiLDM** [comment]
> @LeiDongMei请问你是怎么做的我也遇到同样的问题了
我修改了一下echart引用的源码，在ec-canvas里面的一些渲染有多个的图表渲染的时候会出现一些数据问题，你可以断点看看，应该能找到为什么

**Comment by wangfpp** [comment]
> > 我修改了一下echart引用的源码，在ec-canvas里面的一些渲染有多个的图表渲染的时候会出现一些数据问题，你可以断点看看，应该能找到为什么

我是吧ec-canvas二次封装成一个组建了  已经解决了 谢谢啊

**Comment by susan007** [comment]
> > > 我修改了一下echart引用的源码，在ec-canvas里面的一些渲染有多个的图表渲染的时候会出现一些数据问题，你可以断点看看，应该能找到为什么
> 
> 我是吧ec-canvas二次封装成一个组建了 已经解决了 谢谢啊

能分享一下你封装的组件吗？谢谢

**Comment by wangfpp** [comment]
@susan007  静静。。。不好意思啊  代码都找不到了

**Comment by susan007** [comment]
> @susan007 静静。。。不好意思啊 代码都找不到了

最后我参考掘金文章，修改了ec-canvas源码，加了一个params参数传进去。这样直接封装成组件了，参数传进去就行。
参考链接：https://juejin.im/post/5c74af0ef265da2dd0524c9e
