### ISSUE TITLE
wx:for中如何使用ec-canvas？

### ISSUE THREAD

**Issue by yequ1006** [ecomfe/echarts-for-weixin#288]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
1、我需要在wx:for中，对每个item里画图。画图使用数据为item从后台查询的数据。
2、参考Demo multiCharts做法，有个问题。在onReady中，用selectComponent取wx:for下组件为null。而取wx:for的组件是可以的。
3、还请提供wx:for中，每个item单独画图示例，各图数据不同

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
参考 multiCharts 但是要保证 
id 和 canvas-id 属性每个是不同的

**Comment by yequ1006** [comment]
有什么办法，让item的参数数据，传给onInit里面 ？

**Comment by Ovilia** [comment]
应该是你在 
js 里维护一个 
items 列表，传给 xml，onInit 的时候也直接用这个 items

**Comment by yequ1006** [comment]
解决了 非常感谢

**Comment by qzmly100** [comment]
这贴子别沉啊，不贴代码？

**Comment by qzmly100** [comment]
兄弟，我也想知道wx:for如何搭建使用es-canvas
