### ISSUE TITLE
页面没有图表显示

### ISSUE THREAD

**Issue by issac47** [ecomfe/echarts-for-weixin#29]
很奇怪。
在下载下来的Demo项目中修改一下数据，在页面中是会有变化的。
但是我按照提供的教程把ec-canvas目录拷贝到新建的一个项目中，再按照后续步骤完成了一个新的Demo，但是在页面中没有任何内容，控制台也没有提示任何错误。
我也试过复制ec-canvas目录和某个图表的代码到新demo中也无法显示任何图表。
基础调试库的版本是1.9.91。
我暂时还无法定位到底是哪里出了问题，不知道上面那个说无法实例化的同学是不是跟我是相同的问题

**Comment by zfn931230** [comment]
哥们你问题解决了么，出在哪里

**Comment by issac47** [comment]
我记得好像是我app.wxss中的哪个样式忘了复制

**Comment by chenhongen** [comment]
同问
