### ISSUE TITLE
配置series中label里的backgroundColor 为image时小程序报错

### ISSUE THREAD

**Issue by Toffee24** [ecomfe/echarts-for-weixin#290]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
现在做一个map类型的Echarts,以一个省为地图,需要在地图上的市旁边加上一个小箭头的图片辨识,查阅文档发现backgroundColor:{image:''} 可以实现.配置之后小程序运行报错 ReferenceError: Image is not defined,浏览器下可以实现这个效果

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Yeecoder** [comment]
您好，请问这个问题最终如何解决的呢，我们也在小程序遇到了相同问题
