### ISSUE TITLE
关于折线图表适配的问题

### ISSUE THREAD

**Issue by AlanZou007** [ecomfe/echarts-for-weixin#299]
- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
折线图在iphoneX变成虚线

### 预期效果：
![image](https://user-images.githubusercontent.com/24911981/44503797-d7dd2880-a6ca-11e8-98ea-7e6c5fdc5eda.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/24911981/44503857-2ee2fd80-a6cb-11e8-8265-479e5f85467b.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by AlanZou007** [comment]
version：v4.1.0.rc2

**Comment by Ovilia** [comment]
这不是 ECharts 的问题，所以放 ECharts 版本号没用，应该放真机或开发工具的版本号。
亲测开发工具基础库 2.2.3 版本、iOS 微信 6.7.2 版本没问题，安卓 6.7.2 版本曲线不是虚线，但是坐标轴是虚线。我再给小程序团队反馈一下。
