### ISSUE TITLE
echart官网只提供了和微信小程序最基础的集成方式？？？动态setData不行？？？

### ISSUE THREAD

**Issue by momolela** [ecomfe/echarts-for-weixin#303]
`function initChart(canvas, width, height) {
  const chart = echarts.init(canvas, null, {
    width: width,
    height: height
  });
  canvas.setChart(chart);

  var option = {
    ...
  };
  chart.setOption(option);
  return chart;
}

Page({
  data: {
    ec: {
      onInit: initChart
    }
  }
});`

官网只提供了这种方式，如果我需要动态通过this.setData()方法，来更新chart数据。

’this.setData({
  ec: {
    onInit: initChart
  }
});‘

这样好像行不通

**Comment by dearxd** [comment]
这个问题解决了没有呢?

**Comment by momolela** [comment]
用echart的延迟加载去实现就可以。
具体可以下载echarts-for-weixin，然后看pages/lazyLoad里面的demo即可

**Comment by TeemoPeng** [comment]
官方的例子里，好像只能主动点击按钮触发加载，不能自动触发

**Comment by TeemoPeng** [comment]
> 官方的例子里，好像只能主动点击按钮触发加载，不能自动触发

是我搞错了
