### ISSUE TITLE
在view设置固定高度overflow：auto，图表固定不会滑动。求解？

### ISSUE THREAD

**Issue by easytnt-wx** [ecomfe/echarts-for-weixin#305]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
view设置固定高之后，设置 overflow：auto, 图表不会随着滚动，而是定在哪里不动了，是什么原因？

### 预期效果：
![image](https://user-images.githubusercontent.com/26054309/44771331-44f62f80-ab9d-11e8-9df0-1e2980b98d45.png)
![image](https://user-images.githubusercontent.com/26054309/44771355-563f3c00-ab9d-11e8-87ec-c96e48557eac.png)

（如有需要请提供预期的图）

### 实际效果：
![image](https://user-images.githubusercontent.com/26054309/44771477-a3bba900-ab9d-11e8-8d8a-e9a03b77bdc5.png)

（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by momolela** [comment]
这个问题，有解决方案吗？还是就是不能用overflow：auto？

**Comment by gyfeng1003** [comment]
> 这个问题，有解决方案吗？还是就是不能用overflow：auto？

我也遇到了这个问题，请问咋解决的

**Comment by richard1015** [comment]
我也遇到这个问题了，请问如何解决

**Comment by gyfeng1003** [comment]
> 这个问题，有解决方案吗？还是就是不能用overflow：auto？

在包裹canvas的的所有父级元素 上有用到position:fixed,position:absoluted的都去掉

**Comment by gyfeng1003** [comment]
> > 这个问题，有解决方案吗？还是就是不能用overflow：auto？
> 
> 在包裹canvas的的所有父级元素 上有用到position:fixed,position:absoluted的都去掉

去掉position的定位

**Comment by richard1015** [comment]
> > > 这个问题，有解决方案吗？还是就是不能用overflow：auto？
> > 
> > 
> > 在包裹canvas的的所有父级元素 上有用到position:fixed,position:absoluted的都去掉
> 
> 去掉position的定位

我用的 display flex   没有用到 position 定位，但是也不可以 :(

**Comment by gyfeng1003** [comment]
> > > > 这个问题，有解决方案吗？还是就是不能用overflow：auto？
> > > 
> > > 
> > > 在包裹canvas的的所有父级元素 上有用到position:fixed,position:absoluted的都去掉
> > 
> > 
> > 去掉position的定位
> 
> 我用的 display flex 没有用到 position 定位，但是也不可以 :(

整个页面都没有用到position定位吗，如果没有的话，你把display flex换一下试试，display这个我页面没用到，不太清楚

**Comment by richard1015** [comment]
> > > > > 这个问题，有解决方案吗？还是就是不能用overflow：auto？
> > > > 
> > > > 
> > > > 在包裹canvas的的所有父级元素 上有用到position:fixed,position:absoluted的都去掉
> > > 
> > > 
> > > 去掉position的定位
> > 
> > 
> > 我用的 display flex 没有用到 position 定位，但是也不可以 :(
> 
> 整个页面都没有用到position定位吗，如果没有的话，你把display flex换一下试试，display这个我页面没用到，不太清楚

好的，谢谢， 其实我还想到了一个解决办法 ，就是将 canvas 保存成url  然后我用图片来进行展示，这样的话

**Comment by richard1015** [comment]
微信小程序 原生组件的使用限制
https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html
