### ISSUE TITLE
引入echarts.js文件太大，怎么解决

### ISSUE THREAD

**Issue by heshuo13** [ecomfe/echarts-for-weixin#309]
引入了echart组件，但是在打包的时候，超过了2M

**Comment by lcs1998** [comment]
我也遇到了这个问题，难道开发者是想让我们把不用的东西删掉吗

**Comment by loveWct** [comment]
我也是遇到这个问题,目前官方版本的echart.js还不支持tooltip,只能用git上的,但是又不能缩减体积,真是令人窒息啊

**Comment by CloudXiNoob** [comment]
可以根据需要进行定制！会相对的减小文件的体积。http://echarts.baidu.com/builder.html

**Comment by lcs1998** [comment]
问题解决了，可以使用JS文件压缩，百度一下就可以

**Comment by Ovilia** [comment]
可以使用 ECharts 官网的压缩文件替换

**Comment by GSBL** [comment]
压缩之后也有500k啊
