### ISSUE TITLE
微信小程序 无法正常显示 三个以上的拐点

### ISSUE THREAD

**Issue by smc1989** [ecomfe/echarts-for-weixin#31]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：

微信小程序 无法正常显示 三个以上的拐点问题已同步提交到Echart官方 见以下链接
http://gallery.echartsjs.com/editor.html?c=xHJHnfqc_G&comment=0
截图是相同的option在小程序下的显示 见

### 预期效果：

在小程序内，正常显示所有拐点
![](http://p1m3u21ur.bkt.clouddn.com/Snipaste_2018-03-05_17-55-04.png)

### 实际效果：

![](http://echarts.baidu.com/ecg-storage/img/xHJHnfqc_G.png?v=1520243373188)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
开发工具上没复现出来，你的开发工具基础库版本是？

**Comment by smc1989** [comment]
调试基础库是1.9.91，微信开发工具是win版最新版本。我不光是在编辑上有这个问题，ios真机上也是有这个问题

**Comment by Ovilia** [comment]
我这边还是没法复现，使用本项目最新版的代码了吗？

**Comment by smc1989** [comment]
您能使用我的echarts配置放在小程序编辑器里面试一下 然后截个图出来看一下吗，因为我找朋友使用mac和win的编辑器用最新的echart for wx和最新的小程序编辑器都试过了 有同样的问题。
我的最新配置如下：

```javascript
  var option = {
    color: ["#57B078"],
    backgroundColor: "#fff",
    animation: false,
    grid: {
      left: '6%',
      right: '6%',
      bottom: '6%',
      top: '4%',
      containLabel: true
    },
    xAxis: [{
      show: true,
      type: 'category',
      data: ['12:00', '14:00', '16:00', '18:00', '20:00', '22:00', '24:00', '12:00', '14:00', '16:00', '18:00', '20:00', '22:00', '24:00'],
      axisTick: {
        show: false
      },
      axisLine: {
        show: false
      },
      splitLine: {
        show: false
      },
    }],
    yAxis: [{
      type: 'value',
      show: true,
      axisLine: {
        show: false
      },
      splitLine: {
        show: false
      },
    }],
    dataZoom: [{
      type: 'inside',
      filterMode: 'filter',
      startValue: 0,
      endValue: 6,
    }],
    series: [{
      type: 'bar',
      barWidth: '30%',
      hoverAnimation: false,
      data: [10, 52, 200, 334, 390, 330, 220, 10, 52, 200, 334, 390, 330, 220],
      label: {
        show: true,
        position: 'top',
        color: '#000'
      },
    }]
  };
```

**Comment by Ovilia** [comment]
@smc1989 
<img width="283" alt="2018-03-09 12 53 02" src="https://user-images.githubusercontent.com/779050/37191173-042f1c32-2399-11e8-9e31-2fe86b30b657.png">


这个效果是你预期的吗？

我的微信开发者工具版本 1.02.1802270 Mac 版，基础库 1.9.91

**Comment by smc1989** [comment]
咱们的基础库和编辑器的版本是一样的，
您上图的效果是在不添加左右滑动时的效果，我也是可以有同样的效果。
但是问题是：
我的设置里面里面，有这样一段设置：
```JavaScript
   dataZoom: [{
      type: 'inside',
      filterMode: 'filter',
      startValue: 0,
      endValue: 6,
    }],
```

这个是这设置可以左右滑动效果的，加上这个之后，会发生我所说的那些问题，下面是我有问题的效果图：
![](http://p1m3u21ur.bkt.clouddn.com/2461520576872_.pic_hd.jpg)

**Comment by smc1989** [comment]
好像是我这边设置的问题，需要把 filterMode: 'filter'设置成‘none’后就可以正常显示了

**Comment by Ovilia** [comment]
@smc1989 那都没问题了？

**Comment by smc1989** [comment]
对 除了这个echart组件不能在scroll-view里面使用的问题以外，其他的我这边使用过程中的问题暂时是解决了，关于这个scroll-view这个问题之后会修复吗？

**Comment by Ovilia** [comment]
scroll-view 又是什么问题？

**Comment by gongsan9527** [comment]
同样的问题

**Comment by Ovilia** [comment]
@gongsan9527 你是什么问题？他已经说解决了，你可以用同样的方法解决吗？

**Comment by gongsan9527** [comment]
同样的问题 三个以上的数据不显示 用上面的方法解决不了~~~

**Comment by Ovilia** [comment]
@gongsan9527 官网例子一点没改？怎么复现？

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
