### ISSUE TITLE
在微信小程序上怎么使用echarts-wordcloud

### ISSUE THREAD

**Issue by chenfpp** [ecomfe/echarts-for-weixin#312]
### 问题：
echarts2的官方API里是带有字符云的,但到了echarts3就被从官网上移除了
现在echarts-for-weixin中也没有词云，使用echarts-wordcloud.min.js库，报了如下错误：
![image](https://user-images.githubusercontent.com/30286640/45015978-ed047080-b055-11e8-9d0c-9fcaf2ff2ca6.png)
### 预期效果：
![image](https://user-images.githubusercontent.com/30286640/45017782-196ebb80-b05b-11e8-96ca-dfc15339b5b2.png)
### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by p2ng** [comment]
@chenfpp 
echarts暂时还不能友好支持
https://github.com/ecomfe/echarts-for-weixin/issues/17
