### ISSUE TITLE
支持color为线性渐变和径向渐变吗？

### ISSUE THREAD

**Issue by flitrue** [ecomfe/echarts-for-weixin#32]
color: new echarts.graphic.RadialGradient(0.5, 0.5, 1, [
         {
              color: 'rgba(2,215,167,0.5)',
              offset: 0
         }, {
              color: 'rgba(2,215,167,1)',
              offset: 1
         }
 ])

# or   
![image](https://user-images.githubusercontent.com/15258895/36972236-5ce5abea-20a9-11e8-8d37-b248c7026e31.png)

**Comment by Ovilia** [comment]
支持，有什么问题吗？

**Comment by flitrue** [comment]
没使用成功，一直报错，内存泄漏了，最后没用渐变。

**Comment by Ovilia** [comment]
@flitrue 无法复现，可以提供代码吗？

**Comment by flitrue** [comment]
可能是我写错了，现在没问题了，谢谢

**Comment by yjp1105286534** [comment]
> 没使用成功，一直报错，内存泄漏了，最后没用渐变。

我这里也是 你那里好了吗
