### ISSUE TITLE
有时候 setOption方法为找不到为undefind是怎么回事呢

### ISSUE THREAD

**Issue by wJiaLiang** [ecomfe/echarts-for-weixin#332]

**Comment by yancanchen** [comment]
你好，这个问题有解决吗？如何解决的呢

**Comment by phoenixor** [comment]
我也遇到，之前都是好的，昨天更新最新版本支持canvas 2d，异步加载数据之后更新图表，报错
![image](https://user-images.githubusercontent.com/6568115/76156248-9e480300-6132-11ea-82cb-419f3e1cc76f.png)

**Comment by ring0li** [comment]
我也遇到了。。。
