### ISSUE TITLE
微信小程序里多次渲染图表series数据缓存问题

### ISSUE THREAD

**Issue by fangyu2017** [ecomfe/echarts-for-weixin#333]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
series缓存问题,第一次渲染正常,第二次动态请求数据渲染之后,两次数据进行了合并,设置了setOption({},ture)数据还是进行合并

### 预期效果：
？？？
（如有需要请提供预期的图）
![image](https://user-images.githubusercontent.com/26027008/45660663-7cb51f00-bb2c-11e8-979b-b29211fa4a42.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/26027008/45660687-9d7d7480-bb2c-11e8-8198-cbbeb2d1d35c.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by lizesheng0313** [comment]
最后怎么解决的呢

**Comment by fangyu2017** [comment]
自己的粗心,操作数据的时候直接push的,所以每次都会增加,我不知道你的具体什么原因,如果你每次查的时候数据没问题的话 可以在渲染完成之后试下 chart.setOption(option, {
      notMerge: true
});

 
------------------ Original ------------------
