### ISSUE TITLE
雷达图 series[i]-radar.data[i].itemStyle.color 使用回调函数没有效果

### ISSUE THREAD

**Issue by bigggge** [ecomfe/echarts-for-weixin#335]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：

series[i]-radar.itemStyle.color 使用回调函数没有效果， symbol 颜色没有改变

```
    value: [10, 10, 10, 10, 10],
    symbol: 'circle',
    symbolSize: 8,
    itemStyle: {
      color: 'pink', // 有效
      color: function(params) {
        return colorMap[params.dataIndex] || 'pink';
      }  // 无效
    },
    lineStyle: { width: 0 },
```

### 预期效果：

可以更改 radar 图 symbol 颜色

### 实际效果：

无法更改 radar 图 symbol 颜色

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
ECharts 本身效果正确么？请提供完整的配置项

**Comment by bigggge** [comment]
文档看错了， 是 series[i]-radar.data[i].itemStyle.color 不支持 color 回调

**Comment by bigggge** [comment]
需求是一组数据的各个点都可以设置不同的颜色
