### ISSUE TITLE
tooltip在边界会超出，导致一部分内容不可见

### ISSUE THREAD

**Issue by lizesheng0313** [ecomfe/echarts-for-weixin#336]
tooltip在边界会超出，
![image](https://user-images.githubusercontent.com/23352222/46003273-b49b0400-c0e2-11e8-82e2-f289f33421e5.png)

在PC端 tooltip这种情况会自动跑到左边  在扇形图也会有这样的问题

**Comment by lizesheng0313** [comment]
大家有没有遇到过这个问题呢

**Comment by zhangruinian** [comment]
> 大家有没有遇到过这个问题呢

你用的哪个版本的呀,自己构建的么

**Comment by lizesheng0313** [comment]
@zhangruinian   我是在官网用这个弄的  http://echarts.baidu.com/builder.html

**Comment by imruxin** [comment]
你需要这个配置一下 http://echarts.baidu.com/option.html#tooltip.position

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#tooltip.confine 这个配置项设为 true，后面我改进一下默认用 true

**Comment by lizesheng0313** [comment]
设置confine为true 又跑到右上角了
