### ISSUE TITLE
echarts配置项axisLabel下的富文本项的align属性无效

### ISSUE THREAD

**Issue by NicInvade** [ecomfe/echarts-for-weixin#337]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
echarts配置项axisLabel下的富文本项的align属性无效，配置代码如下：
![image](https://user-images.githubusercontent.com/31463062/46119943-12912e00-c240-11e8-8887-a8d530dd5f39.png)

### 预期效果：
预期x坐标上的红色日期是左对齐坐标轴，黄色日期是剧中，蓝色日期是居右。

### 实际效果：
实际这些日期都是居中的。
![image](https://user-images.githubusercontent.com/31463062/46120036-816e8700-c240-11e8-83b0-6a0213c7565c.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
这个 ECharts 本身的效果是怎么样的，就是在网页中，而不是小程序中

**Comment by Ovilia** [comment]
网页上都无效那就是 ECharts 的问题了，到 ECharts 提问吧
