### ISSUE TITLE
从官网自定义构建文件无法在小程序中使用

### ISSUE THREAD

**Issue by huangyangme** [ecomfe/echarts-for-weixin#34]
- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 从官网自定义构建以减小文件大小失败

默认下载项目中的“echarts.js”文件过大。
使用精简版本“echarts.simple.min.js”，或者自定义构建版本，则无法在小程序中使用。
请问，如何减小 echarts.js 文件大小？

### 实际效果：

![11](https://user-images.githubusercontent.com/4213398/37019685-311695fa-2154-11e8-8712-a61a5d6b2aed.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
我试了一下默认的打包项没问题，可以提供一下你选择了哪些打包项吗？

**Comment by BernersH** [comment]
遇到一样的问题  请问打包项是指？

**Comment by Ovilia** [comment]
就是勾选了哪些组件？

**Comment by jackyon** [comment]
我也是一样的问题，后来实验后，发现只要不勾选“代码压缩”这一项，就能正常运行了

**Comment by Ovilia** [comment]
@jackyon 赞，我排查一下问题

**Comment by Ovilia** [comment]
@jackyon 我试了一下默认的选项，不压缩，还是没法复现

**Comment by Ovilia** [comment]
可否把有问题的 js 文件附在评论中？ @jackyon @BernersH

**Comment by jackyon** [comment]
[echarts.txt](https://github.com/ecomfe/echarts-for-weixin/files/1793658/echarts.txt)

**Comment by jackyon** [comment]
好像是 UglifyJS 压缩有问题了，我试过UglifyJS online压缩的，也是不行，后来换成： https://www.minifier.org/ 压缩，就正常了

**Comment by Ovilia** [comment]
我用你给的也是正常的。。@jackyon 你用这个项目里提供的 echarts.js 是正常的？好奇怪啊……

**Comment by huangyangme** [comment]
@Ovilia 

精简版：
http://echarts.baidu.com/dist/echarts.simple.min.js

在线构建版：
http://echarts.baidu.com/builder/echarts.html?charts=line&components=gridSimple&api=true&version=4&versionCode=4.0.4

都有问题。

**Comment by HuaZaiWuDi** [comment]
如何解决？git上面的echarts.js文件过大，在官网构建的min版本，但是报错找不到echarts.js需要改哪里嘛？

**Comment by Ovilia** [comment]
@huangyangme 
找到问题了，你给的例子里，`ec-canvas/ec-canvas.js` 里 `import * as echarts from './echarts';`，但是 `pages/line/index.js` 里 `import * as echarts from '../../ec-canvas/echarts.simple.min';`。这是不应该的，两处应该都用同样的 echarts 文件。鉴于每个 pages 里都有 echarts 的引用，所以建议下载的文件重命名为 `echarts.js` 放在 `ec-canvas` 下即可。
其他人是不是一样的原因呢？如果还有问题请继续评论。

**Comment by huihaitao** [comment]
请问这个代码包过大的问题你是怎么解决的呢         自定义构建的js文件老是报错

**Comment by BoleLee** [comment]
使用官网默认构建，将压缩勾选去掉，使用wepy编译遇到报错：
```
[Error] Error: 找不到模块: zrender/container/Group
被依赖于: /Users/grace/TestProjects/wepy-project/src/vendor/echarts.custom.js。
请尝试手动执行 npm install zrender/container/Group 进行安装。
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:124:27
    at String.replace (<anonymous>)
    at Object.resolveDeps (/usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:46:21)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:270:27
    at <anonymous>
```

@Ovilia 请问可能是什么原因，要怎么解决？

**Comment by foooooouny** [comment]
将文件内 @example 处相关的注释去掉，或者直接使用压缩版的 echarts.js
wepy编译报错应该就是把 @example 处的注释编译了

```js
* @example
 *     var Group = require('zrender/container/Group');
 *     var Circle = require('zrender/graphic/shape/Circle');
 *     var g = new Group();
 *     g.position[0] = 100;
 *     g.position[1] = 100;
 *     g.add(new Circle({
 *         style: {
 *             x: 100,
 *             y: 100,
 *             r: 20,
 *         }
 *     }));
 *     zr.add(g);
```

**Comment by foooooouny** [comment]
> 将文件内 @example 处相关的注释去掉，或者直接使用压缩版的 echarts.js
> wepy编译报错应该就是把 @example 处的注释编译了
> 
> ```js
> * @example
>  *     var Group = require('zrender/container/Group');
>  *     var Circle = require('zrender/graphic/shape/Circle');
>  *     var g = new Group();
>  *     g.position[0] = 100;
>  *     g.position[1] = 100;
>  *     g.add(new Circle({
>  *         style: {
>  *             x: 100,
>  *             y: 100,
>  *             r: 20,
>  *         }
>  *     }));
>  *     zr.add(g);
> ```


回复问题的是：
```js
[Error] Error: 找不到模块: zrender/container/Group
被依赖于: /Users/grace/TestProjects/wepy-project/src/vendor/echarts.custom.js。
请尝试手动执行 npm install zrender/container/Group 进行安装。
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:124:27
    at String.replace (<anonymous>)
    at Object.resolveDeps (/usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:46:21)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:270:27
    at <anonymous>
```

**Comment by jialeigd** [comment]
> > 将文件内 @example 处相关的注释去掉，或者直接使用压缩版的 echarts.js
> > wepy编译报错应该就是把 @example 处的注释编译了
> > ```js
> > * @example
> >  *     var Group = require('zrender/container/Group');
> >  *     var Circle = require('zrender/graphic/shape/Circle');
> >  *     var g = new Group();
> >  *     g.position[0] = 100;
> >  *     g.position[1] = 100;
> >  *     g.add(new Circle({
> >  *         style: {
> >  *             x: 100,
> >  *             y: 100,
> >  *             r: 20,
> >  *         }
> >  *     }));
> >  *     zr.add(g);
> > ```
> 
> 回复问题的是：
> 
> ```js
> [Error] Error: 找不到模块: zrender/container/Group
> 被依赖于: /Users/grace/TestProjects/wepy-project/src/vendor/echarts.custom.js。
> 请尝试手动执行 npm install zrender/container/Group 进行安装。
>     at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:124:27
>     at String.replace (<anonymous>)
>     at Object.resolveDeps (/usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:46:21)
>     at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:270:27
>     at <anonymous>
> ```

我去 还真是这样
