### ISSUE TITLE
微信小程序移植，不显示bar图

### ISSUE THREAD

**Issue by xcmg** [ecomfe/echarts-for-weixin#341]
### 简单描述问题：
操作顺序
1.拷贝ec-canvas文件夹，至工程目录下
2.按照bar界面，新建界面
3.进入界面后，无错误，显示gl打印信息，图表不加载

### 预期效果：
console.log(chart) 获得已下结果，但是不显示图表
gl {_dom: WxCanvas, _zr: og, _theme: null, _chartsViews: Array(3), _throttledZrFlush: ƒ, …}

### 复现环境：
在微信开发工具中存在该问题
 在真机上存在该问题

**Comment by Ovilia** [comment]
容器是否有宽度高度？

**Comment by ReyCG** [comment]
请问宽度和高度在哪里设置？

**Comment by p2ng** [comment]
@xcmg 
目前我也是跟您一样的效果。代码也是直接copy示例的
环境
- 开发者工具`v1.02.1809260`目前最新版本
- 调试基础库`2.3.0`

然后在wxml页面，输入{{ec}}，就能展示图表
![image](https://user-images.githubusercontent.com/7822128/46326567-f3274600-c62f-11e8-84b2-6e97b547bdb0.png)

**Comment by p2ng** [comment]
看来是我业务代码问题。
只保留echart的代码显示正常。review一下业务代码

**Comment by p2ng** [comment]
@xcmg 
可以尝试只保留canvas代码，然后与业务代码耦合在一起，我这边正常了。
```
<ec-canvas id="mychart-dom-bar" canvas-id="mychart-bar" ec="{{ec}}"></ec-canvas>
```

奇怪。本身业务代码一堆view包裹着，然后在里面再copy官方的代码，已经copy。wcss文件的宽度，长度 100%
```
<view class="container">
  <ec-canvas id="mychart-dom-bar" canvas-id="mychart-bar" ec="{{ ec }}"></ec-canvas>
</view>
```
