### ISSUE TITLE
tooltip配置extraCssText web端有效，小程序无效 加了-webkit-也没用

### ISSUE THREAD

**Issue by caizhendi** [ecomfe/echarts-for-weixin#342]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
tooltip配置extraCssText: '-webkit-transform: rotate(90deg);' web端有效，小程序无效

### 预期效果：
![image](https://user-images.githubusercontent.com/15686186/46240527-93d0f800-c3db-11e8-9f69-41fde30f34a3.png)

### 实际效果：
？？？
（如有需要请提供截图）
![image](https://user-images.githubusercontent.com/15686186/46240530-9cc1c980-c3db-11e8-8a87-0846c4c7c764.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
extraCssText 会在 tooltip DOM 节点上增加 CSS，但是微信小程序不支持 DOM，这样设 CSS 肯定是没有效果的。可以通过 `formatter` 修改内容，其他颜色等样式参考 http://echarts.baidu.com/option.html#tooltip 配置。

**Comment by caizhendi** [comment]
> extraCssText 会在 tooltip DOM 节点上增加 CSS，但是微信小程序不支持 DOM，这样设 CSS 肯定是没有效果的。可以通过 `formatter` 修改内容，其他颜色等样式参考 http://echarts.baidu.com/option.html#tooltip 配置。

我需求是提示框内容横向显示，发现其他都有rotate可以设置 但是tooltip却没有
大佬能给个提示 如何实现吗？

**Comment by Ovilia** [comment]
整体选择 90 度么，好像没法实现，使用场景是？

**Comment by caizhendi** [comment]
> 整体旋转 90 度么，好像没法实现，使用场景是？

竖向的折线图 带双y轴  目前boss是想说图能不能转换成横向 只要图转换成 其他不用 还是竖向方向
尝试css3 rotateY 转换过 发现图会被吃掉 
现在是x轴变成y轴 y轴变成x轴 转换过来 其他能设置的都设置了 就是这个提示框还不行 
![image](https://user-images.githubusercontent.com/15686186/46241649-bf5ddd80-c3ef-11e8-992e-b59a9c62dc12.png)

**Comment by Ovilia** [comment]
那你整体的图表不要转，只改坐标轴文字的旋转可以不？http://echarts.baidu.com/option.html#xAxis.axisLabel.rotate
话说为什么图表要这样转着，不是会看不清么？

**Comment by caizhendi** [comment]
> 那你整体的图表不要转，只改坐标轴文字的旋转可以不？http://echarts.baidu.com/option.html#xAxis.axisLabel.rotate
> 话说为什么图表要这样转着，不是会看不清么？

boss就是觉得要转 因为屏幕的宽再大也就那样 所以要转过来看 
现在初步是能转的都转了 就是tooltip转不过来
本来想说会不会有一个大体设置 直接整张图转过来 也不用去x->y y->x

**Comment by xuqingyou** [comment]
你的问题解决了吗？ 我也遇到了同样的问题

**Comment by caizhendi** [comment]
> 你的问题解决了吗？ 我也遇到了同样的问题

不知道你的问题是啥= = 我最后还是竖屏了
