### ISSUE TITLE
自定义 tooltip 模板不解析 html 标签

### ISSUE THREAD

**Issue by Han-MeiM** [ecomfe/echarts-for-weixin#344]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
使用官方构建的压缩文件，自定义 `tooltip` 时不解析 `HTML标签`

### 实际效果：
![image](https://user-images.githubusercontent.com/27951114/46463703-151ef500-c7f7-11e8-8d45-7b8bc9a6696f.png)
![image](https://user-images.githubusercontent.com/27951114/46463724-1fd98a00-c7f7-11e8-919a-90de62a8a6b9.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
用 `\n` 换行

**Comment by Han-MeiM** [comment]
@Ovilia 
目前是用的 `\n` 来换行的
但是不解析样式的话会比较丑

**Comment by Ovilia** [comment]
本质上是用 ECharts 的富文本实现的 tooltip，所以没法支持 html 的解析
