### ISSUE TITLE
小程序上如何使用dispatchAction？

### ISSUE THREAD

**Issue by lifeng1893** [ecomfe/echarts-for-weixin#345]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
小程序echarts可以使用dispatchAction吗？

### 预期效果：
echarts初始化后需要指定最后一条数据tooltip显示出来
（如有需要请提供预期的图）

### 实际效果：
无
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
和 ECharts 一样有什么问题？

**Comment by lifeng1893** [comment]
@Ovilia 
![1539150952386](https://user-images.githubusercontent.com/16682146/46715836-3ae34880-cc94-11e8-9cf6-64bd69fa5296.jpg)

我是这样写的，好像没效果

**Comment by lifeng1893** [comment]
在onReady获取chart实例后再dispatchAction也没效果

**Comment by circlewang** [comment]
你好，能问下您怎么写的吗

**Comment by lifeng1893** [comment]
> 你好，能问下您怎么写的吗
@circlewang  在onReady里
```
setTimeout(() => {
  chart.dispatchAction({
    type: 'showTip',
    seriesIndex: 0,
    dataIndex: showIndex,
  })
}, 1000)
```
