### ISSUE TITLE
tooltip 手指抬起后不消失

### ISSUE THREAD

**Issue by Huan90s** [ecomfe/echarts-for-weixin#346]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
**_手指抬起后tooltip不消失。_**

### 预期效果：
手指down点echart显示tooltip，手指up后，echart隐藏tooltip

### 实际效果：
tooltip出现后，就不会自动消失

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by fengcen** [comment]
我的也是，tooltip 不会自动隐藏

**Comment by Huan90s** [comment]
@Ovilia  能指点一二吗

**Comment by Ovilia** [comment]
这个是 feature，不是 bug。如果需要自动隐藏，尝试一下监听 touchend 事件，然后 dispatchAction http://echarts.baidu.com/api.html#action.tooltip.hideTip

**Comment by xjjrocker** [comment]
为什么我tooltip也不出现啊，而且官网不是也说微信版暂不支持吗，但是大家怎么都有tooltip呢，请问下是内嵌H5吗还是怎么个实现的？

**Comment by sworlife** [comment]
> 这个是 feature，不是 bug。如果需要自动隐藏，尝试一下监听 touchend 事件，然后 dispatchAction http://echarts.baidu.com/api.html#action.tooltip.hideTip

调用后，`tooltip.axisPointer` 还是存在
``` js
this.chart.dispatchAction({
    type: 'hideTip'
})
```
![image](https://user-images.githubusercontent.com/33422051/61521399-b9022600-aa42-11e9-8c1f-bcbc5369f683.png)

**Comment by huoyanfx** [comment]
chart.on('mouseup', function () {
		console.log("test22")
		chart.dispatchAction({
			type: 'hideTip'
		})
  });
这样写的..没效果啊..console.log("test22")触发了
