### ISSUE TITLE
tooltip confine为ture tips被固定定位在左上角

### ISSUE THREAD

**Issue by AlanZou007** [ecomfe/echarts-for-weixin#347]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
tooltip confine设置为true 被固定在左上角

### 实际效果：
![image](https://user-images.githubusercontent.com/24911981/46724238-2dd25380-ccac-11e8-88cf-a1fb8a9f9132.png)
![image](https://user-images.githubusercontent.com/24911981/46724288-417dba00-ccac-11e8-8b46-982ecfed8789.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by lizesheng0313** [comment]
是的 我也遇到  了这个问题

**Comment by Ovilia** [comment]
已修复，急用的话参考上面对 echarts.js 进行修改

**Comment by Ovilia** [comment]
直接改编译后（但没压缩过）的 echarts.js，搜索 `getOuterSize` 之类的找到改动的地方，照着改就行。

**Comment by lxk0301** [comment]
> 直接改编译后（但没压缩过）的 echarts.js，搜索 `getOuterSize` 之类的找到改动的地方，照着改就行。

@Ovilia 你好  我改了,  不压缩的用着没问题, 但是我自己 改完后,再压缩一下,就报错了,用的是UglifyJS 压缩

**Comment by AlanZou007** [comment]
小程序开发者工具有自带压缩功能。最好定制echarts，只用你需要的功能。

**Comment by lxk0301** [comment]
> 小程序开发者工具有自带压缩功能。最好定制echarts，只用你需要的功能。

@AlanZou007 小程序开发者工具有自带压缩功能？？？？？？？我感觉没用呀
我从官网自己定制的js,没有压缩, 改好那个bug, 如果我不手动压缩,  小程序的开发工具,点击预览就报错.
请看截图
![tim 20181018113637](https://user-images.githubusercontent.com/21308593/47129995-2d4c4500-d2ca-11e8-9ab2-79fe6de032fd.png)

**Comment by AlanZou007** [comment]
@lxk0301 开发者工具默认超过500K，就不压缩了。

**Comment by lxk0301** [comment]
> @lxk0301 开发者工具默认超过500K，就不压缩了。

@AlanZou007 是的呢 ,  但是从官网自定义的,(不压缩)大小也有1.3M多,
因为只有先不压缩,然后添加那个修复的bug代码,才能正常使用,
如果定制的时候勾选了压缩,再去压缩文件里面搜索添加修复bug代码,  就直接报错
我不知道官网自定义版本使用的UglifyJS 压缩是什么标准规范

**Comment by AlanZou007** [comment]
UglifyJS 我试了一下，好像不支持es6 你把const改成var

**Comment by lxk0301** [comment]
> UglifyJS 我试了一下，好像不支持es6 你把const改成var

我已经弄好了, 先去官网自定义下载一份未压缩的代码,  然后去里面搜索添加修复bug的代码,其中 const size 改成 var size;
然后去这个网站压缩一下https://www.css-js.com/
压缩后的文件不会报错, 而且容量也很小了,

**Comment by Crazysanlang** [comment]
issues 264、347、452 都看了， 依然没有看明白怎么处理tooltips 无法自适应的问题，还望明确解答，预期效果是 当tooltip 超过容器时，可以自适应到左边显示。
