### ISSUE TITLE
异步加载数据，显示图表后无法进行交互。

### ISSUE THREAD

**Issue by NgiLu** [ecomfe/echarts-for-weixin#35]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
参考demo的延迟加载，图表在展现后，无法进行交互。

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by yydounai1234** [comment]
lazyload示例里面没有加return chart
