### ISSUE TITLE
如何阻止饼图点击

### ISSUE THREAD

**Issue by churjan** [ecomfe/echarts-for-weixin#350]
![image](https://user-images.githubusercontent.com/15041918/46805487-c09bec80-cd97-11e8-9f91-12f20b9ff6b1.png)

如图，现在如果我在饼图上滑动页面，无法滑动，我感觉应该是饼图上面的点击事件组件了，但是我在文档里面搜不到哪里可以禁止饼图点击

**Comment by lxk0301** [comment]
一看你就没看官方的demo,你请情况 ,demo里面有,  "页面不阻塞滚动"
把js里面的data里面的ecBar :{disableTouch: true},添加上面的属性就行了
![snipaste_2018-10-15_11-52-24](https://user-images.githubusercontent.com/21308593/46929256-2a0a4c80-d071-11e8-809b-7c949e2e7379.png)

**Comment by lxk0301** [comment]
还有,  如果你真认为是 饼图的  点击事件阻止了,  我告诉你 如何禁止 拼图点击.,  在 legend: {
              selectedMode: false,

            },添加 selectedMode: false,
