### ISSUE TITLE
生成的echarts在scroll-view下滚动时，echarts生成的图表是不会滚动的始终定位在原位置， 

### ISSUE THREAD

**Issue by dearxd** [ecomfe/echarts-for-weixin#351]

**Comment by gyjddtang** [comment]
我也遇到这个问题，echarts图表在scroll-view滚动时，不会随着scroll-view滚动，而是保持在原地

**Comment by dearxd** [comment]
> 我也遇到这个问题，echarts图表在scroll-view里，图表不会随着scroll-view滚动，而是保持在原地

这个bug官方这边没有给维护。。。难道要让自己改源码么。。。

**Comment by SuperBinlin** [comment]
我把scroll-view设置的height去除 解决了这个问题

**Comment by dearxd** [comment]
> 我把scroll-view设置的height去除 解决了这个问题

你去掉了高度，是页面滚动了不是指定scroll-view区域滚动。。。

**Comment by SuperBinlin** [comment]
> > 我把scroll-view设置的height去除 解决了这个问题
> 
> 你去掉了高度，是页面滚动了不是指定scroll-view区域滚动。。。

喔 只是给你提供一个思路 因为目前来看 无解 [小程序文档](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)有说明原生组件的使用限制 只能等小程序把这些限制先解决了

**Comment by dearxd** [comment]
嗯。。。

**Comment by dearxd** [comment]
> > > 我把scroll-view设置的height去除 解决了这个问题
> > 
> > 
> > 你去掉了高度，是页面滚动了不是指定scroll-view区域滚动。。。
> 
> 喔 只是给你提供一个思路 因为目前来看 无解 [小程序文档](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)有说明原生组件的使用限制 只能等小程序把这些限制先解决了

嗯
