### ISSUE TITLE
新版本地图颠倒，换了旧版本没有tooltips

### ISSUE THREAD

**Issue by rxyshww** [ecomfe/echarts-for-weixin#352]
新版本地图颠倒，换了旧版本没有tooltips
大佬们什么时候能修复下。。。太要命了

**Comment by rxyshww** [comment]
![image](https://user-images.githubusercontent.com/21061835/46865713-1385aa80-ce51-11e8-8fcb-f16a961aac32.png)

**Comment by Ovilia** [comment]
项目里 map 那个例子，河南的地图，新版本 ECharts 没有颠倒，对比一下？

**Comment by muxinlove** [comment]
1.0.3 的地图是颠倒的，河南地图和显示是相反的，特意查过，这个可以修复一下吗

**Comment by Ovilia** [comment]
我把 ECharts 更新到最新的版本就没有这个问题了，可以 pull 一下。
