### ISSUE TITLE
ec-canvas文件里面的echarts.js文件过大,导致小程序提示包大于3M,不能上传预览

### ISSUE THREAD

**Issue by lxk0301** [ecomfe/echarts-for-weixin#353]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息
小程序提示包大于3M,不能上传预览
将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？
ec-canvas文件里面的echarts.js文件过大,导致小程序提示包大于3M,不能上传预览等等,我自己压缩的报错,请问能否提供一个压缩版本?
### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by lxk0301** [comment]
![tim 20181013180433](https://user-images.githubusercontent.com/21308593/46904151-78550980-cf12-11e8-9cc7-f0d30ba7c29b.png)

**Comment by lantongzi** [comment]
你需要定制一下这个插件的大小 使用定制可以有效的减少插件的体积

**Comment by lxk0301** [comment]
@lantongzi 这我知道,关键是目前定制只能去echatrs官网定制, 但是官网目前的定制版本, 不支持tooltip功能,只能使用这个项目里面的echats.js文件才支持

**Comment by hqzxjczx** [comment]
> @lantongzi 这我知道,关键是目前定制只能去echatrs官网定制, 但是官网目前的定制版本, 不支持tooltip功能,只能使用这个项目里面的echats.js文件才支持

亲测，官网定制的也支持tooltip功能。

**Comment by lxk0301** [comment]
@hqzxjczx 可以 他那个redeme里面 好像说官网的不行,不过我去试试吧
![snipaste_2018-10-15_16-07-32](https://user-images.githubusercontent.com/21308593/46937698-8cc10f80-d094-11e8-9afe-78c5ae5c768c.png)

**Comment by lantongzi** [comment]
去官网定制一份最新的 
![image](https://user-images.githubusercontent.com/22415412/46990599-a31ea800-d134-11e8-8aa4-d1af620a13b1.png)
svg 绘图选上 
![image](https://user-images.githubusercontent.com/22415412/46990621-c77a8480-d134-11e8-94b5-bdb45739d62d.png)
tooptip选上

**Comment by lantongzi** [comment]
![image](https://user-images.githubusercontent.com/22415412/46990650-f42e9c00-d134-11e8-8ed3-1ae29859b58c.png)
你需要的是这个对吗？

**Comment by lxk0301** [comment]
> ![image](https://user-images.githubusercontent.com/22415412/46990650-f42e9c00-d134-11e8-8ed3-1ae29859b58c.png)
> 你需要的是这个对吗？

@lantongzi 对 ,  是这个,  去官网定制的,那个svg渲染,  必须要勾选上面吗????

**Comment by lantongzi** [comment]
你就按着这个去定制吧 尽量只定制自己需要的 不要定制太多的功能

**Comment by lantongzi** [comment]
@lxk0301  svg  我是选上的 估计toopltip 是svg 绘制的吧 具体的没去了解

**Comment by lxk0301** [comment]
@lantongzi 好的好的.   你这是什么编译器?  看着好像不是小程序官网那个编译器吧

**Comment by Ovilia** [comment]
tooltip 是 canvas 绘制的，小程序不支持 svg。
下载 https://github.com/apache/incubator-echarts/blob/master/dist/echarts.min.js 这个，重命名为 echarts.js 替换就行。
