### ISSUE TITLE
关于更新option数据时 画布上还有缓存数据的处理

### ISSUE THREAD

**Issue by lantongzi** [ecomfe/echarts-for-weixin#354]
![image](https://user-images.githubusercontent.com/22415412/46905066-a5101d80-cf20-11e8-81c2-db4cf00058e3.png)

![image](https://user-images.githubusercontent.com/22415412/46905100-45664200-cf21-11e8-862c-2733a06d2add.png)

**Comment by lantongzi** [comment]
自己回答一下吧  其实是在setOption(option, true)  这样就能将之前的数据清理掉
```
setTimeout(function (){
            // 遇到更新数据时 画布上还有之前残余的数据时 setOption 中添加一个true
            // https://blog.csdn.net/qq_36135258/article/details/81671930
            chart.setOption(optionCopy, true);  //赋值后再设置一次option
        },200);
```

**Comment by lizesheng0313** [comment]
我设置了不行  还会显示
