### ISSUE TITLE
小程序多次动态设置数据后  会出现闪频，会显示上一次的结果 

### ISSUE THREAD

**Issue by lizesheng0313** [ecomfe/echarts-for-weixin#357]
小程序动态加载图表，会把上一次的图表也加载出来，在切换的时候怎么让他变空白呢，在PC端可以用showLoading来实现 小程序端不知道怎么写 求助

![image](https://user-images.githubusercontent.com/23352222/46943008-38705c80-d0a1-11e8-861c-6b10451ed456.png)
来回切换后， 就会出现闪频

**Comment by lizesheng0313** [comment]
求助

**Comment by ResearchInstituteWeb** [comment]
找到解决办法没

**Comment by shiyafei** [comment]
最后是怎么解决的？
