### ISSUE TITLE
一段改进代码 请查收

### ISSUE THREAD

**Issue by xingzhuo1983** [ecomfe/echarts-for-weixin#358]
// ec-canvas/util.js
import * as echarts from './echarts';

let getChart = function (option) {
  return {
    onInit: function (canvas, width, height) {
      const chart = echarts.init(canvas, null, {
        width: width,
        height: height
      });
      canvas.setChart(chart);
      chart.setOption(option);
      return chart;
    }
  }
}

module.exports = {
  getChart
}

// pages/xxxxxx/xxxxxx

import { getChart } from '../../../ec-canvas/util';
Page({
    .....
  onLoad: function () {
    // TODO:   generate options by data
    let option = { ... };
    this.setData({
      ec: getChart(option),
    });
  },

})

**Comment by Ovilia** [comment]
这是为了解决什么问题？请用 PR 的方式提交，谢谢

**Comment by xingzhuo1983** [comment]
> 这是为了解决什么问题？请用 PR 的方式提交，谢谢

PR的话会把你们所有的演示页面代码改掉  包括文档 
对于开发者而言 在Page外声明option是不合理的  绝大多数场景下
使用者都是在页面的某个生命周期读取数据  然后注入数据生成option 
然后再将option注入echarts生成图表.

以上代码是对整个暴露的接口做了一个大的优化,  望采纳
