### ISSUE TITLE
echarts官方代码报错

### ISSUE THREAD

**Issue by lizesheng0313** [ecomfe/echarts-for-weixin#360]
![image](https://user-images.githubusercontent.com/23352222/47014712-a25e3400-d17d-11e8-9608-ec5a6d584861.png)
 点击释放图表后报错

**Comment by Ovilia** [comment]
已修复，如果急用请照着 https://github.com/apache/incubator-echarts/commit/7393f826d22a91b4b94e7753660b6250572e33cc 自行修改 ECharts 文件

**Comment by lizesheng0313** [comment]
好的 谢谢姐姐
