### ISSUE TITLE
toolTip功能,在X轴最大值的时候,悬浮窗会被遮住看不到

### ISSUE THREAD

**Issue by lxk0301** [ecomfe/echarts-for-weixin#361]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：

toolTip功能,在X轴最大值的时候,悬浮窗会被遮住看不到
### 预期效果：
像PC端一样,在最右边的时候,悬浮窗自动显示在竖线的左边,
（如有需要请提供预期的图）

![tim 20181017155331](https://user-images.githubusercontent.com/21308593/47070894-d3de0a80-d224-11e8-9a61-90e3198a56bf.png)

### 实际效果：
小程序端在最右边,悬浮窗内容不会自动显示在竖线左边,还是显示在右边,导致被遮住看不到
（如有需要请提供截图）
截图一
![screenshot_2018-10-17-15-44-47-237_com tencent mm](https://user-images.githubusercontent.com/21308593/47070997-01c34f00-d225-11e8-89c7-5f157dcba71b.png)
截图二
![screenshot_2018-10-17-15-45-12-998_com tencent mm](https://user-images.githubusercontent.com/21308593/47071024-0e47a780-d225-11e8-92ab-8d2dd5447f96.png)

### 复现环境：
在微信开发工具,和真机 中都存在该问题

**Comment by lxk0301** [comment]
如果改写,添加 confine :true的话,  悬浮窗就会固定在图表左边
![snipaste_2018-10-17_15-49-16](https://user-images.githubusercontent.com/21308593/47071319-d2f9a880-d225-11e8-8589-0f762d151634.png)

**Comment by lxk0301** [comment]
> 设置tooltip里的confine为ture 然后在#347

@lizesheng0313 你好, 在#347  , 这个我看到了,  但是我没看到他说是如何修复的,能写下代码吗?

**Comment by lizesheng0313** [comment]
![image](https://user-images.githubusercontent.com/23352222/47080557-e5321180-d23a-11e8-9d1a-cd44729b2251.png)
点这个就能看到， 不过我对应改了一下 没成功

**Comment by lizesheng0313** [comment]
你成功了吗   亲爱的chart友

**Comment by lxk0301** [comment]
> 你成功了吗 亲爱的chart友

@lizesheng0313 还没试呢.  刚到 公司. 你成功了??????????

**Comment by lxk0301** [comment]
> 你成功了吗 亲爱的chart友

@lizesheng0313 还没试呢. 刚到 公司.

**Comment by lizesheng0313** [comment]
没 我对应改了 没成功呢， 你试试 应该是我改的不对

**Comment by lxk0301** [comment]
> 没 我对应改了 没成功呢， 你试试 应该是我改的不对
@lizesheng0313 
我都不知道在哪里添加代码,   是在 echarts,js里面 添加这个代码吗?
getOuterSize: function () {
        return this.getSize();
        const size = this.getSize();
        return {
            width: size[0],
            height: size[1]
        };
    }

**Comment by lizesheng0313** [comment]
恩是的

**Comment by lxk0301** [comment]
> 恩是的

@lizesheng0313 
但是我看他  这段代码是写在 
下面路径的js文件里面
src/component/tooltip/TooltipRichContent.js

**Comment by lizesheng0313** [comment]
恩 加群沟通吧 这样太费劲了  368953292

**Comment by Ovilia** [comment]
confine 的问题请在 #347 讨论

**Comment by NANAYWY** [comment]
> 恩 加群沟通吧 这样太费劲了 368953292

请问修改之后是如何压缩的

**Comment by xieyouliang** [comment]
我也遇到这问题了请问现在你们解决了吗？
