### ISSUE TITLE
折线图tooltip丢失x轴项目名称, 自定义tooltip无法添加色盘提示

### ISSUE THREAD

**Issue by zhangruinian** [ecomfe/echarts-for-weixin#363]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
折线图tooltip丢失x轴项目名称, 自定义tooltip无法添加色盘

### 预期效果：
![8f6845da-9f84-434e-92bf-f82e685e5662](https://user-images.githubusercontent.com/9652856/47129091-7dc1a380-d2c6-11e8-8138-8ecf01fbc9bb.png)

### 实际效果：
缺少x轴名字
![fb3f24d1-35a5-4da5-af87-fdddcc6122ba](https://user-images.githubusercontent.com/9652856/47129152-b8c3d700-d2c6-11e8-94c4-c5504a69206f.png)

### 复现环境：
- [x] 在微信开发工具（如有需要请提供截图）中存在该问题
- [x] 在真机上存在该问题

### 补充配置代码
不支持dom 自定义tooltip的时候无法添加前面色盘
```js
 formatter: (params) => {
        console.log(params)
        let time = ''
        let str = ''
        params.forEach((i) => {
          time = i.name + '\n'
          if (i.data === 'null' || i.data == null) {
            str += params[i].marker + i.seriesName + ' :  无数据' + '\n'
          } else {
            str += '<view style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:' + i.color + ';"></view>' + i.seriesName + ' : ' + i.data + '\n'
          }
        })
        return time + str
      }
```

**Comment by zhangruinian** [comment]
@Ovilia请看下~

**Comment by Ovilia** [comment]
用 formatter，彩色的圆点用 `'{marker0at0|}', {marker1at0|}, {marker2at0|}'` 分别表示第 0、1、2 个系列，可能实现得不是很美，但是至少暂时可以这么用着。

**Comment by zhangruinian** [comment]
> 用 formatter，彩色的圆点用 `'{marker0at0|}', {marker1at0|}, {marker2at0|}'` 分别表示第 0、1、2 个系列，可能实现得不是很美，但是至少暂时可以这么用着。
谢谢.实现了 
不过感觉这个比较常用, 可以内置/默认吧

**Comment by zhangruinian** [comment]
> 用 formatter，彩色的圆点用 `'{marker0at0|}', {marker1at0|}, {marker2at0|}'` 分别表示第 0、1、2 个系列，可能实现得不是很美，但是至少暂时可以这么用着。

不过这个感觉很常用,可以内置/默认吧
@Ovilia

**Comment by Ovilia** [comment]
这个其实应该算 ECharts 的项目了，这里先关了。
