### ISSUE TITLE
边上的tooltip会显示在屏幕外边，不会自适应到屏幕内，官方实例也存在该问题

### ISSUE THREAD

**Issue by rxyshww** [ecomfe/echarts-for-weixin#364]
![image](https://user-images.githubusercontent.com/21061835/47193885-c1c8ad00-d387-11e8-814c-53393466160c.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
#347

**Comment by johnnynode** [comment]
https://github.com/ecomfe/echarts-for-weixin/issues/452
