### ISSUE TITLE
小程序预览调试报错

### ISSUE THREAD

**Issue by caizhendi** [ecomfe/echarts-for-weixin#367]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
苹果机8测过没出现问题，努比亚z17S 真机预览出现问题 真机调试无问题 开发者工具也无问题
### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）
![image](https://user-images.githubusercontent.com/15686186/47400853-9112ba00-d771-11e8-83e1-e261f954c717.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x]在真机上存在该问题
代码：
var date = 1539964223111;
let dateArr = [];
for (var i = 0; i < 100;i++) {
  date += 2;
  dateArr.push(date)
}

option = {
    title: {
      text: '断路器机械特性曲线',
      subtext: '日期:21/9/2018,起始时间:16:4:13.382',
      x: 'center',
      align: 'right',
      textStyle: {
        fontSize: 14
      },
      top:'auto'
    },
      grid: {
        bottom: 80
      },
      tooltip: {
        trigger: 'axis',
        axisPointer: {
          type: 'cross',
          animation: false,
          label: {
            backgroundColor: '#505765'
          }
        },
        position: ['40%', '40%']
      },
      legend: {
        data: ['合闸线圈电流', '分闸线圈电流', '触头行程'],
        x: 'center',
        textStyle: {
          fontSize: 10
        },
        bottom: '5%'
      },
      xAxis: [
        {
          boundaryGap: false,
          axisLine: { onZero: false },
          data: dateArr,
          axisLabel:{
            formatter(value,index){
              let date = new Date(value - 0);
              var h = date.getUTCHours() + ':';
              var m = date.getUTCMinutes() + ':';
              var s = date.getUTCSeconds();
              var hs = date.getUTCMilliseconds();
              return h+m+s+'.'+hs;
            }
          }
        }
      ],
      yAxis: [
        {
          name: '电流/A',
          type: 'value',
        },
        {
          name: '行程/mm',
          type: 'value'
        }
      ],
      series: [
        {
          name: '合闸线圈电流',
          type: 'line',
          data: [0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.053612, 0.1031, 0.152588, 0.2094992, 0.26393598, 0.2977528, 0.325796, 0.35878798, 0.3827072, 0.4198232, 0.441268, 0.4635376, 0.4808584, 0.5080768, 0.511376, 0.5385944, 0.5410688, 0.5641632, 0.5757104, 0.5872576, 0.5880824, 0.6012792, 0.60375357, 0.63097197, 0.647468, 0.6499424, 0.6656136, 0.6614896, 0.6812848, 0.6623144, 0.684584, 0.672212, 0.6755112, 0.6746864, 0.6895328, 0.6977808, 0.7076784, 0.7043792, 0.705204, 0.7184008, 0.7167512, 0.7249992, 0.725824, 0.7307728, 0.7307728, 0.73407197, 0.7249992, 0.7266488, 0.7184008, 0.7192256, 0.7200504, 0.71757597, 0.7241744, 0.7151016, 0.7085032, 0.7184008, 0.70108, 0.69035757, 0.6771608, 0.6697376, 0.6606648, 0.6573656, 0.622724, 0.6153008, 0.5971552, 0.5913816, 0.5872576, 0.57736, 0.57736, 0.5880824, 0.5781848, 0.5864328, 0.5790096, 0.5922064, 0.6095272, 0.6012792]
        },
        {
          name: '分闸线圈电流',
          type: 'line',
          data:  [0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.0503128, 0.045364, 0.0486632, 0.049488, 0.0503128, 0.0585608, 0.0635096, 0.070108, 0.0461888, 0.053612, 0.0503128, 0.0379408, 0.049488, 0.0395904, 0.0544368, 0.0651592, 0.0585608, 0.057736, 0.0684584, 0.0651592, 0.074232, 0.0725824, 0.0602104, 0.0643344, 0.0560864, 0.0602104, 0.0486632, 0.0602104, 0.053612, 0.0569112, 0.0527872, 0.0486632, 0.049488, 0.0503128, 0.053612, 0.051962398, 0.0461888, 0.0478384, 0.0470136, 0.0503128, 0.0610352, 0.0626848, 0.0684584, 0.0626848, 0.0643344, 0.0635096, 0.0626848, 0.057736, 0.0709328, 0.0635096, 0.065983996, 0.0734072, 0.0626848, 0.0569112, 0.0527872, 0.059385598, 0.059385598, 0.0668088, 0.0470136, 0.0643344, 0.0643344, 0.0668088, 0.0750568, 0.0717576, 0.0734072, 0.0626848, 0.065983996, 0.0717576, 0.0643344, 0.0635096, 0.0569112, 0.0610352, 0.0602104, 0.0560864, 0.0651592, 0.0626848]
        },
        {
          name: '触头行程',
          type: 'line',
          yAxisIndex: 1,
          lineStyle: {
            width: 1
          },
          data:  [0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998, 0.42999998]
        }
      ]
};
目前是拿到开始的时间戳 或者能否告诉如何实现会更优化 更优美
目前在荣耀9 苹果8 vivoX20上测试过 暂且未发现问题

**Comment by Ovilia** [comment]
问题是啥？报错么，这是哪里的信息，ECharts 没有 deepClone 什么的

**Comment by caizhendi** [comment]
> 问题是啥？报错么，这是哪里的信息，ECharts 没有 deepClone 什么的

嗯 报错 会导致小程序闪退 deepClone无视 按照我上面的代码来 nubiaZ17s会闪退 页面直接出现各种问题 卡死等症状 
![image](https://user-images.githubusercontent.com/15686186/47402930-2ca82880-d77a-11e8-9a63-0ffcc5280494.png)
进入页面 稍等一会就会报这个错 然后导致闪退
我的需求是会给一个开始的时间戳 然后2hm递进 大佬可以帮忙看下 如何优化吗？我也有极度怀疑是我自己写的代码有问题。 目前已测无问题的机子：荣耀8 荣耀9 vivox20 苹果8 
麻烦大佬了，同时祝大佬节日快乐~

**Comment by caizhendi** [comment]
目前把所有代码注释掉 仅仅是 引入组件 在页面上使用这个组件 而不做任何set 手机也会闪退 
好奇setTimeout的报错是什么？
努比亚z17S手机

**Comment by caizhendi** [comment]
![image](https://user-images.githubusercontent.com/15686186/47412206-9f76cb00-d79d-11e8-86e4-88d2bbbc76a7.png)
![image](https://user-images.githubusercontent.com/15686186/47412225-b1f10480-d79d-11e8-9bd8-fd6a53f29928.png)
![image](https://user-images.githubusercontent.com/15686186/47412248-c503d480-d79d-11e8-8b63-65766eb9576d.png)

**Comment by caizhendi** [comment]
down了官方的demo下来 准备用自己手机预览一下 结果代码过大 我把原项目的echarts更换成了官方定制的js
![image](https://user-images.githubusercontent.com/15686186/47420318-b83cac00-d7b0-11e8-9da1-cbf337860a74.png)
![image](https://user-images.githubusercontent.com/15686186/47420324-bd016000-d7b0-11e8-84a1-700729409af0.png)
![image](https://user-images.githubusercontent.com/15686186/47420333-c094e700-d7b0-11e8-8647-1ab0d847c45a.png)
![image](https://user-images.githubusercontent.com/15686186/47420338-c38fd780-d7b0-11e8-8bc9-bb72ba2b796f.png)
用我手机去预览折线图 刚进去除了一些样式跟原来的不一样（可能是因为我没下载下来） 过了一会 依然报错 
![image](https://user-images.githubusercontent.com/15686186/47420400-e8844a80-d7b0-11e8-8161-1d688f7bb459.png)
机型:努比亚z17s 微信版本:6.7.3  手机系统信息:v3.16 安卓版本7.1.1

**Comment by Ovilia** [comment]
你定位看下报的错是哪行的。如果是有些机型有问题，有些没有，多半就是微信小程序的问题。

**Comment by caizhendi** [comment]
我尝试着注释几处setTimeout 发现感觉毫无意义。。。。你们前面代码的逻辑我基本看不懂 瞎猫碰死耗子。。

**Comment by lizesheng0313** [comment]
@Ovilia   我的也报这个错了，不点击也会报错， 怎么回事

**Comment by lizesheng0313** [comment]
https://developers.weixin.qq.com/community/develop/doc/0002e0e77ccc0827f187b9e1e56800   给微信官网提问了    大家帮忙顶一下 看下 到底谁的问题   安卓机有问题

**Comment by lizesheng0313** [comment]
会导致tooltip不显示

**Comment by caizhendi** [comment]
> 我也遇到这个问题 我的是因为 来回切换图表出现的， @caizhendi 你是来回切换图表吗

我主要引入这个组件 放着一会就会报错。。。。

**Comment by caizhendi** [comment]
> 你定位看下报的错是哪行的。如果是有些机型有问题，有些没有，多半就是微信小程序的问题。

谢谢大佬 https://developers.weixin.qq.com/community/develop/doc/0002e0e77ccc0827f187b9e1e56800 小程序官方已经领回去了  着实不好意思 打扰了
