### ISSUE TITLE
echarts 页面上图表不渲染 目前不敢确定哪边的问题 只是来请教下 

### ISSUE THREAD

**Issue by caizhendi** [ecomfe/echarts-for-weixin#376]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
问题：页面上echarts 图表不渲染;getOption()取得到配置 而为啥页面不渲染？
目前所测机型：荣耀8 vivoX20  
苹果6 苹果8测了 无此情况 感觉又是安卓的锅 
场景1：有可能是第一次进页面setOption 不执行 console.log测试了 忘记截图了
场景2：c是echarts页面 从a->b->c->b->a 然后进入不同的a 再a->b->c 会出现下列情形echarts图表不渲染
![image](https://user-images.githubusercontent.com/15686186/47892367-39bbca80-de92-11e8-9868-e8b2023bf5c9.png)
![image](https://user-images.githubusercontent.com/15686186/47892363-34f71680-de92-11e8-8489-7bf308ace217.png)
getOption() 取得到配置数据 但是页面上无echarts图表
![image](https://user-images.githubusercontent.com/15686186/47892381-52c47b80-de92-11e8-9c8c-695c2a6bd32e.png)
页面上已删除其他组件标签和逻辑的判断
### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）
![image](https://user-images.githubusercontent.com/15686186/47892394-6e2f8680-de92-11e8-9069-ac48d9673161.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by caizhendi** [comment]
![image](https://user-images.githubusercontent.com/15686186/47896057-93c68b00-dea6-11e8-9230-731372e6349b.png)
![image](https://user-images.githubusercontent.com/15686186/47896067-a04ae380-dea6-11e8-8437-4af37ae2728b.png)
好奇 什么情况下setOption会不执行？

**Comment by caizhendi** [comment]
改成lazyload的写法 目前实测暂时没问题 
但是不用按钮触发的话 
ec: {
      onInit: initChart
    },
这个不能减少 不然线出不来

**Comment by caizhendi** [comment]
> 代码提供一下
代码逻辑有点复杂 提供了估计您也看不懂 
我现在改成lazyload的用法 以上的问题是不存在了 我最初的写法为
![image](https://user-images.githubusercontent.com/15686186/47898872-a8108500-deb2-11e8-9bba-d7ba73b9c904.png)
但是我好奇的是 getOption有返回值 为啥图表还存在渲染不出来的情况呢 还有 setOption什么情况下会不执行呢

**Comment by wJiaLiang** [comment]
这个加载不出来的问题解决了吗，我也用的lazyload 方式加载，在安卓中正常，在iOS中有时图表加载不出来，
