### ISSUE TITLE
怎么使用全国地图

### ISSUE THREAD

**Issue by dafuchixigua** [ecomfe/echarts-for-weixin#385]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：[x]
就是map组件 怎么使用全国地图 示例只有 河南

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by nciefeiniu** [comment]
菜鸡同问，怎么导入china.js

**Comment by Jarsey** [comment]
菜鸟同问……弄了两个小时没弄好

**Comment by Ovilia** [comment]
把[这个文件](https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/map/mapData.js) `module.exports =` 之后的内容替换为其他地图 JSON 格式的内容。

**Comment by Jarsey** [comment]
> 把[这个文件](https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/map/mapData.js) `module.exports =` 之后的内容替换为其他地图 JSON 格式的内容。

确实是这样的哎，在网上找了china.js文件，然后找到对应的json贴上去就可以了，多谢大佬

**Comment by JedidiahY** [comment]
module.exports = {"type": "FeatureCollection",
"features":
[
{"type": "Feature.........

**Comment by one-tream** [comment]
> > 把[这个文件](https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/map/mapData.js) `module.exports =` 之后的内容替换为其他地图 JSON 格式的内容。
> 
> 确实是这样的哎，在网上找了china.js文件，然后找到对应的json贴上去就可以了，多谢大佬

在哪里找到的全国地图的js？可以分享给我吗？
