### ISSUE TITLE
如何通过触屏控制辅助线的显示和隐藏

### ISSUE THREAD

**Issue by smallsun0122** [ecomfe/echarts-for-weixin#386]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
图标中滑动时候出现指示线，当手指停止滑动时，隐藏指示线
![image](https://user-images.githubusercontent.com/22772199/48342143-e6bfef80-e6a9-11e8-8311-98f1e6edf8e9.png)

无法监听触屏事件去控制显示隐藏。

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
axisPointer
话说这种只跟 ECharts 相关，跟小程序没关系的应该到 ECharts 项目下面提问。
