### ISSUE TITLE
真机调试  小程序渲染图表太慢  提示 等待同步API measureText 调用

### ISSUE THREAD

**Issue by wufeng123456** [ecomfe/echarts-for-weixin#389]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
使用mpvue渲染图表信息  （一个页面有7-8个echarts图表）接口数据处理完成后
发现 图表没有渲染出来  真机调试查看     卡在 “等待同步API measureText 调用”这一步

### 预期效果：
图表数据 提供完成   快速 渲染图表 ）
（如有需要请提供预期的图）

### 实际效果：
等待时间超级长（1分钟左右）   超出了正常等待时间

（如有需要请提供截图）
![image](https://user-images.githubusercontent.com/22437517/48749223-eb416500-ecb4-11e8-88ad-49ca111023f7.png)

### 复现环境：
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
跟这个库有什么关系？？

**Comment by wanglin88207056** [comment]
解决了吗

**Comment by GitACDreamer** [comment]
@wufeng123456 同问，这个问题解决了没？ @Ovilia 不跟这个有关系，那跟什么有关系？

**Comment by wufeng123456** [comment]
这个好像是模拟器的问题，我当时是在正式环境发布后这个问题就没了

**Comment by GitACDreamer** [comment]
@wufeng123456 刚刚发布体验版本，确实挺快的，没有出现卡顿的问题。。。，感谢感谢

**Comment by bbf13** [comment]
同样的问题，怎么解决的？
