### ISSUE TITLE
tooltip 支持 - 20180825 更新：Tooltip 现在可以试用了

### ISSUE THREAD

**Issue by auroradcx** [ecomfe/echarts-for-weixin#4]
请问Echarts可否支持tooltip？相信很多人都需要这个功能，为啥没有做呢？

**Comment by Ovilia** [comment]
因为 ECharts 中 tooltip 的实现是使用 HTML 渲染的，小程序不支持 DOM 操作，如果要支持的话，需要重新实现基于 Canvas 的 tooltip，工作量很大。
当然，这个还是准备做的，只是短期内可能没法支持。

**Comment by auroradcx** [comment]
好吧……好期待~

**Comment by WuHuaJi0** [comment]
同样期待

**Comment by XuKen** [comment]
期待

**Comment by KevinFan520** [comment]
待

**Comment by weifei0228** [comment]
期待

**Comment by halilolocjya** [comment]
期待tooltip~~

**Comment by JeoyZhang** [comment]
老哥老姐们，我想获取动态数据传入echarts去进行更新应该怎么做啊

**Comment by RikaLuo** [comment]
我想请问一下 有没有什么替代办法能展示这个提示框呢？ 比较着急

**Comment by Ovilia** [comment]
@RikaLuo 短期内没办法支持哦，开发人力有限

**Comment by Mrhard** [comment]
现在能不能toople对应的参数呢取到对应的值呢？

**Comment by Mrhard** [comment]
@Ovilia 现在能不能toople对应的参数呢取到对应的值呢？

**Comment by Ovilia** [comment]
@Mrhard 什么意思？

**Comment by Mrhard** [comment]
@Ovilia 
类似于这样
tooltip: {
        trigger: 'axis',
        formatter: function (params) {
          console.log(params)
        }
      },
我需要用到这个params里的数据，就是手指滑动的时候，使用这个数据做一些处理，但是在小程序里拿不到这个，如果不用tooltip的话，用什么方式能拿到tooltip里对应的params呢

**Comment by Mrhard** [comment]
@Ovilia 我拿到了
xAxis: {
        type: 'category',
        boundaryGap: false,
        axisPointer:{
          label:{
            formatter:function(params){
              console.log(params)
            }
          }
        },
      },
这个可以拿到，麻烦您啦~

**Comment by haizhilin2013** [comment]
期待

**Comment by haizhilin2013** [comment]
@Ovilia 大概什么时候能支持呢？

**Comment by Ovilia** [comment]
短期内（一个月内）无法支持，目前在做更高优的需求，档期有点不够，请理解一下~ 欢迎给我们提 PR~

**Comment by wuchao555** [comment]
期待，着急

**Comment by phpjishu** [comment]
tooltip真的是一个急需的需求！！！！！！

**Comment by VanFangbo** [comment]
求支持tooltip~~

**Comment by jhyz804lyb** [comment]
没有ToolTip 和咸鱼有什么区别。

**Comment by jhyz804lyb** [comment]
就一条线在那里摆着

**Comment by F-loat** [comment]
可以拿到 tooltip 的信息的话，不能预先多生成一个文本节点，然后动态调整内容和定位来实现吗？

**Comment by superJzq** [comment]
待待、待待、待待、待待、待待？要不自己写一个............

**Comment by passer101** [comment]
期待，，，

**Comment by XuKen** [comment]
@Mrhard 这样拿到值后怎么传给setData？？？万分感谢
xAxis: {
type: 'category',
boundaryGap: false,
axisPointer:{
label:{
formatter:function(params){
console.log(params)
}
}
},
},

**Comment by Mrhard** [comment]
@XuKen 
xAxis: {
type: 'category',
boundaryGap: false,
axisPointer:{
label:{
formatter:(params)=>{
console.log(params)
this.setData({
xxx:xxx
})
}
}
},
},
这样就行

**Comment by XuKen** [comment]
@Mrhard 感谢，可以了

**Comment by jnohboy** [comment]
@Mrhard  我怎么拿不到数据啊，一点反应都没有
![image](https://user-images.githubusercontent.com/20158611/43056615-cf900f6c-8e6f-11e8-8566-e024b0207e93.png)
![qq 20180723115824](https://user-images.githubusercontent.com/20158611/43056653-fae199ce-8e6f-11e8-9bd8-27d459755845.png)

**Comment by Mrhard** [comment]
@jnohboy console.log没东西吗？这个只是控制台里打印的，控制台里有数据的话，你就可以继续操作了，至于页面变化，你需要额外的去setData

**Comment by Ovilia** [comment]
给大家同步一下进展吧，基于 Canvas 的 tooltip 目前在 [ECharts](https://github.com/apache/incubator-echarts) 项目中已经实现得差不多了，等下个版本 ECharts 上线就可以使用了。急着用的话可以自己编译 ECharts 项目，不过可能现在还不是很稳定。如果有问题请及时反馈，谢谢大家！

**Comment by dj356988** [comment]
@Ovilia 还有多久

**Comment by lizesheng0313** [comment]
@Ovilia  姐姐 还需要 多久

**Comment by Ovilia** [comment]
目前还没发版，大家急着用的话我先给大家编译一个（但是可能其他功能有 bug，因为还没进行测试）。

**Comment by kenberkeley** [comment]
@Ovilia 有 bug 也好过没有啊。。。

**Comment by kenberkeley** [comment]
@Ovilia 至少还能开始着手开发，而不是停滞不前。。。呜呜呜

**Comment by kenberkeley** [comment]
@Ovilia 而且开帖至今已经半年了，我相信有 bug 也是小 bug 哈~

**Comment by Ovilia** [comment]
[echarts-20180824.zip](https://github.com/ecomfe/echarts-for-weixin/files/2317753/echarts-20180824.zip) 这是根据目前最新的 commit（ECharts[@37b2573](https://github.com/apache/incubator-echarts/commit/37b2573054f9f569882f28bf9a8868b522651412) ZRender[0cc6221](https://github.com/ecomfe/zrender/commit/0cc622196d8665f40d02b6156450cc7a87fe3a67)）打包的，我没测过，有问题及时反馈吧~
注意如果用压缩版替换的话，记得把 echarts.min.js 重命名成 echarts.js

**Comment by kenberkeley** [comment]
@Ovilia 谢谢~~~

**Comment by lizesheng0313** [comment]
姐姐我不太会用啊，用eharts.min.js改名替换 ec-canvas/echarts.js  还是没有成功呢   我是不是哪里操作错了

**Comment by lizesheng0313** [comment]
@Ovilia  姐姐我不太会用啊， 我用你给的echarts.min.js 替换了 ec-canvas/echarts.js 之后  toolip还是没能显示出来呢， 我是不是操作错了

**Comment by Ovilia** [comment]
重大更新：我更新了本项目中的 ECharts 代码 `ec-canvas/echarts.js`，Tooltip 接口和 ECharts 的一样，参见 line 的例子。

**Comment by kenberkeley** [comment]
K 线图的 tooltip 表现不太一致 @Ovilia 

小程序版本：
![image](https://user-images.githubusercontent.com/13287948/44618242-d2d3d100-a8a4-11e8-95b3-461d7deca81a.png)

Web 版本：
![image](https://user-images.githubusercontent.com/13287948/44618254-38c05880-a8a5-11e8-84df-35b3b71aae9b.png)

**Comment by huaibaomengxiang** [comment]
现在文件太大 还是等官网出定制版，希望赶紧发布哇

**Comment by lizesheng0313** [comment]
这个月能上线吗 最新的 姐姐

**Comment by yyzych** [comment]
formatter: '{a0}<br/>{b0}<br/>{c0}'

发现跟pc版本不太一样的地方：
小程序的tooltip不支持html元素了？
c0实际显示包含了类目值和数据值？

**Comment by BaconZhang** [comment]
小程序里tooltip使用了{ confine: true } 会导致浮层永远位于左上角的位置

![image](https://user-images.githubusercontent.com/13062998/45667730-f957f580-bb4c-11e8-8045-06e2ec43091e.png)

**Comment by lizesheng0313** [comment]
包太大，怎么处理呢 要上线了

**Comment by chenxtdo** [comment]
@Ovilia tooltip 无法通过 clear 清除

**Comment by Ovilia** [comment]
@lizesheng0313 压缩一下 echarts.js
