### ISSUE TITLE
两条Y轴时设置name和name的样式，模拟器正常，Android(小米5)字体很小，不受样式控制

### ISSUE THREAD

**Issue by dtboy1995** [ecomfe/echarts-for-weixin#417]
如题

**Comment by infinnie** [comment]
#449

**Comment by kkkkkkkkim** [comment]
遇到了相同的问题。。。echarts在小程序兼容性上面问题好多啊

**Comment by lululimin** [comment]
遇到了相同的问题。。。发现问题原因: 如果自定义了字体. 就会导致上面的问题

**Comment by infinnie** [comment]
> 折腾了我一晚上，终于解决了，加个空的rich: {}，字体大小设置就生效了

from https://github.com/ecomfe/echarts-for-weixin/issues/449#issuecomment-475970079

**Comment by dtboy1995** [comment]
@infinnie  谢谢
