### ISSUE TITLE
在iOS上有时候折线统计图会加重不出来

### ISSUE THREAD

**Issue by wJiaLiang** [ecomfe/echarts-for-weixin#427]
### 简单描述问题：
1. ios中有有时候数据图表初始不出来,用的也是延迟加载的例子,

### 实际效果：
[？？？](`
![_20190104191111](https://user-images.githubusercontent.com/20158614/50685576-b3b82d80-1054-11e9-877b-4cf6cc9f0f7e.jpg)
![_20190104191020](https://user-images.githubusercontent.com/20158614/50685579-b87ce180-1054-11e9-9648-a8d4b7af1f26.jpg)
![_20190104191847](https://user-images.githubusercontent.com/20158614/50685809-a780a000-1055-11e9-9390-6a7a00a8326e.png)

`)
（如有需要请提供截图）

### 复现环境：
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
宽度高度有么？自己定位一下？

**Comment by wJiaLiang** [comment]
这个手机上应该是有高度的，已经改成网页了，
