### ISSUE TITLE
折线图显示问题！

### ISSUE THREAD

**Issue by AshuoLF** [ecomfe/echarts-for-weixin#429]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息
![image](https://user-images.githubusercontent.com/21964456/50820689-482dd300-1368-11e9-8856-b2de4312f7d1.png)

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
折线图数据多的时候，会出现线断掉的情况，就像被擦除了一样，

### 预期效果：
需要这些线是连上的
![image](https://user-images.githubusercontent.com/21964456/50820898-d1dda080-1368-11e9-9dce-da71514b735c.png)

（如有需要请提供预期的图）

### 实际效果：
![image](https://user-images.githubusercontent.com/21964456/50820689-482dd300-1368-11e9-8856-b2de4312f7d1.png)
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by AshuoLF** [comment]
> ## 提问前应该做的事
> 请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：
> 
> * [x]  我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
> * [x]  我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)
> 
> ## 需提供的信息
> ![image](https://user-images.githubusercontent.com/21964456/50820689-482dd300-1368-11e9-8856-b2de4312f7d1.png)
> 
> 将符合项的 `[]` 改为 `[x]`，并补充需要的信息：
> 
> ### 简单描述问题：
> 折线图数据多的时候，会出现线断掉的情况，就像被擦除了一样，
> 
> ### 预期效果：
> 需要这些线是连上的
> ![image](https://user-images.githubusercontent.com/21964456/50820898-d1dda080-1368-11e9-9dce-da71514b735c.png)
> 
> （如有需要请提供预期的图）
> 
> ### 实际效果：
> ![image](https://user-images.githubusercontent.com/21964456/50820689-482dd300-1368-11e9-8856-b2de4312f7d1.png)
> （如有需要请提供截图）
> 
> ### 复现环境：
> * [x]  在微信开发工具中存在该问题
> * [x]  在真机上存在该问题

**Comment by xinxinxiaobei** [comment]
请问，解决这个问题了吗？

**Comment by shimangdian** [comment]
大佬，请问一下怎么解决的？
