### ISSUE TITLE
n.measureText is not a function

### ISSUE THREAD

**Issue by zhoocoo** [ecomfe/echarts-for-weixin#43]
![image](https://user-images.githubusercontent.com/24405281/37192387-1f027f2a-23a0-11e8-852e-ef539a7a8040.png)
找不到原因，请问应该怎么解决？

**Comment by Ovilia** [comment]
应该是基础库版本太低，需要 1.9.91 或以上

**Comment by zhoocoo** [comment]
基础库版本是指？

**Comment by Ovilia** [comment]
![1520575459456](https://user-images.githubusercontent.com/779050/37192925-cbdd59a2-23a2-11e8-9a54-c7cbabc6ba6f.jpg)

**Comment by zhoocoo** [comment]
我是直接将你项目里的ec-cancas当组件引入进了自己的项目的。

**Comment by Ovilia** [comment]
那也需要这样操作的

**Comment by zhoocoo** [comment]
OK，搞定了
