### ISSUE TITLE
没有手指点击图标显示提示框的功能吗？

### ISSUE THREAD

**Issue by RikaLuo** [ecomfe/echarts-for-weixin#44]
### 简单描述问题：
例如柱状图，web端是鼠标移动上去，会显示相应的提示。
期望的是微信小程序能在手势触摸能显示相应的提示。
我有添加：
   ```
tooltip: {
      trigger: 'axis',
      axisPointer: {            // 坐标轴指示器，坐标轴触发有效
        type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
      },
      formatter: function (e) {
        // return e.data.displayname;
        return 'hello';
      },
      triggerOn: 'click'
    },
```
但是测试后并没有反应

### 预期效果：
![image](https://user-images.githubusercontent.com/19562162/37194530-9b835d4a-23a9-11e8-9eba-749a7e8aeb42.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/19562162/37194538-a6619a06-23a9-11e8-8902-28e7987d3b69.png)

**Comment by RikaLuo** [comment]
希望有知道的能帮忙，谢谢了

**Comment by Ovilia** [comment]
#4
