### ISSUE TITLE
dispose方法、clear方法，报错Cannot read property 'hide' of undefined

### ISSUE THREAD

**Issue by zhumumu1992** [ecomfe/echarts-for-weixin#443]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
dispose方法、clear方法都不行，报错
`VM54:1 thirdScriptError
Cannot read property 'hide' of undefined; [Component] Event Handler Error @ pages/lazyLoad/index#bound dispose
TypeError: Cannot read property 'hide' of undefined`
哪怕我下载了官网最新的source包，https://echarts.baidu.com/download.html，2.86M大的，还是会报错，请问这个怎么解决呀？谢谢。

### 预期效果：
dispose方法应该要正常销毁实例的。

### 实际效果：
![dispose](https://user-images.githubusercontent.com/26374042/51548997-751fd100-1ea4-11e9-94a6-d83668c89a24.jpg)
![hide of undefined](https://user-images.githubusercontent.com/26374042/51549005-794bee80-1ea4-11e9-98b0-20064c237935.jpg)

### 复现环境：
- [x] 在微信开发工具中存在该问题

- [x] 在真机上存在该问题

**Comment by zhumumu1992** [comment]
今天真机测试了下，真机上面没问题了，没有报错，唯独开发者工具会报错。

**Comment by mtozhk** [comment]
我也遇到了同样问题，每次dispose图表都报错，希望开发团队能尽快解决

**Comment by mtozhk** [comment]
怎么close掉这个issue了？

**Comment by zhumumu1992** [comment]
> 怎么关闭掉这个问题了？

因为年前做这个图表的时候，遇到这个问题，后来发现在真机上是没问题的，所有就closed了。

**Comment by cjackeroo** [comment]
第一次不能关闭，报错。再点击一次就正常关闭了……

希望尽快解决。

**Comment by yee1128xxxx** [comment]
遇到了相同的问题，开发者工具和真机上都不行，都报错，怎么解决？

**Comment by yee1128xxxx** [comment]
去掉tooltip 就可以了，我是这样的

**Comment by MissSky1** [comment]
同样的问题，有半个多月一直都是开发工具有问题，但真机没问题，现在却变成真机也有问题了。。请问下怎么解决？？？

**Comment by yee1128xxxx** [comment]
你echarts里面用了
 tooltip: {
       trigger: 'axis',
        show: true
   },
这个吗？好像不支持这个。还有就是我在页面隐藏和卸载的时候做了这个操作
chart.dispose();//销毁
chart = null;





------------------ 原始邮件 ------------------
发件人: "MissSky1"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 上午10:09
收件人: "ecomfe/echarts-for-weixin"<echarts-for-weixin@noreply.github.com>;
抄送: "待续"<1344307670@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ecomfe/echarts-for-weixin] dispose方法、clear方法，报错Cannot read property 'hide' of undefined (#443)




同样的问题，有半个多月一直都是开发工具有问题，但真机没问题，现在却变成真机也有问题了。。请问下怎么解决？？？

**Comment by MissSky1** [comment]
------------------ 原始邮件 ------------------
发件人: "yee1128xxxx"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 上午10:14
收件人: "ecomfe/echarts-for-weixin"<echarts-for-weixin@noreply.github.com>;
抄送: "Administrator"<879650384@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ecomfe/echarts-for-weixin] dispose方法、clear方法，报错Cannot read property 'hide' of undefined (#443)



你echarts里面用了 
  tooltip: { 
        trigger: 'axis', 
         show: true 
    }, 
 这个吗？好像不支持这个。还有就是我在页面隐藏和卸载的时候做了这个操作 
 chart.dispose();//销毁 
 chart = null; 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "MissSky1"<notifications@github.com>; 
 发送时间: 2019年6月18日(星期二) 上午10:09 
 收件人: "ecomfe/echarts-for-weixin"<echarts-for-weixin@noreply.github.com>; 
 抄送: "待续"<1344307670@qq.com>;"Comment"<comment@noreply.github.com>; 
 主题: Re: [ecomfe/echarts-for-weixin] dispose方法、clear方法，报错Cannot read property 'hide' of undefined (#443) 
 
 
 
 
 同样的问题，有半个多月一直都是开发工具有问题，但真机没问题，现在却变成真机也有问题了。。请问下怎么解决？？？

**Comment by MissSky1** [comment]
就是这个的原因，注释掉就好了。。谢谢啦




------------------ 原始邮件 ------------------
发件人: "yee1128xxxx"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 上午10:14
收件人: "ecomfe/echarts-for-weixin"<echarts-for-weixin@noreply.github.com>;
抄送: "Administrator"<879650384@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ecomfe/echarts-for-weixin] dispose方法、clear方法，报错Cannot read property 'hide' of undefined (#443)



你echarts里面用了 
  tooltip: { 
        trigger: 'axis', 
         show: true 
    }, 
 这个吗？好像不支持这个。还有就是我在页面隐藏和卸载的时候做了这个操作 
 chart.dispose();//销毁 
 chart = null; 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "MissSky1"<notifications@github.com>; 
 发送时间: 2019年6月18日(星期二) 上午10:09 
 收件人: "ecomfe/echarts-for-weixin"<echarts-for-weixin@noreply.github.com>; 
 抄送: "待续"<1344307670@qq.com>;"Comment"<comment@noreply.github.com>; 
 主题: Re: [ecomfe/echarts-for-weixin] dispose方法、clear方法，报错Cannot read property 'hide' of undefined (#443) 
 
 
 
 
 同样的问题，有半个多月一直都是开发工具有问题，但真机没问题，现在却变成真机也有问题了。。请问下怎么解决？？？
