### ISSUE TITLE
echarts图表在小程序上生成图表层级太高

### ISSUE THREAD

**Issue by sjy1234** [ecomfe/echarts-for-weixin#459]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？在小程序上使用echarts生成的图表层级太高，微信小程序官方的cover-view标签又不能嵌套在echarts图表内部

### 预期效果：
？？？
（如有需要请提供预期的图）
![image](https://user-images.githubusercontent.com/44352047/53403322-5d30f500-39ee-11e9-8a20-144a3a95eec1.png)

### 实际效果：
？？？
（如有需要请提供截图）
![image](https://user-images.githubusercontent.com/44352047/53403358-73d74c00-39ee-11e9-847e-7fa638f1e3fb.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
在开发工具中能正常显示
- [] 在真机上存在该问题
在真机上图片就会在文字之上

**Comment by Lamenda** [comment]
这是小程序的问题吧，cavans在真机上属于原生组件，层级最高。
建议可考虑使用echarts 的[自定义系列（custom series）](https://echarts.baidu.com/tutorial.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E5%88%97)试试，把你要显示的文字信息也渲染到cavans里面

**Comment by GitACDreamer** [comment]
@sjy1234 我也遇到同样的问题，我大概描述一下：
在有canvas图表的页面，我添加了按钮，弹出popup、actionsheet窗口，发现里面的内容是显示了，但是由于绘制的图标图层在顶层，导致弹窗不能覆盖图表控件
![image](https://user-images.githubusercontent.com/19402747/54113224-cd923a00-4422-11e9-8001-4b349deabde4.png)
这个popup里面的内容有['杭州', '宁波', '温州', '嘉兴', '湖州'] 好像都被覆盖了
我试过设置z-index也没有用？ 网络上说用 <cover-view> 那这<canvas></canvas>要如何结合这个用？

**Comment by Ovilia** [comment]
现在只能用 cover-view，小程序团队正在改进这方面
