### ISSUE TITLE
把ec-canvas标签放在多个view层内，不显示。

### ISSUE THREAD

**Issue by skyjilygao** [ecomfe/echarts-for-weixin#46]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在echarts示例中测试，
1、由于业务需要，要将ec-canvas包在多个view层级中，但是不显示
2、在一层view中，class是默认的container样式，可以正常显示，但是换个其他样式就显示不了。
问题1，代码如下：
`
<view class="container">
  <view>
    <ec-canvas id="mychart-dom-pie" canvas-id="mychart-pie" ec="{{ ec }}"></ec-canvas>
  </view>
</view>`
问题2，代码如下：
`<view class="page">
  <ec-canvas id="mychart-dom-pie" canvas-id="mychart-pie" ec="{{ ec }}"></ec-canvas>
</view>`
page样式如下：
`page {
  background-color: #fff;
  font-size: 16px;
  font-family: -apple-system-font, Helvetica Neue, Helvetica, sans-serif;
}`
### 预期效果：
正常显示饼图
### 实际效果：
不显示饼图，页面空白

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by XuKen** [comment]
我也有这样的问题，雷达图

**Comment by XuKen** [comment]
@Ovilia

**Comment by Ovilia** [comment]
我在 `app.wxss` 对 `.container` 写了样式，如果不是 `.container` 也应该写样式来确保容器有宽度和高度

**Comment by qiu8310** [comment]
这就是用 :host 设置组件默认外层的样式的好处了，看这里 #56

**Comment by hanxyan** [comment]
我也有这样的问题：同样是bar文件夹代码（已设定宽高和display:block;），在多个view内的时候出现内容挤压、不能显示图表，在一层view内是正常显示。
对比：
![image](https://user-images.githubusercontent.com/26215878/54342216-d8dda380-4676-11e9-9d29-d38733804b72.png)![image](https://user-images.githubusercontent.com/26215878/54342388-41c51b80-4677-11e9-91b5-f8af7057e57c.png)
