### ISSUE TITLE
tooltip 不生效

### ISSUE THREAD

**Issue by lsiten** [ecomfe/echarts-for-weixin#462]
tooltips已经配置，但是不生效，去看官方；例子，也不生效
![微信图片_20190311085146](https://user-images.githubusercontent.com/16066866/54094313-f262bf00-43da-11e9-8edb-f7116cd8d9e8.jpg)

**Comment by xjjrocker** [comment]
我也是界面出不来，而且formatter里面或得到数据的index也不对！而且十字光标移动，提示的数据不变！
formatter: function (param) {
        var i = param[0].dataIndex;
        console.log("--------begin---------");
        console.log(i);
        console.log(xdata);
        console.log(xdata[i]);
        console.log(ydata);
        console.log(ydata[i]);
        console.log("---------end--------");
        return ""
      }

**Comment by Ovilia** [comment]
官方例子也不生效的话，是版本问题吧？是开发者工具还是真机？提供一下版本号

**Comment by xjjrocker** [comment]
可以了，是下载的版本问题




| |
xjjrocker
邮箱：xjjrocker@163.com
|

Signature is customized by Netease Mail Master

在2019年03月19日 14:23，羡辙 写道：

官方例子也不生效的话，是版本问题吧？是开发者工具还是真机？提供一下版本号
