### ISSUE TITLE
Echarts显示层级过高，fixed元素被遮盖（Taro框架）

### ISSUE THREAD

**Issue by KingGanZeng** [ecomfe/echarts-for-weixin#463]
## 提问前应该做的事
- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
通过taro引入的echarts，底部为fixed布局的菜单栏，在真机上echarts层级过高，显示异常，但在微信开发工具上未出现

### 预期效果：
![微信图片_20190318164550](https://user-images.githubusercontent.com/22743840/54517677-4fdbaa80-499d-11e9-8585-400f410960d4.png)

### 实际效果：
![微信图片_20190318164302](https://user-images.githubusercontent.com/22743840/54517627-34709f80-499d-11e9-8f5d-c74c7f923c66.png)
截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [ ] 在真机上存在该问题

**Comment by Ovilia** [comment]
现在只能用 cover-view，其他的小程序正在改进
