### ISSUE TITLE
小程序中areaStyle颜色设置后，安卓真机和苹果真机颜色差异非常明显

### ISSUE THREAD

**Issue by wang10705** [ecomfe/echarts-for-weixin#47]
areaStyle颜色设置后，安卓真机和苹果真机颜色差异非常明显，请问有办法解决没有？

**Comment by Ovilia** [comment]
应该是苹果有半透明变深的问题吧？这个问题要等下一个版本的小程序基础库推出

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
