### ISSUE TITLE
真机调试下，图表会遮挡view标签

### ISSUE THREAD

**Issue by tiyo** [ecomfe/echarts-for-weixin#48]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
svg图表遮挡了view标签

### 预期效果：
<img width="400" alt="screen shot 2018-03-10 at 12 52 17 pm" src="https://user-images.githubusercontent.com/1608989/37238471-e61cf57e-2461-11e8-8138-52f15e059606.png">

### 实际效果：
![wechatimg101](https://user-images.githubusercontent.com/1608989/37238476-fc53ddee-2461-11e8-83a2-4a93bfdb125d.jpeg)

### 复现环境：
- [x] 在真机上存在该问题

**Comment by tiyo** [comment]
自行解决了！

**Comment by xdsfoo** [comment]
@tiyo   我也预到同样问题，网上找的解决办法都试了，还是被挡，请问是怎么解决的 ？

**Comment by Choujiji** [comment]
> 自行解决了！

请为如何处理的？
