### ISSUE TITLE
在饼图绘制时，legend 使用 formatter +textStyle rich 时，legend 会重叠

### ISSUE THREAD

**Issue by CorruptKubCzh** [ecomfe/echarts-for-weixin#489]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在饼图绘制时，legend 使用 formatter +textStyle rich 时，legend 会重叠

### 预期效果：
![image](https://user-images.githubusercontent.com/22706798/56843991-600b7180-68db-11e9-867d-d196bd86d8e0.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/22706798/56843996-93e69700-68db-11e9-9030-52cbc394c033.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by CorruptKubCzh** [comment]
只要把echarts.js 替换成 新版本的echarts.js就好了

**Comment by kapbook-caizhehao** [comment]
已更换最新版本的echarts.js，但还是存在该问题，求解决

**Comment by kapbook-caizhehao** [comment]
> 只要把echarts.js 替换成 新版本的echarts.js就好了

我已经更新成最新版本echarts.js，但还是重叠

**Comment by CorruptKubCzh** [comment]
我在使用官网的最新版本的echarts.js 不会出现这样的问题，我使用的并不是微信提供的这个

**Comment by CorruptKubCzh** [comment]
> > 只要把echarts.js 替换成 新版本的echarts.js就好了
> 
> 我已经更新成最新版本echarts.js，但还是重叠

你可以在https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all上面使用的你图表代码进行模拟

**Comment by thislyc** [comment]
我也是去官网定制了一个然后替换一下就好了
