### ISSUE TITLE
小程序内不能以svg渲染

### ISSUE THREAD

**Issue by tiyo** [ecomfe/echarts-for-weixin#49]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

**代码如下：**
const chart = echarts.init(canvas, 'light', {
            width: width,
            height: height,
            renderer: 'svg'
          });

加载时出现错误：
**TypeError: Cannot read property 'createElementNS' of undefined**

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
#36
