### ISSUE TITLE
小程序内可否在page里 按需实例化图表

### ISSUE THREAD

**Issue by yvlf** [ecomfe/echarts-for-weixin#5]
我看给的例子都是页面加载的时候，自动实例化图表，我这边单个页面会有多张图表，需要按需加载，

 <ec-canvas id="mychart-dom-line" canvas-id="mychart-line" ec="{{ ec }}" ></ec-canvas>

**Comment by yvlf** [comment]
加油！焦急的等待中…… :+1:

**Comment by XuKen** [comment]
加油！焦急的等待中…… 👍+10086

**Comment by Ovilia** [comment]
动态加载图表的例子参见柱状图的例子

**Comment by jnstyle** [comment]
加油！焦急的等待中…… 👍

**Comment by JeoyZhang** [comment]
@yvlf 老哥，你是要获取数据之后再生成echarts图吗？我看了一下这里的问题，官方是说现在还不支持这样吗（就是我获取数据之后根据获取的数据实现echarts图）？

**Comment by XuKen** [comment]
@JeoyZhang 我也是获取到数据再生成echarts图，而且一个页面有多个echarts图，看官方的意思好像是不支持的。主要是demo没有详细说明

**Comment by JeoyZhang** [comment]
@XuKen 但是看他有的一些意思是说先实例化，然后可以再获取数据更新的样子，真是好懵，兄弟要是有什么进展就分享一下啊

**Comment by Ovilia** [comment]
@jnstyle 已经支持了，参见柱状图的例子
