### ISSUE TITLE
能否增加直接传 options 进行初始化 canvas 的功能？

### ISSUE THREAD

**Issue by anchengjian** [ecomfe/echarts-for-weixin#50]
## 背景：
在 mpvue 中使用 echarts 的小程序组件。

不想通过在 data 中传 function ，直接传 options 进行 canvas 图表的初始化。

## 已有完整并跑通的实现：
https://github.com/mpvue/examples/tree/master/echarts

**Comment by Ovilia** [comment]
为什么想直接传 options？有什么好处？这样会限制原有 echarts 的其他接口

**Comment by anchengjian** [comment]
感谢回复。

原来还有其他接口，我当时只看到有 lazyLoad 和 onInit 这两个接口配置。

初衷是不想用太繁琐的初始化方法，直接传一个 options 给组件渲染完就好。然后在某些情况下，通过 data 传 function 会有困难，也违背 data 的语义，感觉不优雅，大致就这样。

**Comment by Ovilia** [comment]
如果你有特殊需求可以照这个思路自己再封装一次，但通用的还是需要兼容一般的 echarts 初始化的做法

**Comment by yfzhangCode** [comment]
@anchengjian  您好，我在mpvue中使用的是您推荐的 那种方法。。由于图表较多，我在utils中把options 封装了一下，每个页面进行获取，然后赋值给ec.options，但是数据改变后，我如果在mounted中初始化 echart， 数据图表是空白（没有绘制）。。在created中初始化是可以显示的。。。疑问是：为什么在mounted(）中进行数据的初始化后没有绘制图表？
