### ISSUE TITLE
在mpvue中使用报错Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by lin5164** [ecomfe/echarts-for-weixin#503]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by lin5164** [comment]
`<template>
  <div>
    <div class="container">
      <ec-canvas :echarts="echarts" class="canvas" id="mychart-dom-bar" canvas-id="mychart-bar" :ec="ec"></ec-canvas>

    </div>
  </div>
</template>
<script>
let chart = null
import echarts from '../../../static/ec-canvas/echarts.js'
export default {
  data() {
    return {
      echarts,
      ec: {
        onInit: this.initChart,
      }
    }
  },
  methods: {
    initChart(canvas, width, height) {
      chart = echarts.init(canvas, null, {
        width: width,
        height: height
      });
      canvas.setChart(chart);

      var option = {
        title: {
          text: '测试下面legend的红色区域不应被裁剪',
          left: 'center'
        },
        color: ["#37A2DA", "#67E0E3", "#9FE6B8"],
        legend: {
          data: ['A', 'B', 'C'],
          top: 50,
          left: 'center',
          backgroundColor: 'red',
          z: 100
        },
        grid: {
          containLabel: true
        },
        tooltip: {
          show: true,
          trigger: 'axis'
        },
        xAxis: {
          type: 'category',
          boundaryGap: false,
          data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
          // show: false
        },
        yAxis: {
          x: 'center',
          type: 'value',
          splitLine: {
            lineStyle: {
              type: 'dashed'
            }
          }
          // show: false
        },
        series: [{
          name: 'A',
          type: 'line',
          smooth: true,
          data: [18, 36, 65, 30, 78, 40, 33]
        }, {
          name: 'B',
          type: 'line',
          smooth: true,
          data: [12, 50, 51, 35, 70, 30, 20]
        }, {
          name: 'C',
          type: 'line',
          smooth: true,
          data: [10, 30, 31, 50, 40, 20, 10]
        }]
      };

      chart.setOption(option);
      return chart;
    }
  },
}

</script>

<style lang='scss'>
.container {
  background-color: #ccc;
}
ec-canvas {
  width: 100%;
  height: 500rpx;
}
.tooltipContainer {
  z-index: 1000;
  background-color: rgba(0, 0, 0, 0.4);
  position: absolute;
  top: 30rpx;
  left: 14rpx;
  color: white;
  font-size: 16rpx;
  border-radius: 6rpx;
  .tooltip {
    padding: 6rpx 16rpx;
    justify-content: flex-start;
    &:first-child {
      padding-top: 10rpx;
    }
    &:last-child {
      padding-bottom: 10rpx;
    }
    .color {
      margin-right: 8rpx;
      display: inline-block;
      height: 22rpx;
      width: 22rpx;
      border-radius: 50%;
      background-color: black;
    }
  }
}
</style>`

**Comment by w1922616586** [comment]
解决了嘛  我遇到了同样的问题
