### ISSUE TITLE
tooltip不支持extraCssText吗

### ISSUE THREAD

**Issue by chavesgu** [ecomfe/echarts-for-weixin#509]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
设置extraCssText无效

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
小程序版本的 tooltip 是基于 canvas 实现的，所以不可能支持 css

**Comment by chavesgu** [comment]
> 小程序版本的 tooltip 是基于 canvas 实现的，所以不可能支持 css

我觉得应该兼容echarts原本的配置项吧，比如我要旋转tooltip，怎么实现呢？

**Comment by xuqingyou** [comment]
echarts  如何横屏显示啊
