### ISSUE TITLE
使用wx.navigateTo() 跳转报错jsEnginScriptError

### ISSUE THREAD

**Issue by RikaLuo** [ecomfe/echarts-for-weixin#51]
点击A页面的按钮，通过wx.navigateTo()方法 到B页面，第一次点击无任何问题。
点击B页面自带返回按钮至A页面后，再次点击A页面按钮至B页面时，控制台出现报错：
![image](https://user-images.githubusercontent.com/19562162/37263782-ab30a15c-25e4-11e8-89d0-316349d41a92.png)

B页面中有多个echart图标。
经测试，将B页面的Echarts图标注释后，A、B页面的跳转无报错现象。
求各位大神指点迷津，谢谢了

**Comment by Ovilia** [comment]
app.json 里写了该页面吗？

**Comment by RikaLuo** [comment]
app.json 里面有该页面

**Comment by RikaLuo** [comment]
@Ovilia  app.json 里面有该页面的。

**Comment by Ovilia** [comment]
示例有这个问题吗？

**Comment by RikaLuo** [comment]
@Ovilia 事例无此问题，我是完全按照事例复制过来的，只对数据做了调整 ，请问是否能帮忙看看呀？

**Comment by Ovilia** [comment]
那就一点点调试定位看是哪里的改变引起的问题吧~
