### ISSUE TITLE
通过bind:init异步获取数据的方法渲染图表，tooltips点击无效

### ISSUE THREAD

**Issue by kkxiaoa** [ecomfe/echarts-for-weixin#517]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by kkxiaoa** [comment]
如果我按照文档在data里通过mock数据的方法渲染图表，tooltips点击正常显示，但是如果我通过bind:init异步获取数据的方法渲染图表，tooltips点击无任何效果

**Comment by AdorableLi** [comment]
我也遇到了这个问题，请问解决了嘛？

**Comment by kkxiaoa** [comment]
@AdorableLi  解决了  你仔细阅读一下首页md指出的注意事项，改变一下写法就行了
