### ISSUE TITLE
真机 legend 不显示

### ISSUE THREAD

**Issue by sishuiruhuo** [ecomfe/echarts-for-weixin#52]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
微信模拟器跟真机显示不一致。使用官方的ECharts Demo。真机苹果7。坐标下的显示没有，右上角的也没有。好像是超过坐标范围的显示都会失效。

### 预期效果：
![image](https://user-images.githubusercontent.com/21232006/37271008-0e74dfc2-260c-11e8-8550-0a832ee12e80.png)

- 

（如有需要请提供预期的图）

### 实际效果：
![image](https://user-images.githubusercontent.com/21232006/37271001-01861aa6-260c-11e8-8d84-41faddf1ea18.png)

（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by sishuiruhuo** [comment]
@Ovilia 
是的啊。我完全用的是官方demo。
html
<view class="container">
  <ec-canvas id="mychart-dom-line" canvas-id="mychart-line" ec="{{ ec }}"></ec-canvas>
</view>
css
/**app.wxss**/
.container {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;

  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  box-sizing: border-box;
} 

/**index.wxss**/
ec-canvas {
  width: 100%;
  height: 100%;
}
其他图形显示都很正常，就这个显示有问题。

**Comment by Ovilia** [comment]
option 怎么写的？这显然不是官网例子里的 option

**Comment by sishuiruhuo** [comment]
@Ovilia 
不好意思截图的时候我稍微修改了下option 的参数。下面是我大体修改的内容，当时截图的时候我没有保存，颜色以及位置可能不正确。
`
tooltip: {
      trigger: 'axis',
      axisPointer: {
        type: 'cross',
        label: {
          backgroundColor: '#6a7985'
        }
      }
    },
  legend: {
      orient: 'vertical',
      right: 20,
      top: 15,
      data: ['A商品', 'B商品', 'C商品']
    },
`
下面是官方的截图模拟器：
![1520922906 1](https://user-images.githubusercontent.com/21232006/37326188-f30da5fa-26cb-11e8-8f9a-ac361390cdce.jpg)
真机：
![338067791556232148](https://user-images.githubusercontent.com/21232006/37326227-161e33d4-26cc-11e8-8be3-68f41b7aa002.jpg)

**Comment by Ovilia** [comment]
不太清楚……我还是怀疑图表 div 超出屏幕范围了吧？

**Comment by Haaayden** [comment]
我这边也是遇到了同样的问题，模拟器上可以正常显示图例区域，但是真机上，原本图例所在的区域会正常占位，但就是不显示图例，手动调整图例legend位置参数到折线图所在的区域可以看到图例，但是超出折线区域的就会被截断

**Comment by Haaayden** [comment]
在真机上使用官方小程序，也能看到他不显示折线图的图例

**Comment by Ovilia** [comment]
@Haaayden 真机是安卓还是 ios？微信版本号是？

**Comment by Haaayden** [comment]
iOS 微信版本6.6.5 iPhone8P

**Comment by Ovilia** [comment]
复现出来了，等我排查一下

**Comment by czhongm** [comment]
还没找出问题么？另外加了title和datazoom 也是显示不出来

**Comment by NortonLee** [comment]
有没有最新进展？我刚提了issues，发现重复了。

**Comment by Ovilia** [comment]
这个问题由微信小程序修复了，需要等待微信下一次发版

**Comment by czhongm** [comment]
微信方没给出具体时间么？或者有什么临时措施解决下？

**Comment by Ovilia** [comment]
这两天就会修复

**Comment by Ovilia** [comment]
小程序代码不需要修改，等微信开发者工具更新即可

**Comment by czhongm** [comment]
微信开发工具更新到1.02.1804080了，问题还存在，这版没修正么？

**Comment by Ovilia** [comment]
@czhongm 我在跟他们沟通~

**Comment by blockmood** [comment]
我也在等待这个问题的修复。

**Comment by Ovilia** [comment]
问了一下，需要微信客户端上新版本，预计在四月中下旬

**Comment by hepking** [comment]
这个问题还没解决吗？大约到什么时候？

**Comment by hepking** [comment]
实测，两个还是可以，三个以上就隐藏了

**Comment by yuliezhou** [comment]
多久修复啊.大佬们,有人知道吗

**Comment by wuxiang364** [comment]
我这也是，安卓没问题，选中两个以及以下的是可以显示图列。超过就没了，这个问题是微信解决吗？

**Comment by Ovilia** [comment]
亲测 ios 6.6.7 已修复，再试试？

**Comment by wuxiang364** [comment]
是的，刚从6.6.6更新到6.6.7，可以了，很赞

**Comment by herohql521** [comment]
请问什么时候能支持折线图手势缩放
