### ISSUE TITLE
想请教一下一个页面多图表的定位问题

### ISSUE THREAD

**Issue by Lninn** [ecomfe/echarts-for-weixin#526]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
如图所示，页面中所有的图表是放在 scroll-view 中的，想实现通过点击页面顶部的按钮，调到对应的图表去。在模拟器上没有出现问题，可以通过按钮跳转到对应的图表ID，也可以上下滑动；在真机上演示的时候，滑动没有问题，当点击按钮的时候，页面的元素不受控制，会出现图表绘制错误或不绘制。

### 预期效果：
![img1.jpg](https://i.loli.net/2019/07/13/5d29df14a6f0032640.jpg)

### 实际效果：
![img2.jpg](https://i.loli.net/2019/07/13/5d29df725c32528681.jpg)

### 部分代码
![img3.jpg](https://i.loli.net/2019/07/13/5d29dfcd3610680320.jpg)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
这样描述不太好帮你找原因，建议自己先 debug 下，看看是哪部分的问题

**Comment by Lninn** [comment]
谢谢，我后面重新改了一下 scroll-view 和 图表组件的布局样式，又实现了我要的效果，因该是定位的问题。

**Comment by riordondj** [comment]
想问你用的是mpvue-echarts吗，想问你是如何解决 canvas标签不能在scroll-view里的问题的呢

**Comment by Lninn** [comment]
> 想问你用的是mpvue-echarts吗，想问你是如何解决 canvas标签不能在scroll-view里的问题的呢

我这边是 css 定位的问题。我感觉小程序 scroll-view 里面嵌入 canvas 还是不太稳定，最好换个方式。
