### ISSUE TITLE
Cannot read property 'type' of undefined;at SelectorQuery callback function

### ISSUE THREAD

**Issue by shuch** [ecomfe/echarts-for-weixin#557]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
echart.js github 版本图表可以正常显示，使用[官网定制](https://www.echartsjs.com/zh/builder.html)版时图表无法显示，并报错

### 预期效果：
定制版echart.js和github版本都能正常显示
（如有需要请提供预期的图）

### 实际效果：
echart.js github 版本图表可以正常显示，使用 [官网定制](https://www.echartsjs.com/zh/builder.html)时图表无法显示，并报错

![A2BCA4F2-7DAA-46f9-8C20-CE43403C7135](https://user-images.githubusercontent.com/29475098/65401430-a3223000-ddfa-11e9-8671-8476584dd424.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by daxiahu** [comment]
遇到同样的问题，求解

**Comment by shuch** [comment]
官网定制版本的压缩格式和taro的打包有冲突，解决方案参考 https://github.com/shuch/blog/issues/9 

> 遇到同样的问题，求解

**Comment by hujiamei920122** [comment]
遇到同样的问题，求解

**Comment by wgh970312** [comment]
可以试试修改编译配置`mini.compile.exclude`
[https://nervjs.github.io/taro/docs/config-detail/#minicompileexclude](url)
