### ISSUE TITLE
使用的官方提供的案例【小米8】手机会有一个bug，所有字体都缩小了

### ISSUE THREAD

**Issue by newBird01** [ecomfe/echarts-for-weixin#559]
使用的官方提供的案例【小8米手机】【 微信版本7.0.6】【系统版本 Android9】
![WechatIMG268](https://user-images.githubusercontent.com/25924193/65657370-b67d0780-e055-11e9-8470-26065ddd32c4.png)

**Comment by newBird01** [comment]
x轴，y轴的字体都缩小的快看不见了。

**Comment by witsea** [comment]
在mate9上也是这样，解决了没有？？

**Comment by witsea** [comment]
换一个最新的echarts.js，官网下载一个就可以了

**Comment by zhangsao** [comment]
yAxis & xAxis
添加
axisLabel: {
fontSize: '13',
}

series 里面 添加

label: {
normal: {
show: true,
position: 'top',
rich: {}
}
},
