### ISSUE TITLE
在自己项目中无法显示 Echarts 组件

### ISSUE THREAD

**Issue by green-dalii** [ecomfe/echarts-for-weixin#59]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
参考教程，拷贝 ec-canvas 目录，将pages/bar添加到自己的项目中，同时按教程修改了app.json，并保持目录结构同 echarts demo 一致。echarts不显示，也无报错。
console如图：
![a](https://user-images.githubusercontent.com/7144084/37341668-2d111968-26fd-11e8-9dce-c1c03ff8d52c.JPG)

### 预期效果：
能正常运行echarts

### 实际效果：
![b](https://user-images.githubusercontent.com/7144084/37341625-0edf8e2a-26fd-11e8-8e8d-8b599b6d2b81.JPG)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by qiu8310** [comment]
我猜你问题也是 和 #46 一样的，官方的组件默认是 inline 的，没有宽高，你需要写组件的时候指定，比如

```html
<ec-canvas style="display:block; width: 100%; height: 400px;" ...></ec-canvas>
```

已经给官方提了意见了，见 #56

**Comment by qiu8310** [comment]
我猜你问题也是 和 #46 一样的，官方的组件默认是 inline 的，没有宽高，你需要写组件的时候指定，比如

```html
<ec-canvas style="display:block; width: 100%; height: 400px;" ...></ec-canvas>
```

已经给官方提了意见了，见 #56

**Comment by green-dalii** [comment]
@qiu8310 谢谢，确实是这个问题，已解决！
