### ISSUE TITLE
如何监听切换图例的事件？？小程序端的

### ISSUE THREAD

**Issue by HuaZaiWuDi** [ecomfe/echarts-for-weixin#60]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by HuaZaiWuDi** [comment]
小程序中图标的事件如何监听？？

**Comment by Ovilia** [comment]
你能获取 `chart` 实例，参考 echarts 的写法

**Comment by HuaZaiWuDi** [comment]
`    chart.on('legendselectchanged', function (params) {
        console.log('点击图例', params)
      })
`
比如获取图例的写法是这样吗？但是完全没有效果啊。麻烦指点下

**Comment by HuaZaiWuDi** [comment]
谢谢，已经可以了

**Comment by NANAYWY** [comment]
> 你能获取 `chart` 实例，参考 echarts 的写法

请问如何监听拖动datazoom在小程序端 @Ovilia
