### ISSUE TITLE
echarts 使用resize() 实现响应式宽高失效

### ISSUE THREAD

**Issue by hongaah** [ecomfe/echarts-for-weixin#601]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在微信小程序中，echarts 高度不能响应式。
我的方法是：根据需要渲染的数据大小，改变echarts的外部容器高度，然后使用echarts实例的resize()方法。

### 预期效果：
想根据数据量的大小，改变echarts的外部容器高度，改变echarts高度
（如有需要请提供预期的图）

### 实际效果：
echarts的外部容器高度改变了，但echarts高度没变
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by hongaah** [comment]
chart.resize({ width: chart.getWidth(), height: xxx })

**Comment by wangz-code** [comment]
非常感谢, 可以了 整这个这个微信小程序动态高度真折磨

**Comment by cocofei2020** [comment]
@wangz-code 请问怎么解决的？

**Comment by wangz-code** [comment]
> [@wangz-code](https://github.com/wangz-code) 请问怎么解决的？
```html
          <!-- canvas高度过高会1365 导致页面在ios下无法渲染 -->
          <view class="report-echart--show" style="height: {{echartHeight}}px;">
              <ec-canvas id="report" canvas-id="report" ec="{{ ec }}"></ec-canvas>
         </view>

```

```js

        // 动态计算高度 dpr 一定要传递不然会模糊
	reloadChartHeight: function (echartHeight, option) {
		if (echartHeight > 1365) echartHeight = 1365;
		if (echartHeight < 500) echartHeight = 500;
		this.setData({ echartHeight });
		chart.resize({ dpr: chartDpr, width: chart.getWidth(), height: echartHeight });
		chart.setOption(option, { notMerge: true });
	},



```
