### ISSUE TITLE
Funnel的label, position设为'insideLeft' 无效

### ISSUE THREAD

**Issue by HermanZzz** [ecomfe/echarts-for-weixin#603]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
Funnel的label, position设为'insideLeft' 无效

### 预期效果：
标签的位置在漏斗图梯形内部左侧。

### 实际效果：
position:'insideLeft' 与没有设置position效果一样.
设置position: 'inside'是可以生效的.

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
这个应该是你使用的时候 demo 项目的 ECharts 版本还没更新到最新，现在 master 上已经更新到 4.6.0 了，请重新试一下。

**Comment by HermanZzz** [comment]
更新后已解决
