### ISSUE TITLE
tooltip formatter不支持自定义dom标签

### ISSUE THREAD

**Issue by jessyHong** [ecomfe/echarts-for-weixin#604]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
tooltip formatter不支持自定义dom标签换行

### 预期效果：
官网Echarts支持
![image](https://user-images.githubusercontent.com/13619454/72056752-26af5080-3308-11ea-8c9f-6c3e1045fb18.png)

### 实际效果：
？？？
（如有需要请提供截图）
![image](https://user-images.githubusercontent.com/13619454/72056816-48103c80-3308-11ea-98ed-3221755f74db.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Gusiil** [comment]
dom写法应该不行，就是br不能换行很蛋疼

**Comment by Ovilia** [comment]
因为微信小程序不支持 DOM 操作，所以在小程序里使用 ECharts tooltip 的时候，[renderMode](https://echarts.apache.org/zh/option.html#tooltip.renderMode) 是 `'richText'`，换行尝试用 `'\n'`。
