### ISSUE TITLE
[bug report]柱状图category标题显示不全

### ISSUE THREAD

**Issue by HARDCOREAJ** [ecomfe/echarts-for-weixin#614]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
根据demo的柱状图例子, 封装成组件以后展示在页面中, category的标题显示不全

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by HARDCOREAJ** [comment]
很可惜 无法上次bug图片

**Comment by Ovilia** [comment]
[interval](https://echarts.apache.org/zh/option.html#xAxis.interval) 设为 0 可以强制显示所有标签。这个不是小程序 ECharts 的问题，请仔细阅读 ECharts 文档。
