### ISSUE TITLE
华为手机使用新版Canvas 2d绘图异常,旧版Canvas绘图正常

### ISSUE THREAD

**Issue by OAHNAUY** [ecomfe/echarts-for-weixin#619]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
华为手机使用新版Canvas 2d绘图异常,旧版Canvas绘图正常,目前测试了华为荣耀10,华为P30

比如折线图不显示横纵坐标,饼图不显示数值,仪表盘不显示数字

### 预期效果：
？？？
（如有需要请提供预期的图）
<img width="172" alt="image" src="https://user-images.githubusercontent.com/12781579/76142473-271a5c80-60a9-11ea-8bf9-02ba27e49ca0.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/12781579/76142346-db1ae800-60a7-11ea-8a1f-28755ab36f49.png">
<img width="389" alt="image" src="https://user-images.githubusercontent.com/12781579/76142352-e706aa00-60a7-11ea-8ab0-3d639a74517e.png">
<img width="387" alt="image" src="https://user-images.githubusercontent.com/12781579/76142357-eff77b80-60a7-11ea-88d4-254648a4e769.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/12781579/76142370-01d91e80-60a8-11ea-875e-c6cb48ddb77c.png">

### 实际效果：
？？？
（如有需要请提供截图）
<img width="402" alt="image" src="https://user-images.githubusercontent.com/12781579/76142312-69429e80-60a7-11ea-8a6a-fd5f2e17f4b8.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/12781579/76142316-87a89a00-60a7-11ea-956c-933b330d1974.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/12781579/76142320-9db65a80-60a7-11ea-99e7-3a1b1e96e129.png">
<img width="165" alt="image" src="https://user-images.githubusercontent.com/12781579/76142327-b161c100-60a7-11ea-9131-65e1e2c5cef2.png">

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题  目前测试华为荣耀10,华为P30

**Comment by OAHNAUY** [comment]
<img width="172" alt="image" src="https://user-images.githubusercontent.com/12781579/76142454-e7537500-60a8-11ea-8c65-caea57a9325f.png">
还有一张正常绘制的饼图,有数字,新版的canvas 2d没有数字

**Comment by Ovilia** [comment]
提供一下配置项

**Comment by OAHNAUY** [comment]
目前相同的配置iPhone,小米手机上使用最新版的echarts正常,华为异常.微信官方社区里很多反馈华为手机对于canvas 2d支持有bug,能否帮忙验证一下最新版的官方微信小程序echarts示例在华为真机上能否正常运行呢?

**Comment by Ovilia** [comment]
如果是 canvas 2d 的问题，那只能等微信小程序修复了，这个问题就自然修复了。

**Comment by OAHNAUY** [comment]
微信小程序基础库2.11.0已修复

**Comment by JX-Zhuang** [comment]
企业微信小程序，雷达图indicator name 英文和数字没有展示

**Comment by niconicoli** [comment]
怎么使用小程序基础库2.11.0，我的小程序后台配置了最低基础库为2.11.0，但是手机打开还是2.10.1

**Comment by malushashouzyc** [comment]
> 企业微信小程序，雷达图indicator name 英文和数字没有展示

单独判断华为手机，数字英文标点符号全部转成全角字符，在企业微信里目前可以显示出来，只不过样式方面字与字之间的距离会大一些

**Comment by AJbing** [comment]
> 

what r u talking about

**Comment by AJbing** [comment]
> > 企业微信小程序，雷达图indicator name 英文和数字没有展示
> 
> 单独判断华为手机，数字英文标点符号全部转成全角字符，在企业微信里目前可以显示出来，只不过样式方面字与字之间的距离会大一些

what r u tking ??????
