### ISSUE TITLE
`tooltip`无法修改字体大小

### ISSUE THREAD

**Issue by TSjianjiao** [ecomfe/echarts-for-weixin#620]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
`tooltip`使用`formatter`后无法修改字体大小
```javascript
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'shadow'
            },
            textStyle: {
                // 无论值是多少 实际显示的字体还是默认大小
                fontSize: 666,
                // 其他设置有效 比如颜色
                color: '#f00'
            }
        },
```

### 预期效果：
能调整`tooltip`字体大小

### 实际效果：
无法调整`tooltip`字体大小

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题
- `echarts`使用的是当前最新的仓库版本，小程序库和开发者工具都是最新的

**Comment by Ovilia** [comment]
这个是 ECharts 的问题，请关注 https://github.com/apache/incubator-echarts/issues/12232
