### ISSUE TITLE
新版通过canvasToTempFilePath和saveImageToPhotosAlbum保存出来的图片是空白？

### ISSUE THREAD

**Issue by phoenixor** [ecomfe/echarts-for-weixin#621]
昨天更新的ec-charts文件夹，使用小程序最新canvas 2d画布，需求是把pie图保存成图片，使用了官方示例里面的代码。
![image](https://user-images.githubusercontent.com/6568115/76159535-a026bc00-615c-11ea-96cd-42b5969302a4.png)
![image](https://user-images.githubusercontent.com/6568115/76159539-ac127e00-615c-11ea-8f21-bdf5faf9419e.png)
![image](https://user-images.githubusercontent.com/6568115/76159544-ba609a00-615c-11ea-9848-b2163af2da76.png)
用户点击才保存，不存在图表未绘制完成的可能。
测试多次，保存出来的png图片都是一片空白

**Comment by Ovilia** [comment]
同 #623
