### ISSUE TITLE
小程序下，line使用dataZoom放大图表后无法显示虚线

### ISSUE THREAD

**Issue by JerryWangTdcy** [ecomfe/echarts-for-weixin#629]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
小程序下，line使用dataZoom放大图表，并且设置了两条虚线，无法正常显示虚线，放大缩小后，有时虚线可以看到虚线，但是会聚集到一起。无法正常显示

### 预期效果：
![image](https://user-images.githubusercontent.com/34759071/76682406-f9985a80-6636-11ea-9f9e-63d9aff049bb.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/34759071/76682413-0d43c100-6637-11ea-8857-c9521a7fd409.png)
在pc端配置的option显示效果正常
![image](https://user-images.githubusercontent.com/34759071/76682422-264c7200-6637-11ea-8abc-77771d5c30ed.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
提供一下配置项

**Comment by JerryWangTdcy** [comment]
您好，配置如下：
options = {
        grid: {
          x: 20,
          y: 20,
          x2: 20,
          y2: 50 //距离下边的距离
        },
        tooltip: {
          trigger: 'axis',
          formatter: function (params) {
            return params[0].name + "\n" + params[0].value + "℃";
          }
          
        },
        xAxis: {
          show: true,
          axisLine: {
            show: false
          },
          axisTick: {
            show: false
          },
          type: 'category',
          axisLabel: {
            textStyle: {
              fontSize: 12,
              color: '#999999'
            }
          },
          data: temperatureListX
        },
        yAxis: {
          type: 'value',
          scale: true,
          axisLabel: {
            formatter: '{value} ℃' //刻度标签的内容格式器，支持字符串模板和回调函数两种形式，按照自己需求设置
          },
          splitLine: {
            show: false
          }, //去除网格线
          axisLine: {
            show: false
          },
          axisTick: {
            show: false
          },
          show: false //隐藏y轴
        },
        dataZoom: [{
          type: 'inside',
          start: 15,
          end: 80
        }],
        series: [{
          data: temperatureListY,
          symbol: 'none', // 不显示折线点
          type: 'line',
          itemStyle: {
            normal: {
              lineStyle: { // 系列级个性化折线样式  
                width: 2,
                type: 'solid',
                color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                  offset: 0,
                  color: '#E50909'
                }, {
                  offset: 0.5,
                  color: '#E5E500'
                }, {
                  offset: 1,
                  color: '#56D600'
                }]), //线条渐变色  
              },
              label: {
                show: false,  // 不显示折线点数据
                color: '#999999',
                fontSize: 10,
                formatter: '{c}' + _temp
              }
            },
            emphasis: {
              color: 'red',
              lineStyle: { // 系列级个性化折线样式  
                width: 2,
                type: 'dotted',
                color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                  offset: 0,
                  color: '#E50909'
                }, {
                  offset: 0.5,
                  color: '#E5E500'
                }, {
                  offset: 1,
                  color: '#56D600'
                }])
              }
            }

          }, //线条样式
          smooth: true,
          markLine: {
            symbol: 'none', //去掉箭头
            itemStyle: {
              normal: {
                lineStyle: {
                  color: '#000'
                },
                label: {
                  fontSize: 10,
                  formatter: function (params) {
                    return params.name
                  }
                  // formatter: ' 37' + _temp
                }
              }
            },
            data: [
              { yAxis: '35', name: '正常' },
              { yAxis: '37', name: '偏热' }
            ]
          }
        }]
不好意思，有些不重要的变量我没有修改。

**Comment by Ovilia** [comment]
请提供直接能运行的代码例子，给的里面有些变量没有定义……
