### ISSUE TITLE
雷达图里面的legend图例组件点击后报错，无法顺利地消失或展现

### ISSUE THREAD

**Issue by ramwin** [ecomfe/echarts-for-weixin#63]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在官方例子的radar图里面添加配置
    ```
    legend: {
      data: ['预算', '开销']
    },
    ```
雷达图上出现了预算和开销的图例，但是点击后报错

### 预期效果：
第一次点击预算，预算图线消失，第二次点击预算，预算的图片又展示
（如有需要请提供预期的图）

### 实际效果：
第一次点击，多了一条预算的曲线，动画效果结束后，和原有的预算曲线重叠。
第二次点击，console里面报错，没有效果
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
