### ISSUE TITLE
小程序报错Failed to set 'font' on 'CanvasContext': invalid format."

### ISSUE THREAD

**Issue by llllllllr** [ecomfe/echarts-for-weixin#630]
### 简单描述问题：
正常使用echarts，图表正常渲染，但是小程序报错 Failed to set 'font' on 'CanvasContext': invalid format."

### 复现环境：
- [x] 在微信开发工具中存在该问题
已根据以下网址的提示修改了echats.js,但是并没有效果
<https://developers.weixin.qq.com/community/develop/doc/0008c88a5207d0c9dc684e53d51800>

**Comment by Ovilia** [comment]
配置项贴一下
