### ISSUE TITLE
用2d模式出来的图表会比较模糊有什么解决办法吗

### ISSUE THREAD

**Issue by yah0130** [ecomfe/echarts-for-weixin#633]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
2d模式出来的图表会比较模糊

### 预期效果：
与老模式一样清晰
（如有需要请提供预期的图）

### 实际效果：
比较模糊
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by MsEcho** [comment]
echarts官方文档里还有一个devicePixelRatio像素比的参数，加上应该就可以了，echarts.init(canvas, null, { width, height, devicePixelRatio: dpr })

**Comment by yah0130** [comment]
嗯解决了就是没传这个参数谢谢了

**Comment by wdzjpt** [comment]
![image](https://user-images.githubusercontent.com/52905288/80450615-774cc700-8954-11ea-97f8-3c9126d323b9.png)
请问一下这个为什么还是有提示切换2d   是哪里需要修改或设置吗？谢谢

**Comment by Ovilia** [comment]
@wdzjpt https://github.com/ecomfe/echarts-for-weixin#canvas-2d-%E7%89%88%E6%9C%AC%E8%A6%81%E6%B1%82 检查下基础库版本
