### ISSUE TITLE
toolTip里怎么加上事件按钮？

### ISSUE THREAD

**Issue by peng20017** [ecomfe/echarts-for-weixin#634]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
需要在toolTip里加入一个自定义按按钮，怎么传入dom，并实现点击事件

### 预期效果：
？？？
（如
![2cac2c132fe6ecf0f11221acb3fab5d](https://user-images.githubusercontent.com/32953539/77129922-c7508800-6a90-11ea-82b3-ab46cd27789b.jpg)

### 实际效果：
微信小程序内不能传入dom元素；
但是官放网站上 renderMode属性：浮层的渲染模式，默认以 'html 即额外的 DOM 节点展示 tooltip；此外还可以设置为 'richText' 表示以富文本的形式渲染，渲染的结果在图表对应的 Canvas 中（目前 SVG 尚未支持富文本），这对于一些没有 DOM 的环境（如微信小程序）有更好的支持，但是不能在小程序内实现。
### 复现环境：
微信开发工具v1.02.1911180

**Comment by peng20017** [comment]
我用了cover-view 定时实现了效果，但是还是想问一下，echart-for-weixin 支持这种方式吗？

**Comment by Ovilia** [comment]
不支持，因为没有额外的 DOM 节点

**Comment by peng20017** [comment]
了解。
