### ISSUE TITLE
能不能出一个支付宝/钉钉小程序版本的echarts

### ISSUE THREAD

**Issue by maplelover** [ecomfe/echarts-for-weixin#636]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
希望可出一个支付宝/钉钉小程序版本的echarts
具体思路可以参考，https://www.yuque.com/antv/blog/bg9sxf

**Comment by Ovilia** [comment]
与本项目无关，感兴趣的话可以自己参考本项目支持。
