### ISSUE TITLE
关系图中节点使用图像报错Image is not defined

### ISSUE THREAD

**Issue by dreamchen** [ecomfe/echarts-for-weixin#637]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
使用关系图时，data中的symbol使用图像模式（symbol: 'image://https://www.echartsjs.com/zh/images/logo.png',)，报错（Image is not defined）
已尝试下载最新包，在pc浏览器直接使用无问题，小程序内依然存在该问题，已排除图片访问域名问题

### 预期效果：
能够正常显示图像：
![image](https://user-images.githubusercontent.com/4631721/77223208-6068c700-6b95-11ea-8a2b-5ea71063eaa7.png)

### 实际效果：
无法正常运行：
![image](https://user-images.githubusercontent.com/4631721/77223228-7aa2a500-6b95-11ea-96eb-4d209ff80339.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by dreamchen** [comment]
查看源码发现如下情况，echart使用额H5默认元素，这些元素在小程序内是没有的。

**Comment by Ovilia** [comment]
目前不支持图片

**Comment by jthivan** [comment]
> 目前不支持图片

@Ovilia 有计划在微信小程序上支持图片么，我看有不少人提这个问题呢。

**Comment by Nighting-Liu** [comment]
修改echarts.js中function tn(t,e,i,n,o)中的new Image -> i.__zr.dom.canvasNode.createImage()即可
