### ISSUE TITLE
关系图快点支持图片吧，需求很大

### ISSUE THREAD

**Issue by seventsing** [ecomfe/echarts-for-weixin#638]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
欢迎提 pr

**Comment by zhiyouai** [comment]
> 欢迎提 pr

这个问题我试了一种方法，从现象看是可以解决问题。出错的原因是echarts里调用了new Image获取image对象，我在获取canvas后通过createImage方法替换new Image，就可以展示图片了

**Comment by Ovilia** [comment]
@zhiyouai 可以贴一下解决方法吗？

**Comment by zhiyouai** [comment]
> @zhiyouai 可以贴一下解决方法吗？

我针对的是小程序基础库2.9.0以上版本，在echarts.js中增加setCanvas方法，用于赋值canvas对象。在ec-canvas.js文件，获取到canvas之后，调用setCanvas进行赋值
![image](https://user-images.githubusercontent.com/12656103/84646143-39235b00-af34-11ea-9b60-10bb669a07f4.png)，在echarts.js原来调用new Image方法的地方，用canvas.createImage替换
![image](https://user-images.githubusercontent.com/12656103/84646320-80a9e700-af34-11ea-8770-2a3fb607a05c.png)这个mCanvas就是接收第一步赋值后的变量

**Comment by zlLotus** [comment]
@zhiyouai 可以提供下完整的文件吗

**Comment by songsgroup** [comment]
> @zhiyouai 可以提供下完整的文件吗

同问

**Comment by Nighting-Liu** [comment]
修改echarts.js中function tn(t,e,i,n,o)中的new Image -> i.__zr.dom.canvasNode.createImage()即可

**Comment by yinlianggood** [comment]
22/08/30 
最新修改方法，已尝试可行！
修改loadImage方法，如下：
第一步：
![image](https://user-images.githubusercontent.com/10203628/187439857-f8dfbe0d-2068-4792-b60c-5fc888cf0073.png)

第二步：
![image](https://user-images.githubusercontent.com/10203628/187440340-e1141c04-e752-4b55-b390-1a50efea0de8.png)

**Comment by chdtyzhy** [comment]
<img width="889" alt="image" src="https://github.com/ecomfe/echarts-for-weixin/assets/7151873/0c37b008-8602-4c5b-86af-103594ef2d3d">
@yinlianggood
