### ISSUE TITLE
symbol 使用自定义图片问题

### ISSUE THREAD

**Issue by qqqdu** [ecomfe/echarts-for-weixin#64]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
我想在柱形图中的 `markPoint` 配置项中将 `symbol` 设置为自

定义图片。
### 预期效果：
图片显示成功

### 实际效果：
如果使用文档中提出的  `'image://url'` 方式  小程序开发者工具报错，`Image is not defined;` 因为小程序并没有Image方法，将 `url` 改为 `base64` 依然报错。
如果使用文档中的 `'svg://url'` 图片依然无法加载。

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该

**Comment by Ovilia** [comment]
目前不支持图片

**Comment by wangyangyong** [comment]
请问什么是侯能支持图片

**Comment by gamijin0** [comment]
请问小程序中的echart还是不支持使用外部图片吗? 比如我想用自己的图片来作为graph中节点的背景,是不是做不到? (Image is not defined;)

**Comment by NameLi** [comment]
可以用svg，亲测有效

**Comment by gailufeng** [comment]
> 可以用svg，亲测有效

请教怎么用的，我用svg也报错了：Cannot read property 'createElementNS' of undefined;at pages/echarts/echarts onReady function;at SelectorQuery callback function
TypeError: Cannot read property 'createElementNS' of undefined

**Comment by LaneMa** [comment]
> > 可以用svg，亲测有效
> 
> 请教怎么用的，我用svg也报错了：Cannot read property 'createElementNS' of undefined;at pages/echarts/echarts onReady function;at SelectorQuery callback function
> TypeError: Cannot read property 'createElementNS' of undefined

哥们成功了吗？请教怎么做

**Comment by newstarao** [comment]
> > > 可以用svg，亲测有效
> > 
> > 
> > 请教怎么用的，我用svg也报错了：Cannot read property 'createElementNS' of undefined;at pages/echarts/echarts onReady function;at SelectorQuery callback function
> > TypeError: Cannot read property 'createElementNS' of undefined
> 
> 哥们成功了吗？请教怎么做

不能用base64，只能用svg的path，如下所示：
     symbol: 'path://M40.02-99c2.07,1.21,4.26,2.25,6.19,3.66c5.94,4.34,8.23,12.57,4.95,19.79 c-3.21,7.08-6.82,14.03-10.86,20.67c-2.17,3.56-1.25,5.38,1.99,6.36c2.94,0.89,6.36,1.91,9.15,1.21c5.51-1.4,8.33,1.23,10.66,5.29 c4.71,8.22,9.72,16.29,13.84,24.8C81.06-6.65,89,0.4,99.56,5.17C109.82,9.8,120,14.7,129.85,20.15c4.72,2.61,9.09,6.37,10.24,12.97 c-2.89-1.93-5.2-3.75-7.78-5.04c-0.99-0.5-2.6,0.22-4.83,0.5c-5.36-9.35-16.8-9.4-26.74-12.62C91.68,13.04,81.82,11.37,75.66,3 c-5.98-8.13-11.61-16.52-17.4-24.79c-0.46-0.66-0.98-1.27-1.66-2.16c-3.21,7.75-6.78,15-9.12,22.63c-1.15,3.76-0.64,8.37,0.26,12.33 c0.81,3.59,3.01,6.92,4.87,10.22c6.73,11.95,2.41,22.89-2.91,33.75c-0.35,0.72-0.86,1.43-1.46,1.97 c-7.11,6.38-14.48,12.5-21.24,19.22c-2.08,2.07-3.1,5.7-3.62,8.77c-1.92,11.44-3.81,22.92-4.93,34.46 c-0.5,5.16,1.06,10.49,1.28,15.75c0.23,5.7,0.39,11.47-0.15,17.13c-1.15,12.11-2.83,24.17-4.11,36.27c-0.18,1.72,0.8,3.53,1.13,5.33 c0.88,4.76-0.22,6.23-4.71,5.17c-4.53-1.06-8.86-2.94-14.27-4.8c1.98-1.62,2.84-2.83,3.94-3.12c5.42-1.44,7-5.2,6.39-10.23 c-1.39-11.39-3.15-22.73-4.24-34.14c-0.53-5.56,0.16-11.23,0.24-16.85c0.06-4.49,0.01-8.97,0.01-14.72 c-2.79,1.53-5.2,2.27-6.79,3.83c-4.26,4.19-8.39,8.56-12.11,13.22c-1.55,1.95-2.19,4.76-2.79,7.29c-0.47,1.99,0.6,5.02-0.48,6.05 c-2.17,2.08-5.2,3.79-8.13,4.38c-3.61,0.73-7.49,0.18-12.26,0.18c6.34-8.69,11.91-16.11,17.22-23.71c3.29-4.71,6.23-9.67,9.24-14.58 c2.15-3.5,3.76-7.4,6.3-10.57c5.38-6.73,6.74-14.28,6.72-22.64C0.88,68.3,1.36,57.91,2.26,47.58c0.69-7.85,2.15-15.67,3.7-23.41 c0.77-3.83,2.89-7.39,3.72-11.22c1.83-8.4-1.9-16-4.38-23.95C2.96-5.34-0.31,0.12-1.5,6c-1.96,9.72-7.34,17.44-12.26,25.57 c-4.39,7.25-8.79,14.52-12.75,22.01c-2.64,5-4.5,10.41-6.83,15.92c-4.82-5.28-4.65-10.59-0.94-16.97 C-21.4,30.4-12.08,6.78-6.17-18.12c1.4-5.88,1.24-12.11,2.23-18.12c1.2-7.27,4.15-9.56,11.39-9.69c8.65-0.14,13.86-4.77,14.48-13.51 c0.35-5.01,0.16-10.11-0.28-15.12c-0.82-9.3,2.49-16.57,10.17-21.69c2.08-1.39,4.78-1.87,7.2-2.76C39.35-99,39.69-99,40.02-99z'

**Comment by LittleFox99** [comment]
使用svg path 但是外部图片颜色就消失了

**Comment by Nighting-Liu** [comment]
修改echarts.js中function tn(t,e,i,n,o)中的new Image -> i.__zr.dom.canvasNode.createImage()即可

**Comment by chenyinkai** [comment]
@Nighting-Liu 大哥厉害了。`5.1.2`版本中可修改 `new Image` 为 `n.__zr.dom.canvasNode.createImage()` ;
