### ISSUE TITLE
echarts图表在微信小程序中显示不清晰

### ISSUE THREAD

**Issue by myGitFang** [ecomfe/echarts-for-weixin#640]
## 简单描述问题：
代码和数据都没有问题，做了许多种可能情况的调试都不清晰

### 预期效果：
（如有需要请提供预期的图）
效果图是这样的
![bc](https://user-images.githubusercontent.com/44764720/77405283-e5e6b400-6ded-11ea-849c-be511bc3474f.png)

### 实际效果：
![af](https://user-images.githubusercontent.com/44764720/77405201-ce0f3000-6ded-11ea-9ecb-fa230f8615d6.png)

（如有需要请提供截图）

### 复现环境：
   在微信开发工具中不存在该问题
   在真机上存在

**Comment by huoyanfx** [comment]
出现了同样的问题,没有以前的清晰有点模糊....新版Canvas 2d会这样, 旧版的测试没有这个问题...但是旧版又有层级问题

**Comment by huoyanfx** [comment]
新版Canvas 2d  今天又在安卓真机上测试...有些文字显示不出来....ios真机是有点模糊

**Comment by huoyanfx** [comment]
![微信截图_20200325200811](https://user-images.githubusercontent.com/37257338/77535264-4f8dbd80-6ed5-11ea-8686-95f081db05c7.png)

**Comment by vickey-chen** [comment]
给一下initCanvas的使用方式。

需要传入dpr，在文档有写，例如：
function initChart(canvas, width, height, **dpr**) {
  chart = echarts.init(canvas, null, {
    width: width,
    height: height,
    **devicePixelRatio: dpr // new**
  });
  canvas.setChart(chart);
}

**Comment by myGitFang** [comment]
@huoyanfx 这个我本来就写了的，但是依然没用

**Comment by Ovilia** [comment]
看一下传入的 dpr 是否是 2

**Comment by myGitFang** [comment]
> 看一下预期的dpr是否是2

**Comment by myGitFang** [comment]
> 看一下预期的dpr是否是2

一直是 2

**Comment by myGitFang** [comment]
> 给一下initCanvas的使用方式。
> 
> 需要初始化dpr，在文档中写，例如：
> function initChart（canvas，width，height，**dpr**）{
> chart = echarts.init（canvas，null，{
> width：width，
> height：height，
> **devicePixelRatio：dpr // new**
> } ）;
> canvas.setChart（chart）;
> }

我写的和你这个是一样的

**Comment by aiyayacxl** [comment]
这个问题有解决方法吗
