### ISSUE TITLE
把option传到二级页面再生成新的echart,报错,circle dependency,循环引用

### ISSUE THREAD

**Issue by curiousbabyMz** [ecomfe/echarts-for-weixin#641]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息
首页生成echart图表,把option传到二级页面,生成新的echart图表,就报错了
提示循环引用Circle dependency may exists;at SelectorQuery callback function

### 简单描述问题：
把option传到二级页面再生成新的echart,报错,circle dependency,循环引用

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by curiousbabyMz** [comment]
使用示例的配置option也是如此

**Comment by curiousbabyMz** [comment]
@Ovilia 麻烦看到了帮忙解决一下

**Comment by Ovilia** [comment]
怎么传的？贴一下代码

**Comment by curiousbabyMz** [comment]
@Ovilia 谢谢，更新工具后，问题消失了；我是通过storageSync存取的
