### ISSUE TITLE
折线图<ec-canvas>是type="2d"并且<ec-canvas>宽度超过1360px的时候，并且导致Android系统微信闪退，iOS系统无法渲染

### ISSUE THREAD

**Issue by WangMaoling** [ecomfe/echarts-for-weixin#645]
由于业务需要需要用ec-canvas画出趋势变化图并且可以左右滑动来查看所以的数据，所以ec-canvas宽度需要根据数据量动态计算，数据量过大宽度超过1360px时候就会出现标题描述现象。
由于Android手机直接闪退所以就在iOS手机测试：
下图是1360px的数据显示情况
![image](https://user-images.githubusercontent.com/23271322/78316107-68f7cf00-7591-11ea-962c-13f91f17f96d.png)
![image](https://user-images.githubusercontent.com/23271322/78316156-89278e00-7591-11ea-9b18-4c3c66653d08.png)
数据是可以拖动的，可以拖到最后看下：
![image](https://user-images.githubusercontent.com/23271322/78316178-9a709a80-7591-11ea-9b60-7d0303783b6d.png)
但是修改宽度为1400px的时候直接无法渲染了下图ios系统截图：
![image](https://user-images.githubusercontent.com/23271322/78316225-bbd18680-7591-11ea-83c5-4a3cefcbe99c.png)
<view class="body">
  <view class="jiluBox">
    <scroll-view class="ft-box"  scroll-x="true">
    
      <view style="width:1360px" class="container"> 
        <ec-canvas type="2d" id="mychart-pef" canvas-id="mychart-pef" ec="{{ ec_pef }}"></ec-canvas>
      </view>
    </scroll-view>
  </view>
</view>

请问有什么解决办法，用老版本的，新版本就出现这样问题了，小程序引入新版本是为了解决老版本ec-canvas层级过高问题的，但是现在出现这个问题...求大神帮下忙

**Comment by hyq1860** [comment]
这个问题看了微信官方说明,在画布宽高过大的时候,会崩溃,可以尝试设置小一点的画布

**Comment by WangMaoling** [comment]
新版本这个问题不适用业务，只能用旧版本了（完毕）
