### ISSUE TITLE
小程序端支持chart.resize() 吗？

### ISSUE THREAD

**Issue by deFang** [ecomfe/echarts-for-weixin#646]
请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

设置了将ec-canvas默认隐藏，需要时再弹出，但弹出时会获取不到width, height，搜索知道需要再resize一下，但是试了并没有效果，dom的width,height依然是0.

**Comment by Ovilia** [comment]
"需要时再弹出" 你需要在 setTimeout 里再初始化图表

**Comment by deFang** [comment]
```
 <view class="container" hidden="{{true}}">
    <ec-canvas id="mychart-dom-bar" canvas-id="mychart-bar" ec="{{ ec }}" ></ec-canvas>
</view>
```
上面是代码，默认状态是hidden，此时ecComponent.init获得的width，height都是0；
在将hidden设置为false之后，在手动调用chartInstance.resize()，内部的获取的width,height依然是0，但如果显示的调用chartInstance.resize({ width: 300, height: 300 }) 就能正常显示出图，所以为什么chartInstance不能自动获取到对应模块的width,height呢?

**Comment by Ovilia** [comment]
说了要加个 setTimeout……
