### ISSUE TITLE
真机echarts提示无法加载插件

### ISSUE THREAD

**Issue by changer-wang** [ecomfe/echarts-for-weixin#648]
### 简单描述问题：
真机echarts显示无法加载插件
### 实际效果：
![WechatIMG1](https://user-images.githubusercontent.com/32571221/78766624-1452ba80-79bc-11ea-8e2e-27eabc866e97.jpeg)

### 复现环境：
真机echarts能正常加载, 但是会在图表中间提示无法加载插件

**Comment by changer-wang** [comment]
基础库: 2.10.4

微信: 7.0.13

安卓: 9

内核版本:4.9.112

手机: OPPO K3

**Comment by Ovilia** [comment]
ECharts 并没有使用「插件」，不知道这个错误是不是你自己项目里其他地方引起的呢？

**Comment by changer-wang** [comment]
> ECharts并没有使用“插件”，不知道这个错误是不是你自己项目里其他地方引起的呢？

并不是,我用同样的手机查看官方的demo也会有同样的问题

**Comment by changer-wang** [comment]
> ECharts并没有使用“插件”，不知道这个错误是不是你自己项目里其他地方引起的呢？

[
![image](https://user-images.githubusercontent.com/32571221/79710882-e7c26b00-82f8-11ea-8ac7-fa751e5afa14.png)
](url)
请看 我将官方的柱状图bar数据替换成这个就会出现这种问题

**Comment by changer-wang** [comment]
> ECharts 并没有使用「插件」，不知道这个错误是不是你自己项目里其他地方引起的呢？

具体替换代码如下: var option = {
    xAxis: [
      {
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        axisLine: {
          lineStyle: {
            color:'#333',
          }
        },
        axisLabel: {
          textStyle: {
            color: '#333'
          }
        }
      }
    ],
    yAxis: [
      {
        type: 'value',
        axisLabel : {
          textStyle: {
            color: '#fff'
          }
        },
        axisLine: {
          lineStyle: {
            color:'#333',
          }
        },
      },
    ],
    series: [
      {
        type: 'bar',
        barWidth: '60%',
        data: [10, 52, 200, 334, 390, 330, 220],
        itemStyle: {
          normal: {
            label: {
              show: true,
              position: 'top',
              textStyle: {
                color: '#e66a6b',
                fontSize: 16,
                fontWeight: 'bold'
              }
            },
          }
        }
      }
    ]
  }

**Comment by changer-wang** [comment]
> ECharts 并没有使用「插件」，不知道这个错误是不是你自己项目里其他地方引起的呢？

非常奇怪哦!demo中的数据直接打开没有问题,可我更换了option里面的数据就会提示这个错误!
![21587354085_ pic](https://user-images.githubusercontent.com/32571221/79711949-f3fbf780-82fb-11ea-8057-d34ef1e9fa67.jpg)
![31587354085_ pic](https://user-images.githubusercontent.com/32571221/79711956-f8c0ab80-82fb-11ea-950f-1efd5b94db88.jpg)
替换的数据为:
`  var option = {
    series: [
        {
            type: 'pie',
            radius: ['50%', '70%'],
            data: [
                {value: 335, name: '直接访问'},
                {value: 310, name: '邮件营销'},
                {value: 234, name: '联盟广告'},
                {value: 135, name: '视频广告'},
                {value: 1548, name: '搜索引擎'}
            ]
        }
    ]
};`

**Comment by huaxiaocheng** [comment]
![未标题-1](https://user-images.githubusercontent.com/58205179/80081404-7a773a00-8585-11ea-9f2b-40a5c4a0e1ee.jpg)
我也遇到了这个问题，目前所有测试的机型中，只有左边这个（手机型号：ZTE BV0720，版本号：BV0720V2.0B04，Android版本6.0，微信版本 7.0.10，基础库：2.10.2）出现了这个问题，并且z-index也有问题；其他都像右边一样，正常显示。

**Comment by Ovilia** [comment]
无法复现哦
