### ISSUE TITLE
安卓手机echarts（旧版本）折线图出现样式显示混乱，文字大小以及颜色错乱等

### ISSUE THREAD

**Issue by WangMaoling** [ecomfe/echarts-for-weixin#649]
所有安卓手机echarts（旧版本）折线图出现样式显示混乱，新版本未发现此问题但新版本有个问题不适用业务需求，故只能选用旧版本。请各位大佬看看到底哪里出问题了
正常效果图：
![image](https://user-images.githubusercontent.com/23271322/78851258-f2a11400-7a4b-11ea-902d-48f38522900e.png)
异常图(华为p30截图，这个手机效果看着还算好的)：
![image](https://user-images.githubusercontent.com/23271322/78851308-106e7900-7a4c-11ea-9eb0-4e3189197dad.png)
![image](https://user-images.githubusercontent.com/23271322/78851341-23814900-7a4c-11ea-8e45-f44fba6c3f38.png)
![image](https://user-images.githubusercontent.com/23271322/78851418-54617e00-7a4c-11ea-8e86-8aea40db6d81.png)
异常图（小米8 MIUI 11.0.6 截图，效果简直不能看）
![image](https://user-images.githubusercontent.com/23271322/78851886-832c2400-7a4d-11ea-9995-36c640d2daf0.png)
以下是具体配置项：
               option ={
			backgroundColor:'#fff',
			title: [{
				text: ' \n日期\n日变异率\n时间',
				top: -25,
				left: 0,
				textStyle: {
					lineHeight: 20,
					fontSize: 10,
					color: '#606266',
					fontWeight: 'normal',
					formatter: function (value) {
						return '{table|' + value + '}';
					},
					rich: {
						table: {
							align: 'center'
						}
					}
				}
			}],

			//整个图表的上下左右边距
			grid: {
				left: 65,//图的x,y轴象限内有效区域距离，也就是y轴刻度区域的宽 65
				right: 1,
				bottom: 1 
			},

			xAxis: [{
				type: 'category',
				z:1,
				data: ['早','晚','早','晚','早','晚'],
				position: 'top',
				offset: 0,
				splitArea: {
					show: false
				},
				axisTick: {
					show: false
				},
				splitLine: {
					show: false,
				},
				axisTick: {
					length: 179,
					lineStyle:{
						width:0.2,
						color:'#606266'
					}
				},
				axisLabel:{
					interval: 0,
					textStyle: {
						fontSize: 10,
					},
					margin: 5,
				},
				axisLine:{
					show:false,
					lineStyle:{
						color: '#606266',
					}
				},
			},
			{
				type: 'category',
				z:1,
				data: [0.23,0.11,0.45],//变异率
				offset: 20,
				position: 'top',
				splitArea: {
					show: false
				},
				axisTick: {
					show: false
				},
				axisLabel: {
					interval: 0,
					formatter: function (value, index) {
						// 格式化成月/日，只在第一个刻度显示年份
						if(value){
							let one = value.split(',')[0]*100;
							return one.toFixed(0)+'%';
						}else{
							return '';
						}
				},
					textStyle: {
						fontSize: 10,
						color: function (value, index) {
							let arr = value.split(',');
							return arr[1] == 0 ? '#1FDE87' : '#FFA230';
						}
					},
					margin: 5,
				},
				splitLine: {
					show: false,
				},
				axisLine:{
					show:false,
					lineStyle:{ 
						color: '#606266',
					}
				},
				
			},
			{
				type: 'category',
				z:1,
				data: ['02/01','02/02','02/03'],//日期
				position: 'top',
				offset: 40,
				splitArea: {
					show: false
				},
				splitLine: {
					show: false,
				},
				axisLabel: {
					interval: 0,
					textStyle: {
						fontSize: 10,
					},
					margin: 5,
				},
				axisTick: {
					show: true,
					length: 300, 
					lineStyle:{
						width:0.2,
						color:"#606266"
					}
				},
				axisLine:{
					show:false,
					lineStyle:{ 
						color: '#606266',
					}
				},
			
			}
			],
			yAxis: [
			{
				axisLabel: {
					showMinLabel: false,
					showMaxLabel: false,
					textStyle: {
						fontSize: 10,
					},
				},
				type: 'value',
				z:3,
				splitLine: {
					show: true,
					lineStyle: {
						color: '#979797',
						width: 0.5,
					}
				},
				axisTick: {
					show: false
				},
				axisLine: {
					show:false,
					lineStyle: {
						color: '#606266',
						width: 0.5 
					}
				}
			},
			{
				name: '峰值流速(PEF)L/min',
				position: 'left',
				nameLocation: 'center',
				nameGap: 45, //与轴线间距
				nameTextStyle: { //文字样式
					fontSize: '12'
				},
				axisLine: {
					lineStyle: {
						color: '#606266'
					}
				},
			},
			],
			series: [
				{
					name: '',
					type: 'line',
					z:1,
					stack: '',
					animation: false,
					symbol: 'circle',
					symbolSize: 4,
					itemStyle: {
						normal: {
							color: '#0092f6',
							lineStyle: {
								color: "#0092f6",
								width:1
							},
						}
					},
					xAxisIndex: 0,
					data: [356,456,380,470,501,490],//具体数据
				},
				//颜色区域划分
				{
					type: 'line',
					markArea: {
						silent: true,
						z:-10,
						data: [
							[{
								// name: '危险',
								yAxis: 0,
								itemStyle: {
									color: '#FAE3E0',
									opacity: 1
								},
							}, {
								yAxis: 300
							}],
							[{
								// name: '警告',
								yAxis: 300,
								itemStyle: {
									color: '#FFEECB',
									opacity: 1
								},
							}, {
								yAxis: 450,
							}],
							[{
								// name: '正常',
								yAxis: 450,
								itemStyle: {
									color: '#C1EFDA',
									opacity: 1
								},
							}, {
								yAxis: 10000,
							}],
						]
					}
				}
			],
			graphic:[]//设置上面的横线部分，计算出来的数据
		};

**Comment by Ovilia** [comment]
使用一下新版本呢？因为安卓上的很多渲染问题能用新版本修复

**Comment by Ovilia** [comment]
旧版本应该没法解决这些问题，是小程序 canvas 旧版本有很多渲染问题。
