### ISSUE TITLE
安卓端和ios端显示颜色

### ISSUE THREAD

**Issue by biggerthan** [ecomfe/echarts-for-weixin#652]
### 简单描述问题：
安卓端和ios端显示颜色不一样, ios端是符合预期的, 安卓端显示感觉有透明度

### 预期效果：
![ios](https://user-images.githubusercontent.com/17694117/79088215-905e5100-7d74-11ea-8ea0-03d051b256c3.png)

### 实际效果：
安卓端
![android](https://user-images.githubusercontent.com/17694117/79088213-8dfbf700-7d74-11ea-8425-e722defc653a.jpeg)
iOS端
![ios](https://user-images.githubusercontent.com/17694117/79088215-905e5100-7d74-11ea-8ea0-03d051b256c3.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by biggerthan** [comment]
排除下来是visualMap的问题, 图元的颜色是对的, 映射在曲线上的不对

**Comment by Ovilia** [comment]
请提供一下源码？
