### ISSUE TITLE
微信小程序使用echarts,模拟地图迁徙报错failed to excute drawimage on CanvasRenseringContext2D

### ISSUE THREAD

**Issue by xujaibo** [ecomfe/echarts-for-weixin#654]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [X] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [X] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
微信开发者工具报错failed to excute drawimage on CanvasRenseringContext2D the provide value is......,使用普通地图可以显示,但是用到下面的链接,类似地图迁徙的例子就会报错,在vue中使用可以出来的,小程序不行
### 预期效果：
![echarts1](https://user-images.githubusercontent.com/45301701/79419276-1aaeeb00-7fe9-11ea-8afe-c0b7b869cb78.png)

官方实例地址:https://gallery.echartsjs.com/editor.html?c=x3jmr2Aqmh

（如有需要请提供预期的图）

### 实际效果：
![echarts2](https://user-images.githubusercontent.com/45301701/79419288-20a4cc00-7fe9-11ea-89b6-670e53fbe0ba.png)

微信开发者工具报错failed to excute drawimage on CanvasRenseringContext2D,使用普通地图可以显示,但是用到上面类似地图迁徙的例子就会报错,在vue中使用可以出来的,小程序不行

（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题

**Comment by Ovilia** [comment]
不支持图片

**Comment by xujaibo** [comment]
> 不支持图片

请问一下这个不支持图片是什么意思,是这个迁徙的echarts中使用到了图片,所以才导致报错,无法使用的吗?

**Comment by Ovilia** [comment]
看起来是的
