### ISSUE TITLE
原生微信小程序开发中，二次封装的ec-canvas标签在组件，当组件引用第二次，不显示问题

### ISSUE THREAD

**Issue by xmt1997** [ecomfe/echarts-for-weixin#655]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
微信小程序发开阶段，主页有四个标签页，每个标签页的内容为一个组件，这个组件包含ec-canvas标签和其他内容，主页引用时，在第一个标签页可显示ec-canvas和组件内的其他内容，在其他标签页不可显示ec-canvas，但可以显示组件的其他内容。请教一下这个是怎么回事？谢谢

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
应该是容器宽高的问题，如果组件是在第一个标签页展示的时候初始化，那么其他几个图表的容器是没有宽高的，解决办法参考 lazyLoad 的例子
