### ISSUE TITLE
地图大小在不同真机显示不一致

### ISSUE THREAD

**Issue by z729063706** [ecomfe/echarts-for-weixin#656]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？
在[](https://github.com/piscium2010/coronavirus-map)项目中
地图大小在不同真机不一致
已经对该项目的样式文件进行了修改
并强制启用旧版绘图
但也无法解决
### 预期效果：
？？？
（如有需要请提供预期的图）

![Snipaste_2020-04-23_09-18-37](https://user-images.githubusercontent.com/32958288/80048723-8f32de00-8543-11ea-90f2-332b925d4bd1.png)
### 实际效果：
？？？
（如有需要请提供截图）
两部小米9，一部正常一部不正常，不正常的系统为开发版系统
华为Nova3 显示不正常
![QQ图片20200423092000](https://user-images.githubusercontent.com/32958288/80048746-a07bea80-8543-11ea-9454-767a752e3d59.jpg)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
新旧版都有这个问题吗？

**Comment by z729063706** [comment]
> 新旧版都有这个问题吗？

是的，估计是手机系统底层的问题

**Comment by Ovilia** [comment]
建议手动设置 dpr？

**Comment by z729063706** [comment]
> 建议手动设置 dpr？
不好使的，改成2就更没法看了
可能是安卓10.0的问题

**Comment by Ovilia** [comment]
我这边没法提供更多帮助，看看是不是需要关闭 issue？
