### ISSUE TITLE
通过触发组件方法初始化怎么调用

### ISSUE THREAD

**Issue by liuqi888** [ecomfe/echarts-for-weixin#657]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by liuqi888** [comment]
this.triggerEvent('init', {
            canvas: canvas,
            width: res.width,
            height: res.height,
            canvasDpr: canvasDpr // 增加了dpr，可方便外面echarts.init
          });
利用这个方法初始化怎么调用呢？？

**Comment by liuqi888** [comment]
wxml：
<ec-canvas bindinit="init" id="mychart-dom-line" canvas-id="mychart-line" ec="{{ ec }}"></ec-canvas>
js：
 init:initChart
直接改官方demo，改成这样之后不能初始化了。麻烦看一下。

**Comment by Ovilia** [comment]
你这个 triggerEvent 里的 `canvas` 是怎么获得的？

**Comment by Ovilia** [comment]
请参考例子实现，如果是要延迟加载，参考延迟加载的例子
