### ISSUE TITLE
部分安卓手机不能渲染出图表

### ISSUE THREAD

**Issue by Evan-acg** [ecomfe/echarts-for-weixin#658]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：
手机品牌：华为 荣耀
系统：安卓版本8.0.0 EMUI8.0.0
微信版本：V7.0.13

### 简单描述问题：
同样的代码片断，在大部分手机上可以正常的生成图表并渲染显示，但在部分手机上却无法渲染显示

### 预期效果：

![image](https://user-images.githubusercontent.com/20313866/80185038-457aee00-863e-11ea-853b-44877eb7e17a.png)

### 实际效果：

![image](https://user-images.githubusercontent.com/20313866/80185054-4ca1fc00-863e-11ea-84af-c6ae7fdd1e51.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by fang635295364** [comment]
又出现多次进入图表不显示的问题么？

**Comment by Evan-acg** [comment]
应该不是你说的这个问题，IOS上正常，大部分的安卓机也是正常的，只有少数几台没有渲染出来，也没有报错什么，所以搞的我各种头疼，都不知道怎么排查。

**Comment by fang635295364** [comment]
我现在出现多次进去不显示的问题 不知道为什么

**Comment by fang635295364** [comment]
就第一次进入显示

**Comment by Evan-acg** [comment]
会不会是配置生成项的问题。

**Comment by fang635295364** [comment]
我贴了代码 问官方 也没有人回我。。

**Comment by Ovilia** [comment]
@Evan-acg 这个是图表容器没有宽度高度吧？需要用 css 写好宽度高度

**Comment by Evan-acg** [comment]
@Ovilia 如果是高度的问题的话，这个不合理啊，数据是根据服务器返回的，里面的bar的数量也是动态的，那么这个时候我设置死了高度的话，如果返回的数量多，那是不是全挤到一块了么？我总不能根据返回数据的高度，手动的去设置父容器的高度吧？就不能让父容器被内容撑开么？

**Comment by Ovilia** [comment]
canvas 的大小肯定是需要设置才能有的，没法自动“撑开”，因为显然没法根据内容画了哪些区域决定 canvas 的大小，所以容器的大小肯定是一开始就确定的。
和数据是没有关系的，如果数据多，ECharts 会自动处理这个情况，你需要做的就是用 css 固定好容器的高度。
