### ISSUE TITLE
多次进入小程序 图表不显示

### ISSUE THREAD

**Issue by fang635295364** [ecomfe/echarts-for-weixin#659]
![f30ab5d268338ed8fe3c856dd782253](https://user-images.githubusercontent.com/54343916/80194380-df499780-864c-11ea-9439-878bbce3f5f3.jpg)
第一次进入显示正常 完了点击右上角关闭在进入 就不显示了
![ca1ab34170497e6c04aa865c5799a77](https://user-images.githubusercontent.com/54343916/80194432-f1c3d100-864c-11ea-873e-4f3bd482ae57.jpg)

 图表代码
  onLoad: function() {
      this.getData();
      this.echartsComponnet1 = this.selectComponent('#mychart1');
      this.echartsComponnet2 = this.selectComponent('#mychart2');
      this.echartsComponnet3 = this.selectComponent('#mychart3');
      //获取数据
    },
    getData1: function() {
      if (!Chart[0]) {
        this.init_echarts(1); //初始化图表
      }
      if (!Chart[1]) {
        this.init_echarts(2); //初始化图表
      }
      if (!Chart[2]) {
        this.init_echarts(3); //初始化图表
      }

    },
    //初始化图表
    init_echarts: function(i) {
      this['echartsComponnet' + i].init((canvas, width, height, dpr) => {
        // 初始化图表
        Chart[i - 1] = echarts.init(canvas, null, {
          width: width,
          height: height,
          devicePixelRatio: dpr
        });
        this.setOption(i);
        // 注意这里一定要返回 chart 实例，否则会影响事件处理等
        return Chart[i - 1];
      });
    },
    setOption: function(i) {
      Chart[i - 1].clear(); // 清除
      Chart[i - 1].setOption(this['getOption' + i]()); //获取新数据
    },
    //图表1获取数据
    getOption1: function() {

**Comment by Ovilia** [comment]
出去的时候 dispose 掉，进来的时候重新初始化

**Comment by fang635295364** [comment]
这个chart.dispose() 应该写在哪里 有配置说明么

**Comment by Ovilia** [comment]
就是你不再需要这个图表实例（比如 dom 节点被移除）的时候调，文档：https://echarts.apache.org/zh/api.html#echartsInstance.dispose

**Comment by fang635295364** [comment]
已经解决了  麻烦了

**Comment by zx1222** [comment]
> 请问怎么解决的？？ 我在page onUnload中执行chart.dispose()还是不行 第二次进入不渲染
