### ISSUE TITLE
lazy_load模式下，点击图例后，线条不消失。

### ISSUE THREAD

**Issue by ramwin** [ecomfe/echarts-for-weixin#66]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
使用lazy_load模式，并添加了

### 预期效果：
点击图例后，对应的线条影藏

### 实际效果：
点击后，对应的曲线没有影藏。
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by crazyurus** [comment]
遇到了同样的问题，求解
