### ISSUE TITLE
不知道算不算bug 请帮忙看下

### ISSUE THREAD

**Issue by fang635295364** [ecomfe/echarts-for-weixin#662]
开发者工具上显示的如图
![image](https://user-images.githubusercontent.com/54343916/80467734-d7e9fd00-8970-11ea-8f6f-c560ba941ed2.png)
手机上可以正常显示
![image](https://user-images.githubusercontent.com/54343916/80468451-c523f800-8971-11ea-8598-bb965b77cccc.png)
之前一直显示正常 今天突然这样子了

**Comment by Ovilia** [comment]
应该是开发者工具的问题
