### ISSUE TITLE
Tooltip里面的formatter编译时标签识别为字符串

### ISSUE THREAD

**Issue by zl466281249** [ecomfe/echarts-for-weixin#666]
Tooltip里面的formatter编译时标签识别为字符串

**Comment by Ovilia** [comment]
什么意思？本来就应该是字符串

**Comment by zl466281249** [comment]
> 什么意思？本来就应该是字符串

正常应该是将div,span这边标签识别，但是现在是当成字符串编译了

**Comment by Ovilia** [comment]
哦哦，因为微信小程序的环境不支持 DOM 操作，所以 tooltip 也是用 canvas 渲染的，所以 div span 是没法使用的。可以用 ECharts 的富文本实现高级样式，参见：https://echarts.apache.org/zh/tutorial.html#%E5%AF%8C%E6%96%87%E6%9C%AC%E6%A0%87%E7%AD%BE

**Comment by githubWangc** [comment]
但是tooltip里面的formatter不支持富文本吧？
