### ISSUE TITLE
安卓的图表一些文字显示不全

### ISSUE THREAD

**Issue by huoyanfx** [ecomfe/echarts-for-weixin#668]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
安卓的图表一些文字显示不全
ios真机 和开发者工具没问题, 安卓有问题. 使用的新版Canvas 2d才会这样

### 预期效果：
![微信截图_20200505210921](https://user-images.githubusercontent.com/37257338/81070347-ad221a80-8f15-11ea-8b57-773f28832f07.png)

### 实际效果：
![微信截图_20200505210906](https://user-images.githubusercontent.com/37257338/81070354-af847480-8f15-11ea-9bf4-7f1f338a365d.png)

感觉是安卓的各个formatter和title的subtext字符串解析有问题...

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
不用 formatter 就没问题？

**Comment by jasaec** [comment]
相同问题 
强制使用3d+ formatter  正常
使用canvas 2d + formmater就会出现相同问题 特别是华为系的手机

**Comment by Ovilia** [comment]
似乎和 #650 是同一个问题，跟 formatter 可能没关系，就是数字的问题。排查中，请关注 #650。
