### ISSUE TITLE
ios端如何在确保图表能点击的同时图表内部区域不阻塞页面滚动

### ISSUE THREAD

**Issue by hexiaojun5233** [ecomfe/echarts-for-weixin#669]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
公司要在小程序中使用图表 要求如折线图 点击节点时能显示具体金额
但是在使用过程中 在图表区域内不能滑动页面 有能同时支持点击和不阻塞页面的解决方案吗？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
和小程序团队沟通过了，据说是小程序客户端的 bug，等待客户端修复。

**Comment by Ovilia** [comment]
同 #660

**Comment by hexiaojun5233** [comment]
谢谢

**Comment by BigFaceCat5233** [comment]
> > 和小程序团队沟通过了，据说是小程序客户端的 bug，等待客户端修复。
> 
> @Ovilia 想问一下 这个问题有解决吗？或者有没有什么解决方案？

嵌webview
