### ISSUE TITLE
Iphone7通过回退进入页面，图标不显示

### ISSUE THREAD

**Issue by jinsust** [ecomfe/echarts-for-weixin#670]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在iphone7手机上，点击回退按钮，返回上一页面，概率性出现图表不显示的问题；
直接进入页面，能正常显示；进入下一级页面后再返回概率出现

### 预期效果：
![5B75E13C-DFB0-457D-A374-22C8FD8F63F0](https://user-images.githubusercontent.com/2959978/81516829-e0c4d080-936b-11ea-843c-5e3465209bd8.png)

（如有需要请提供预期的图）

### 实际效果：
![41B796A2AA7E62605DB9F70731E5EA49](https://user-images.githubusercontent.com/2959978/81516782-b07d3200-936b-11ea-872b-16b1c721f5a8.png)

（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题  目前只在iphone7上出现，其他型号未出现此问题(android/iphone11等)

**Comment by jinsust** [comment]
通过日志排查，返回时echarts相关对象都是正常的
![image](https://user-images.githubusercontent.com/2959978/81517050-35684b80-936c-11ea-93e0-78d10d62a6cc.png)

**Comment by Ovilia** [comment]
如果有这个情况，可以尝试退出页面的时候 dispose 掉，进入的时候重新初始化。如果这能解决，说明引起问题的原因是，ECharts 实例还在，但是对应的 dom 节点已经不在了，你看到的是新的 dom 节点。

**Comment by jinsust** [comment]
尝试dispose  echart对象报错
platCatChart: xd
id: "ec_1589165063492"
resize: ƒ ()
_$eventProcessor: Bd {eventInfo: null}
_$handlers: {click: Array(1), finished: Array(1)}
__ec_primitive__: true
__flagInMainProcess: false
__optionUpdated: false
_api: Uu {getDom: ƒ, getZr: ƒ, getWidth: ƒ, getHeight: ƒ, getDevicePixelRatio: ƒ, …}
_chartsMap: {_ec_series00_series.bar: e}
_chartsViews: [e]
_componentsMap: {_ec_series00_axisPointer: e, _ec_series00_tooltip: e, _ec_series00_yAxis.value: e, _ec_series00_xAxis.category: e, _ec_series00_grid: e, …}
_componentsViews: (8) [e, e, e, e, e, e, e, e]
_coordSysMgr: Yu {_coordinateSystems: Array(1)}
_disposed: true
_dom: WxCanvas {ctx: CanvasRenderingContext2D, canvasId: "platCat-bar", chart: xd, isNew: true, canvasNode: r, …}
_ecEventProcessor: Bd {eventInfo: null}
_messageCenter: _d {_$handlers: {…}, _$eventProcessor: undefined}
_model: e {parentModel: undefined, ecModel: undefined, option: {…}, scheduler: bc, _theme: _l, …}
_pendingActions: []
_scheduler: bc {ecInstance: xd, api: Uu, _dataProcessorHandlers: Array(6), _visualHandlers: Array(10), _allHandlers: Array(16), …}
_theme: null
_throttledZrFlush: ƒ e()
_zr: Cr {dom: WxCanvas, id: 2321, storage: En, painter: Qi, handler: $t, …}
__proto__: Object

报错信息
this._tooltipContent.dispose is not a function;at "pages/brand/brand_detail" page lifeCycleMethod onHide function
TypeError: this._tooltipContent.dispose is not a function

**Comment by Ovilia** [comment]
参见 `lazyLoad` 的例子，dispose 不应该报错。

**Comment by Ovilia** [comment]
看一下如果是 https://github.com/ecomfe/echarts-for-weixin/issues/673 的问题的话，先替换为 4.6.0 版本
