### ISSUE TITLE
下载echarts-for-weixin，将ec-canvas/echart.js替换为官方4.7.0完整包，报错

### ISSUE THREAD

**Issue by F5F5** [ecomfe/echarts-for-weixin#673]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
调用dispose或clear报错，dispose第二次可调用成功：
this._tooltipContent.dispose is not a function; 

### 预期效果：
不报错且调用成功

### 实际效果：
（如有需要请提供截图）
![image](https://user-images.githubusercontent.com/15978277/81928681-3a512780-9618-11ea-85f9-46421070908a.png)

试了下官方的4.6.0版本，不报错

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
这个 bug 在 https://github.com/apache/incubator-echarts/pull/12608 修复了，4.9.0 版本发布还需要一段时间（2-5周），建议先使用 4.6.0 版本。
