### ISSUE TITLE
小程序在真机中tooltip点击一次后，图表无法再次点击，或者说是卡住了

### ISSUE THREAD

**Issue by caojwaqzh** [ecomfe/echarts-for-weixin#674]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在真机打开情况下，tooltip第一次点击或者触摸上有效果，之后不能移动（不知道是不是卡住了），页面无任何阻塞

### 预期效果：
希望可以和电脑上效果一样，tooltip随点击移动而移动

### 实际效果：
![微信图片_20200520135846](https://user-images.githubusercontent.com/24741727/82410239-0d7e9380-9aa2-11ea-9b3e-376e5833c805.jpg)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
本项目 demo 中的例子是否有这个问题？没有的话，请提供一个最简单的复现代码

**Comment by caojwaqzh** [comment]
> 本项目 demo 中的例子是否有这个问题？没有的话，请提供一个最简单的复现代码

tooltip 我搞错了 我用的是 echarts-mpvue
echarts-for-weixin我引用到 mpvue 中后 一直报 creatElement不存在的错误 有遇到过相同问题的吗？我想试试看用这个 tooltip还会不会卡 但是用不了现在

**Comment by Ovilia** [comment]
这个问题在 https://github.com/apache/incubator-echarts/pull/12608 中修复了，但是 ECharts 还没发版。如果急需的话，可以自行[编译 ECharts 项目的 master 分支](https://github.com/apache/incubator-echarts/wiki/How-to-setup-the-dev-environment#3-run-and-debug)，替换本项目中的 `echarts.js`。
