### ISSUE TITLE
dataZoom 滚动条支持

### ISSUE THREAD

**Issue by koukaicheng** [ecomfe/echarts-for-weixin#69]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？
在一个折线图上面 左右滑动  我在配置中加了 dataZoom: {
      type: 'slider',
      realtime: false
    },
但是 只在图表上方出现了一个滚动条 但是不会真的滑动

### 预期效果：
？？？
（如有需要请提供预期的图）
![image](https://user-images.githubusercontent.com/23202904/37508362-b1269912-292d-11e8-8939-2d0a575ea15f.png)

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
滚动条现在支持得不太好，后面改进下

**Comment by Ovilia** [comment]
同 #61，这里先关了
