### ISSUE TITLE
旭日图如何根据onclick的参数快速定位到data层级

### ISSUE THREAD

**Issue by zhangkl** [ecomfe/echarts-for-weixin#690]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
我需要编辑旭日图的节点，希望通过click事件的入参，能够快速定位到数据并进行修改保存。

### 预期效果：
click事件入参中提供data数据的层级，比如data[0].children[1].chlidren[2]
或提供其他实现方式

### 实际效果：
无次参数

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
这个请到 ECharts 项目中提
