### ISSUE TITLE
雷达图文字重叠问题

### ISSUE THREAD

**Issue by zyzkevin** [ecomfe/echarts-for-weixin#701]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
雷达图的文字label 重叠问题, 有可能是因为我的indicators太多了. 这个问题主要在圆的上方和下方出现

### 实际效果：
![image](https://user-images.githubusercontent.com/52997677/88893010-4c864d80-d278-11ea-92d4-e3e73cdea7e2.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
这个请到 ECharts 项目报 bug
