### ISSUE TITLE
懒加载图表不支持trigger: 'axis'吗？

### ISSUE THREAD

**Issue by flitrue** [ecomfe/echarts-for-weixin#72]
```
tooltip: {
      trigger: 'axis',
      axisPointer: {            // 坐标轴指示器，坐标轴触发有效
        type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
      }
    },
```
### 懒加载：点击axis无效果
![image](https://user-images.githubusercontent.com/15258895/37533462-db3c314a-297c-11e8-8cb7-11c1a0c36291.png)

### 非懒加载：显示阴影
![image](https://user-images.githubusercontent.com/15258895/37533503-fc28c364-297c-11e8-9566-72d5ac621b7c.png)

**Comment by flitrue** [comment]
懒加载也不支持formatter传入函数  
```
axisLabel: {
          formatter: function(){
            return 'hello'
          },
          color: '#666'
        }
```

**Comment by Ovilia** [comment]
已修复 0883dcc
