### ISSUE TITLE
柱形图 给各个柱形设置背景色

### ISSUE THREAD

**Issue by Hongwei-Qiu** [ecomfe/echarts-for-weixin#723]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
微信小程序柱状图每个柱形图设置不同颜色，但还是默认颜色，以下是代码，h5的echart能实现，微信不行
series: [{				
							type: 'bar',
							data: [],
							itemStyle: {
								normal: {
									color: function(params) {
										let color = ['#FF7B7B', '#FFCF85', '#58DBC6', '#58C1DB', '#CA9FFF', '#FDBDA9', '#FFA0D6', '#E4FA97',
											'#E4FA97'
										];
										return color[params.dataIndex]

									},

								}
							}
						}]

### 预期效果：
![image](https://user-images.githubusercontent.com/32996949/92898373-825e4a80-f450-11ea-8379-e9f31be67201.png)

（如有需要请提供预期的图）

### 实际效果：
？？？
![image](https://user-images.githubusercontent.com/32996949/92898537-a326a000-f450-11ea-89f7-68bca3e2d15a.png)

（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Hongwei-Qiu** [comment]
微信的color 不支持吗

**Comment by xiaozhang121** [comment]
我现在也遇到了这个问题 请问你的解决了吗

**Comment by Hongwei-Qiu** [comment]
没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ecomfe/echarts-for-weixin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月28日(星期一) 中午11:58
收件人:&nbsp;"ecomfe/echarts-for-weixin"<echarts-for-weixin@noreply.github.com&gt;;
抄送:&nbsp;"等梦归"<1614837845@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ecomfe/echarts-for-weixin] 柱形图 给各个柱形设置背景色 (#723)





 
我现在也遇到了这个问题 请问你的解决了吗
