### ISSUE TITLE
怎么保存为图片

### ISSUE THREAD

**Issue by ymli1981** [ecomfe/echarts-for-weixin#73]
在小程序中，怎么把图表保存到手机相册中

**Comment by Ovilia** [comment]
暂不支持

**Comment by Ovilia** [comment]
参考 `pages/saveCanvas` 的例子，生成临时本地文件路径后，可以使用 [wx.saveFile](https://mp.weixin.qq.com/debug/wxadoc/dev/api/file.html#wxsavefileobject) 保存。
