### ISSUE TITLE
支持缩放和平移吗

### ISSUE THREAD

**Issue by ymli1981** [ecomfe/echarts-for-weixin#74]
demo不能缩放平移，需要怎么设置？

**Comment by Ovilia** [comment]
目前还不支持多指操作，平移是可以的，比如地图里可以设置 `roam: true` 设置

**Comment by hepking** [comment]
请问，使用tree为layout: 'radial'的时候如何平移呢？

**Comment by Ovilia** [comment]
573025c917cb3107b0c64b5d8fb4547e1a0ae1f4 现已支持。

**Comment by sunnyateveryday** [comment]
> 目前还不支持多指操作，平移是可以的，比如地图里可以设置 `roam: true` 设置

能不能在柱状图里面平移呢我设置dataroom怎么无法平移
