### ISSUE TITLE
坐标轴箭头在安卓上有问题

### ISSUE THREAD

**Issue by ymli1981** [ecomfe/echarts-for-weixin#75]
坐标标签rotate：设置rotate，比如45，不是单个标签旋转45，而是所有标签作为一个整体旋转45
坐标markline：设为[none,arror]后，纵向末端有箭头，横向没有

这两个问题都是安卓有，苹果无

**Comment by Ovilia** [comment]
怀疑是安卓 transform 问题引起的

**Comment by wangchao523** [comment]
我也遇到了这个问题axisLabel.rotate=45，开发工具显示正常。华为机中有问题

**Comment by ZhuRuiHeng** [comment]
+1

**Comment by yueyue-zhang** [comment]
请问这个问题目前解决了吗？

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
