### ISSUE TITLE
Echarts图表在ios最新版微信7.0.20存在微信闪退问题。

### ISSUE THREAD

**Issue by GuanQi0812** [ecomfe/echarts-for-weixin#767]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？
![image](https://user-images.githubusercontent.com/39716280/103398569-3f97be00-4b78-11eb-9301-df2531c4132b.png)

### 预期效果：
？？？
（如有需要请提供预期的图）
![image](https://user-images.githubusercontent.com/39716280/103398575-47eff900-4b78-11eb-85e1-e54aca968c45.png)

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题
- 真机上点击 微信直接闪退，并提示清理内存，存在风险。

**Comment by lantsang** [comment]
https://developers.weixin.qq.com/community/develop/doc/000a06475c0528cdbf7baf20a51c00

**Comment by GuanQi0812** [comment]
已经解决，微信官方大大已知bug，会尽快修复。

**Comment by lantsang** [comment]
这个问题微信官方已经解决了。把微信升级到ios 7.0.21即可。
具体请查看链接 https://developers.weixin.qq.com/community/develop/doc/000a06475c0528cdbf7baf20a51c00

**Comment by IVanMissAya** [comment]
好的 谢谢大佬~
