### ISSUE TITLE
地图样例如何在同页面中动态刷新

### ISSUE THREAD

**Issue by EllisonTsui** [ecomfe/echarts-for-weixin#77]
function initChina(canvas, width, height) {
}

**Comment by Ovilia** [comment]
动态刷新是什么意思？参考延迟加载的例子？

**Comment by EllisonTsui** [comment]
ec 在图表能够在页面加载后被初始化，但是会有需求在当前页面中更换这个图表（比如地图）的内容

**Comment by Ovilia** [comment]
参见柱状图的例子，https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/bar/index.js#L133 获取实例的方式，然后 setOption 改变

**Comment by EllisonTsui** [comment]
已解决，谢谢你哈！

**Comment by EllisonTsui** [comment]
#问题补充# 如果图表 所在的父级元素的display:none, 在当父级元素的display:block,刷新无效，求帮助~

**Comment by Ovilia** [comment]
应该是在父元素 display: block 的时候才初始化，或者 chart.resize()，总之要保证图表容器有宽度和高度
