### ISSUE TITLE
微信小程序 ios端 图表能正常显示 但是触摸就闪退

### ISSUE THREAD

**Issue by IVanMissAya** [ecomfe/echarts-for-weixin#772]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
option配置项 有tooltip 有datazoom  开发工具上一切正常 Andriod端正常 ios端正常显示 但是触摸闪退 

### 预期效果：
Andriod端和IOS端 都能正常显示图表
（如有需要请提供预期的图）

### 实际效果：
Andriod端正常  IOS端能显示 但是触摸闪退
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中不存在该问题
- [x] 在真机上存在该问题

**Comment by IVanMissAya** [comment]
经过测试发现 就是tooltip的原因    使用tooltip 没有自定义参数  ios端触摸就闪退

**Comment by guakeliao** [comment]
我也使用了， 但是我的正常呢。
var option = {
    ...
    tooltip: {
      trigger: 'axis',
      axisPointer: { // 坐标轴指示器，坐标轴触发有效
        type: 'shadow' // 默认为直线，可选为：'line' | 'shadow'
      },
      confine: true
    },
    ...
}

**Comment by IVanMissAya** [comment]
已经解决啦  具体查看链接
https://developers.weixin.qq.com/community/develop/doc/000a06475c0528cdbf7baf20a51c00
