### ISSUE TITLE
图表不是tab页中的第一页,显示空白。

### ISSUE THREAD

**Issue by guakeliao** [ecomfe/echarts-for-weixin#773]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
图表在 tab中的第一页显示出来了。其他tab页显示空白
### 预期效果：
<img width="384" alt="WX20210112-150445@2x" src="https://user-images.githubusercontent.com/9064387/104280969-ad80a580-54e7-11eb-8534-d8524ca59b0d.png">

### 实际效果：
<img width="389" alt="WX20210112-150502@2x" src="https://user-images.githubusercontent.com/9064387/104280975-b1acc300-54e7-11eb-81c5-f4511d012c10.png">

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by IVanMissAya** [comment]
因为在其他tab页面  图表节点没有加载出来  获取不到图表对象  可以在切换tab完成的时候 获取图表对象 在渲染图表

**Comment by guakeliao** [comment]
谢谢。确实是你说的问题。已经解决

**Comment by IVanMissAya** [comment]
不用谢不用谢   我那个问题还没有解决呢...  微信小程序中使用 tooltip 没有自定义参数 ios端触摸图表就闪退..

**Comment by guakeliao** [comment]
sorry 我帮不了你呀。我才接触前端。脑壳都大了

**Comment by IVanMissAya** [comment]
嗯嗯 没事没事  我那个暂时先把tooltip注释掉了  也提交了issue 等官方回复吧.. 加油加油~

**Comment by guakeliao** [comment]
我暂时没有遇到你的问题呢。我也使用了tooltip。
var option = {
    ...
    tooltip: {
      trigger: 'axis',
      axisPointer: { // 坐标轴指示器，坐标轴触发有效
        type: 'shadow' // 默认为直线，可选为：'line' | 'shadow'
      },
      confine: true
    },
    ...
}

**Comment by IVanMissAya** [comment]
已经解决了  微信更新到最新版 就可以了

**Comment by IVanMissAya** [comment]
https://developers.weixin.qq.com/community/develop/doc/000a06475c0528cdbf7baf20a51c00
