### ISSUE TITLE
小程序引用插件过大

### ISSUE THREAD

**Issue by KKMAMi** [ecomfe/echarts-for-weixin#774]
我项目中目前只用到了简单的折线图，但是发现ec-canvas组件中的echarts文件就有700多K，我想问下，我能不能针对性的引用，因为小程序项目现在本身就对大小限制的严格，望回复
![image](https://user-images.githubusercontent.com/37092331/104430410-97471800-55c1-11eb-8ee5-12bd1cc45b2b.png)

**Comment by AbbyLiang** [comment]
https://echarts.apache.org/zh/builder.html   可定制
