### ISSUE TITLE
标注显示问题

### ISSUE THREAD

**Issue by ymli1981** [ecomfe/echarts-for-weixin#78]
坐标轴 markline.symbo="dashed" 时，markpoint的circle图形显示不全，只显示3/4，
markline不设置，或symbo设置为 solid时，就无此问题

**Comment by Ovilia** [comment]
应该是 `markLine.lineStyle.type` 设为 `'dashed'`，`markPoint.symbol` 设为 `'circle'`，这样还有问题吗？

**Comment by ymli1981** [comment]
就是这么设置的，我表述错了，还是有问题
苹果手机

**Comment by Ovilia** [comment]
贴一下有问题的代码，以及开发工具上是否有问题

**Comment by ymli1981** [comment]
电脑端小程序显示正常，真机显示有问题，都已更新到微信最新版

**Comment by ymli1981** [comment]
series: [
        {
          type: 'scatter',
          name: title1,
          
          markPoint: {
            symbol: 'circle',
            silent: false,
            symbolSize: xymin,
            itemStyle: {
              borderColor: '#000',
              borderWidth: 1,
              borderType: 'solid',
              color: '#fff'
            },
            data: bdata,

            label: {
              show: true,
              fontSize: 11,
              color: '#000',
              formatter: function (params) {
                var str1 = params.data.name
              }
            }





          },
          markLine: {
            silent: true,
            symbol: ['none', 'arrow'],
            lineStyle: {

              normal: {
                type: 'solid',
                opacity: 1,
                color: '#888',
              }
            },
            label: { show: false },
            animation: false,
            data: ldata,
          },



        }

**Comment by ymli1981** [comment]
[https://24lchh.cn/wx/ke/1.jpg](url)
[https://24lchh.cn/wx/ke/2.png](url)

**Comment by Ovilia** [comment]
把完整的代码贴一下，`bdata` 之类的不知道是什么。数据复杂的话，简单复现下。

**Comment by ymli1981** [comment]
就是类似这样的数据

[{name:"xx1",
coord[2,3]},{name:"xx2",
coord[2,1]}]
在markpoint里显示name值

**Comment by ymli1981** [comment]
你们只要一测试就会发现问题了，我发个完整代码

**Comment by ymli1981** [comment]
定义全局变量 bdata ,ldata

**Comment by ymli1981** [comment]
就在你们这个实例的scatter里

定义全局变量 ldata,bdata,
在onready里赋值
onReady() {
	  bdata=[
  { name:'维度1',coord:[0,10]},
  { name: '维度2', coord: [20, 20] },
  { name: '维度3', coord: [0, 30] },
  { name: '项目1', coord: [10, 10] },
  { name: '项目2', coord: [20, 40] },
  { name: '项目3', coord: [30, 10] },

] 
	  ldata=[]
	  for (let i = 0; i < 4; i++) {
      let ll = [
        {

          coord: [(i + 1)*5, 0]
        },
        {
          coord: [(i + 1) * 5,100]
        }
      ]
      ldata.push(ll)
    }
    for (let j = 0; j < 4; j++) {
      let ll = [
        {

          coord: [0, (j + 1)*5]
        },
        {
          coord: [100, (j + 1) * 5]
        }
      ]
      ldata.push(ll)
    }
  }
然后在series里加上
markPoint: {
              symbol: 'circle',
              silent: false,
              symbolSize:50,
              itemStyle: {
                borderColor: '#000',
                borderWidth: 1,
                borderType: 'solid',
                color: '#fff'
              },
              data:bdata,

              label: {
                show: true,
                fontSize:11,
                color: '#000',
                formatter: function (params) {
                  var str1 = params.data.name
                  var zj = parseInt(50/ 15.6) + 1
                  var max1 = zj *( zj-1)
                  var reg = new RegExp("[\\u4E00-\\u9FFF]+", "g");
                  if (reg.test(str1)) { 

                  }
                  else {
                    
                    max1 = zj*2 *(zj-1)
                    zj = zj * 2
                  }
                  
                  console.log(max1)
                  if (str1.length > max1) { str1 = str1.substr(0, max1 - 1) + "…" }
                  var s = str1.split("");
                  for (var i = zj - 1; i < s.length; i += zj) {
                    if(i!=s.length-1){s[i] = s[i] + "\n";}
                  }

                  var ss = '';
                  
                  for (var i = 0; i < s.length; i++) {
                    ss += s[i];
                  }
                 
                 
                  return ss
                }
              },
            },
            markLine: {
              silent: true,
              symbol: ['none', 'arrow'],
              lineStyle: {

                normal: {
                  type: 'dashed',
                  opacity:1,
                  color: '#888',
                }
              },
              label: { show: false },
              animation:false,
              data: ldata,
            },
    },

错误就可以复现了

**Comment by ymli1981** [comment]
完整代码

**Comment by ymli1981** [comment]
完整代码        import * as echarts from '../../ec-canvas/echarts';
var bdata
var ldata
const app = getApp();

function initChart(canvas, width, height) {
  const chart = echarts.init(canvas, null, {
    width: width,
    height: height
  });
  canvas.setChart(chart);

  var data = [];
  var data2 = [];

  for (var i = 0; i < 10; i++) {
    data.push(
      [
        Math.round(Math.random() * 100),
        Math.round(Math.random() * 100),
        Math.round(Math.random() * 40)
      ]
    );
    data2.push(
      [
        Math.round(Math.random() * 100),
        Math.round(Math.random() * 100),
        Math.round(Math.random() * 100)
      ]
    );
  }

  var axisCommon = {
    axisLabel: {
      textStyle: {
        color: '#C8C8C8'
      }
    },
    axisTick: {
      lineStyle: {
        color: '#fff'
      }
    },
    axisLine: {
      lineStyle: {
        color: '#C8C8C8'
      }
    },
    splitLine: {
      lineStyle: {
        color: '#C8C8C8',
        type: 'solid'
      }
    }
  };

  var option = {
    color: ["#FF7070", "#60B6E3"],
    backgroundColor: '#eee',
    xAxis: axisCommon,
    yAxis: axisCommon,
    legend: {
      data: ['aaaa', 'bbbb']
    },
    visualMap: {
      show: false,
      max: 100,
      inRange: {
        symbolSize: [20, 70]
      }
    },
    series: [{
      type: 'scatter',
      name: 'aaaa',
      data: data,
		  markPoint: {
              symbol: 'circle',
              silent: false,
              symbolSize:50,
              itemStyle: {
                borderColor: '#000',
                borderWidth: 1,
                borderType: 'solid',
                color: '#fff'
              },
              data:bdata,

              label: {
                show: true,
                fontSize:11,
                color: '#000',
                formatter: function (params) {
                  var str1 = params.data.name
                  var zj = parseInt(50/ 15.6) + 1
                  var max1 = zj *( zj-1)
                  var reg = new RegExp("[\\u4E00-\\u9FFF]+", "g");
                  if (reg.test(str1)) { 

                  }
                  else {
                    
                    max1 = zj*2 *(zj-1)
                    zj = zj * 2
                  }
                  
                  console.log(max1)
                  if (str1.length > max1) { str1 = str1.substr(0, max1 - 1) + "…" }
                  var s = str1.split("");
                  for (var i = zj - 1; i < s.length; i += zj) {
                    if(i!=s.length-1){s[i] = s[i] + "\n";}
                  }

                  var ss = '';
                  
                  for (var i = 0; i < s.length; i++) {
                    ss += s[i];
                  }
                 
                 
                  return ss
                }
              },
            },
            markLine: {
              silent: true,
              symbol: ['none', 'arrow'],
              lineStyle: {

                normal: {
                  type: 'dashed',
                  opacity:1,
                  color: '#888',
                }
              },
              label: { show: false },
              animation:false,
              data: ldata,
            },
    },
    {
      name: 'bbbb',
      type: 'scatter',
      data: data2
    }
    ],
    animationDelay: function (idx) {
      return idx * 50;
    },
    animationEasing: 'elasticOut'
  };


  chart.setOption(option);
  return chart;
}

Page({
  onShareAppMessage: function (res) {
    return {
      title: 'ECharts 可以在微信小程序中使用啦！',
      path: '/pages/index/index',
      success: function () { },
      fail: function () { }
    }
  },
  data: {
    ec: {
      onInit: initChart
    }
  },

  onReady() {
	  bdata=[
  { name:'维度1',coord:[0,10]},
  { name: '维度2', coord: [20, 20] },
  { name: '维度3', coord: [0, 30] },
  { name: '项目1', coord: [10, 10] },
  { name: '项目2', coord: [20, 40] },
  { name: '项目3', coord: [30, 10] },

] //标签位置
	  ldata=[]
	  for (let i = 0; i < 4; i++) {
      let ll = [
        {

          coord: [(i + 1)*5, 0]
        },
        {
          coord: [(i + 1) * 5,100]
        }
      ]
      ldata.push(ll)
    }
    for (let j = 0; j < 4; j++) {
      let ll = [
        {

          coord: [0, (j + 1)*5]
        },
        {
          coord: [100, (j + 1) * 5]
        }
      ]
      ldata.push(ll)
    }
  }
});

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
