### ISSUE TITLE
echarts 无法被任何元素覆盖掉？求大神支招

### ISSUE THREAD

**Issue by zhouhang94** [ecomfe/echarts-for-weixin#79]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
echarts 无法被任何元素覆盖掉！！！无论怎么定位也好，z-index也好，echarts都会在最上层

### 预期效果：
echarts图表可以被其他元素覆盖

### 实际效果：
echarts无法被任何元素覆盖

### 复现环境：
- [ ] 在微信开发工具中存在该问题
- [yes] 在真机上存在该问题

**Comment by Ovilia** [comment]
其他元素写 z-index 的时候有没有 `position: relative` 之类的？

**Comment by Ovilia** [comment]
在开发工具和真机上都无法复现，请提供相应代码

**Comment by blockmood** [comment]
我都是直接隐藏了canvas，然后再显示出来，这样做的，反正我是覆盖不了，各种办法都试了。

**Comment by Ovilia** [comment]
参见 #84

**Comment by Rainylane** [comment]
用cover-view标签
