### ISSUE TITLE
TypeError: t.addEventListener is not a function

### ISSUE THREAD

**Issue by Rabbitzzc** [ecomfe/echarts-for-weixin#791]
问题：`TypeError: t.addEventListener is not a function`

场景：在小程序中使用，出现上面报错（Rax）

**Comment by Ovilia** [comment]
代码？

**Comment by yexk** [comment]
我也遇到了一样的问题。你的解决了吗？

```js
import Taro, { Component } from "react";
import { View } from "@tarojs/components";
import echarts from "../../components/ec-canvas/echarts";
import "./index.scss";

let pieDataA = null;
export default class Index extends Component {
  constructor(props) {
    super(props);
    this.state = {
      ec: {
        onInit: this.initChart,
      },
    };
  }
  componentWillMount() {
      // pieDataA.setOption(this.getOption(), true);
  }
  getOption() {
    let option = {
      title: {
        text: "ECharts 入门示例1",
      },
      tooltip: {},
      legend: {
        data: ["销量"],
      },
      xAxis: {
        data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"],
      },
      yAxis: {},
      series: [
        {
          name: "销1量",
          type: "bar",

          data: [5, 20, 36, 10, 10, 20],
        },
      ],
    };
    return option;
  }
  initChart(canvas, width, height) {
    console.log('==>',canvas);
    const chart = echarts.init(canvas, null, {
      width: width,
      height: height,
    });
    canvas.setChart(chart);
    chart.setOption(this.getOption(), true);
    pieDataA = chart;
    return chart;
  }
  render() {
    return (
      <View className="list">
        <View className="mychart-con">
          <ec-canvas id="xxx" canvasId="xxx" ec={ this.state.ec } force-use-old-canvas="true"></ec-canvas>
        </View>
      </View>
    );
  }
}

```
![image](https://user-images.githubusercontent.com/19749521/131322198-3afdbb76-bcda-4ab2-8261-965dcebf5af0.png)

**Comment by pans0911** [comment]
> 我也遇到了一样的问题。你的解决了吗？
> 
> ```js
> import Taro, { Component } from "react";
> import { View } from "@tarojs/components";
> import echarts from "../../components/ec-canvas/echarts";
> import "./index.scss";
> 
> let pieDataA = null;
> export default class Index extends Component {
>   constructor(props) {
>     super(props);
>     this.state = {
>       ec: {
>         onInit: this.initChart,
>       },
>     };
>   }
>   componentWillMount() {
>       // pieDataA.setOption(this.getOption(), true);
>   }
>   getOption() {
>     let option = {
>       title: {
>         text: "ECharts 入门示例1",
>       },
>       tooltip: {},
>       legend: {
>         data: ["销量"],
>       },
>       xAxis: {
>         data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"],
>       },
>       yAxis: {},
>       series: [
>         {
>           name: "销1量",
>           type: "bar",
> 
>           data: [5, 20, 36, 10, 10, 20],
>         },
>       ],
>     };
>     return option;
>   }
>   initChart(canvas, width, height) {
>     console.log('==>',canvas);
>     const chart = echarts.init(canvas, null, {
>       width: width,
>       height: height,
>     });
>     canvas.setChart(chart);
>     chart.setOption(this.getOption(), true);
>     pieDataA = chart;
>     return chart;
>   }
>   render() {
>     return (
>       <View className="list">
>         <View className="mychart-con">
>           <ec-canvas id="xxx" canvasId="xxx" ec={ this.state.ec } force-use-old-canvas="true"></ec-canvas>
>         </View>
>       </View>
>     );
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/19749521/131322198-3afdbb76-bcda-4ab2-8261-965dcebf5af0.png)

兄弟，你解决了吗，我也碰到这个问题了

**Comment by pans0911** [comment]
> 问题：`TypeError: t.addEventListener is not a function`
> 
> 场景：在小程序中使用，出现上面报错（Rax）

兄弟，如何解决的，我也碰到相同的问题了

**Comment by pans0911** [comment]
t.addEventListener 后面改写为 t.addEventListener?.(e,n,i)

**Comment by imsheng** [comment]
我也遇到这个问题 in taro 3.3.12

**Comment by Rabbitzzc** [comment]
根据上面那个朋友写的改一下试试？

**Comment by Jingjingsixgod** [comment]
> 我也遇到这个问题 in taro 3.3.12

我也遇到了这个问题，请问一下是怎么解决的

**Comment by zhoulujun** [comment]
同样的问题，无解……

**Comment by Rabbitzzc** [comment]
加上 ? 不可以么....之前我记得解决了，不过忘了解决方案了

**Comment by Jingjingsixgod** [comment]
> 加上 ? 不可以么....之前我记得解决了，不过忘了解决方案了

可以解决
window.addEventListener.(e,n,i)修改成window.addEventListener?.(e,n,i)解决了

**Comment by Ovilia** [comment]
pull 一下最新代码，addEventListener 的问题已经解决了
