### ISSUE TITLE
真机IOS不显示，真机调试报错

### ISSUE THREAD

**Issue by liucyu** [ecomfe/echarts-for-weixin#794]
![image](https://user-images.githubusercontent.com/13191643/115101598-11e45280-9f78-11eb-9e05-c6b37b060c14.png)

**Comment by BeHappy0o0o0o0** [comment]
调试可以使用 强制使用旧版本canvas的开关，来解决。 上线时，把开关去掉。

**Comment by Ovilia** [comment]
微信小程序方面的答复：这个是 canvas 2d 是同步 jsbinding 接口实现，真机调试还不支持，可以忽略，我们即将支持了
