### ISSUE TITLE
关于在iphone上图表标题不显示问题。

### ISSUE THREAD

**Issue by blockmood** [ecomfe/echarts-for-weixin#81]
![tim 20180320184448](https://user-images.githubusercontent.com/22879524/37650151-0b6d06ce-2c6f-11e8-815c-d579284bbb23.png)

这个标题位置在iphone上onload打开不加载，等点击当前空白区域的时候又会显示出标题，多次点击又会消失，请问这是什么问题？

**Comment by blockmood** [comment]
补充一下我刚才的问题：我设置以下这个属性，就是默认有一个不选中状态，onload的时候可以显示的，但是只要3个全部选中，就会出现空白问题。

legend: {
      data: ['A商品1', 'B商品', 'C商品'],
      selected:{
        'C商品':false
      }
    },

**Comment by chinaAF** [comment]
我也发现这个问题了，legend在ios上不显示

**Comment by Rainylane** [comment]
同样遇到了这个问题

**Comment by Ovilia** [comment]
同 #52，还没排查出原因，请关注 #52
