### ISSUE TITLE
企业微信小程序下，控制台触发 非法颜色: none 报错

### ISSUE THREAD

**Issue by elevensky** [ecomfe/echarts-for-weixin#823]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
企业小程序下兼容问题，报错，非法颜色: none，这个应该是微信的内置脚本报的。
![image](https://user-images.githubusercontent.com/6904834/130004633-ff975bc6-f0af-4499-8c04-893412413533.png)

### 预期效果：
控制台无报错
（如有需要请提供预期的图）

### 实际效果：
一堆报错
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Xlu103** [comment]
我的解决方法是更改微信小程序基础库版本到2.10.4

**Comment by BackMountainDevil** [comment]
https://developers.weixin.qq.com/community/enterprisewechat/doc/0000c66e358490a3e89c7a7fc56400

本地调试 v2.22.0 真机调试v2.6.6也会有这个错误。但是相同环境运行本仓库的代码就没有问题。。

**Comment by BackMountainDevil** [comment]
canvas2D 在2.9.0 发布，是我真机太低了。。
