### ISSUE TITLE
真机下markLine设置symbol无效果

### ISSUE THREAD

**Issue by flitrue** [ecomfe/echarts-for-weixin#83]
真机效果：  
![image](https://user-images.githubusercontent.com/15258895/37652536-d224afe0-2c76-11e8-8665-bc019d1b0d38.png)

开发者工具效果：  
![image](https://user-images.githubusercontent.com/15258895/37652649-2709033a-2c77-11e8-99c8-447a2d64fd46.png)

代码：
```
markLine: {
          symbol: ["", "arrow"],
          symbolSize: [5, 5]
}
```

注：最新代码

**Comment by Ovilia** [comment]
同#75
