### ISSUE TITLE
TypeError: t.addEventListener is not a function

### ISSUE THREAD

**Issue by imsheng** [ecomfe/echarts-for-weixin#832]
使用 taro 3.3 编译微信小程序 运行不成功

提示 TypeError: t.addEventListener is not a function

https://github.com/ecomfe/echarts-for-weixin/issues/791

**Comment by 154305** [comment]
把"undefined"!=typeof window&&!!window.addEventListener这句直接改成false

**Comment by 154305** [comment]
echarts.js里面

**Comment by zhengjianghao** [comment]
试一下下面这个方法：
1.https://echarts.apache.org/zh/builder.html, 自行下载echart.min.js
2.搜索t.echarts={},找到后面的方法,替换如下
3.(this,function(t) => (this,function(t,window,document)
4.替换ec-canvas里面的echarts.js,不要忘记改名字
亲测可行
