### ISSUE TITLE
在 Taro3 中 ec-canvas 不能正常运行

### ISSUE THREAD

**Issue by RobertChaw** [ecomfe/echarts-for-weixin#834]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
ec-canvas 不能正常运行使用，运行项目为[Taro官方示例](https://github.com/NervJS/taro-sample-weapp/tree/vue)
在网上看到一种[临时的解决方法](https://juejin.cn/post/7013280646336348167)

### 预期效果：
![image](https://user-images.githubusercontent.com/29568488/141677225-9578a5fc-6ba8-480c-bb21-2ca482fd281e.png)
（如有需要请提供预期的图）

### 实际效果：
![image](https://user-images.githubusercontent.com/29568488/141677233-0d99e659-3d95-42c9-983c-8ef65c86a095.png)
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Komorebi94** [comment]
试一下下面这个方法：
1.https://echarts.apache.org/zh/builder.html,自行下载echart.min.js
2.搜索t.echarts={},找到后面的方法,替换如下
3.(this,function(t) => (this,function(t,window,document)
4.替换ec-canvas里面的echarts.js,不要忘记改名字
