### ISSUE TITLE
真机上echarts悬浮，未随swiper滑动而滑动

### ISSUE THREAD

**Issue by cnsilvan** [ecomfe/echarts-for-weixin#84]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [X] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
swiper中使用了echarts，滑动过程中echarts并未跟随页面一起滑动，一直在原来位置上

### 预期效果：
应该随页面一起滑动
（如有需要请提供预期的图）
![image](https://user-images.githubusercontent.com/15416002/37697878-6969f970-2d1a-11e8-9a56-5d48b3174a5f.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/15416002/37697930-da53387c-2d1a-11e8-9e3c-c763b4d1dfc2.png)

（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [X] 在真机上存在该问题（一加5T）

**Comment by cnsilvan** [comment]
微信是最新版本的

**Comment by Ovilia** [comment]
因为 css position 写得不对？

**Comment by cnsilvan** [comment]
@Ovilia 全部position都试过了。echarts一直在悬浮的感觉。只在真机上有这个问题。我用官方demo套了个swiper试一下。发现也是这样的

**Comment by cnsilvan** [comment]
测试了android和ios 都是这样的

**Comment by FreeFlying0** [comment]
echarts是用canvas组件来实现的，微信官方都认为canvas组件本身还是有问题的
![image](https://user-images.githubusercontent.com/11344018/37699448-8dab1f64-2d22-11e8-8e47-826808468aed.png)

**Comment by x-manJS** [comment]
用svg渲染替代canvas渲染

[https://echarts.baidu.com/tutorial.html#%E4%BD%BF%E7%94%A8%20Canvas%20%E6%88%96%E8%80%85%20SVG%20%E6%B8%B2%E6%9F%93](url)

**Comment by tinycalf918** [comment]
请问这个问题是没有解决方法么？我现在就是要在echarts图形区域上悬浮一个img，但是在手机上会被图层覆盖
