### ISSUE TITLE
飞书小程序的支持性

### ISSUE THREAD

**Issue by duym1016** [ecomfe/echarts-for-weixin#843]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
你好，我是一位开发者，目前我们在探索**飞书小程序**（字节跳动）的开发，较多场景有考虑使用echarts进行数据展示，请问后期是否会针对飞书小程序进行支持？

### 预期效果：
可以在飞书小程序中正常使用echarts进行图表等展示

### 实际效果：
目前在飞书中引入，会报微信支持库版本问题，本人已经去代码里面注释，绕过了这些校验。目前没有报错，但是饼图一直没有展示出来，仍在尝试使用。

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题
- [x] 在飞书开发者工具上存在该问题

**Comment by zhonghuaifang** [comment]
问一下，你解决这个问题了吗？我也是要做飞书小程序，需要用到图表，到现在都没找到能用的组件

**Comment by duym1016** [comment]
> 问一下，你解决这个问题了吗？我也是要做飞书小程序，需要用到图表，到现在都没找到能用的组件

你好，我之前联系了飞书小程序的开发人员，明确得知，小程序目前是不支持echarts的，我们使用了其他的工具，ucharts，希望可以给你提供帮助。
