### ISSUE TITLE
折线图部分缺少

### ISSUE THREAD

**Issue by Pennyhui** [ecomfe/echarts-for-weixin#85]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
图中多条折线，其中一条显示不完整

### 预期效果：

![default](https://user-images.githubusercontent.com/13732551/37701743-1d8c9628-2d2b-11e8-8039-4f54ed13337a.png)

### 实际效果：

![default](https://user-images.githubusercontent.com/13732551/37701756-2aaecd44-2d2b-11e8-92f9-44bb84a0f74a.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by koukaicheng** [comment]
我也存在这样的问题 最后一条的数据不显示 不完整

**Comment by Ovilia** [comment]
开发工具版本号？基础库版本号？复现的代码？

**Comment by liufeics** [comment]
好像只存在开发工具，真机测试好像没问题

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
