### ISSUE TITLE
引用echarts5.3.0及以上版本会报错

### ISSUE THREAD

**Issue by shema1ah** [ecomfe/echarts-for-weixin#858]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
我使用自定义打包构建压缩，尝试5.3.0及以上版本，都会报错

### 预期效果：
预期正常，不报错

### 实际效果：
![image](https://user-images.githubusercontent.com/43143397/164360127-95af8274-eb24-4b62-92d6-f8edb422300d.png)

### 复现环境：
小程序模拟器及真机

**Comment by hyq1860** [comment]
同样的问题

**Comment by lpubcat** [comment]
+1+1+1 希望尽快修复啊，需要用到5.3.0的新特性。

**Comment by Jamboy** [comment]
在wx-canvas.js内添加  addEventListener() { } 空方法可解决。详情见 https://juejin.cn/post/7013280646336348167

**Comment by Ovilia** [comment]
Fixed in 43d0147c7b1fed8eb9e0d9936db1bf219dd665f8
