### ISSUE TITLE
引用echarts5.3.0及以上版本使用dataZoom Y轴拖动 会报错

### ISSUE THREAD

**Issue by wenhao1994** [ecomfe/echarts-for-weixin#861]
![1653534175(1)](https://user-images.githubusercontent.com/38873899/170406805-bbe3c47d-fcf8-4349-bed6-d075574665c6.jpg)

**Comment by adminwarlock** [comment]
dataZoom: [{
   ...,
    preventDefaultMouseMove: false,
  }]

**Comment by Ovilia** [comment]
Fixed in 43d0147c7b1fed8eb9e0d9936db1bf219dd665f8
