### ISSUE TITLE
导入 echarts.js 到 ts 项目中的一个问题

### ISSUE THREAD

**Issue by timecommunication** [ecomfe/echarts-for-weixin#864]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在开发 ts 的 微信小程序项目时，用 ```import * as echarts from '../../components/ec-canvas/echarts'``` 引包

小程序开发软件 提示 这个文件不是模块

如何 让开发软件不报这个错误？

### 预期效果：
<img width="871" alt="屏幕快照 2022-06-08 16 46 06" src="https://user-images.githubusercontent.com/19165258/172573703-c9b964b8-86f4-4e8a-b2a4-b966ac995e11.png">

### 实际效果：
<img width="851" alt="屏幕快照 2022-06-08 16 37 32" src="https://user-images.githubusercontent.com/19165258/172573276-dccb86b9-3692-4c58-9064-f16ebd176ca8.png">

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by gaoweijun2018** [comment]
注释掉就行
// @ts-ignore

**Comment by hongkb24** [comment]
老哥最后怎么解决的
