### ISSUE TITLE
tooltip通过formatter 如何动态修改文案颜色

### ISSUE THREAD

**Issue by TiaoQiLaiBaoBei** [ecomfe/echarts-for-weixin#866]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
这个不是微信版本特有的问题

**Comment by TiaoQiLaiBaoBei** [comment]
> 这个不是微信版本特有的问题

设置 renderMode: "richText",  动态显示自定义样式
![1657090991366](https://user-images.githubusercontent.com/71240148/177489567-97bbfa9d-0985-475a-a9b1-9fefd21d9425.png)
![1657090991366](https://user-images.githubusercontent.com/71240148/177489615-6c41bc99-8c40-4f23-b187-625dd7f0ca37.png)

**Comment by TiaoQiLaiBaoBei** [comment]
> > 这个不是微信版本特有的问题
> 
> 设置 renderMode： “richText”， 动态显示自定义样式 ![1657090991366](https://user-images.githubusercontent.com/71240148/177489567-97bbfa9d-0985-475a-a9b1-9fefd21d9425.png) ![1657090991366](https://user-images.githubusercontent.com/71240148/177489615-6c41bc99-8c40-4f23-b187-625dd7f0ca37.png)

没起作用 颜色不变

**Comment by TiaoQiLaiBaoBei** [comment]
> 这个不是微信版本特有的问题



> 这个不是微信版本特有的问题

麻烦看一下我的截图
