### ISSUE TITLE
Apache ECharts 的uni-app版本, 支持Vue 2/3. 

### ISSUE THREAD

**Issue by xbmlz** [ecomfe/echarts-for-weixin#886]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：

https://github.com/xbmlz/echarts-for-uniapp
Apache ECharts 的uni-app版本, 支持Vue 2/3. 

### 预期效果：
![index](https://user-images.githubusercontent.com/27397747/202963462-63aac33b-5e95-4b2e-b6a1-637df63b0b49.png)

![boxplat](https://user-images.githubusercontent.com/27397747/202963493-7bc7bc31-06f0-4f97-b91e-3ec22e9ddba8.png)

![line](https://user-images.githubusercontent.com/27397747/202963520-324d18cd-05bc-49a7-9074-065079b6422c.png)

![theme](https://user-images.githubusercontent.com/27397747/202963556-695d6dc6-9137-4437-911c-ad1560af1d38.png)

**Comment by Ovilia** [comment]
这里没什么流量的，到 [awesome-echarts](https://github.com/ecomfe/awesome-echarts) 提交下吧~
