### ISSUE TITLE
获取后台数据后怎么传给initChart初始化图表函数呀？

### ISSUE THREAD

**Issue by chudongyang** [ecomfe/echarts-for-weixin#89]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by chudongyang** [comment]
我这理解能力确实有点差啊，文档里也没有写怎么传的，demo全部都是写好的假数据，麻烦官方看到帮我解答下疑问啊

**Comment by chudongyang** [comment]
大面积数据图横坐标的axisLabel里设置fontWeight没有任何作用

**Comment by Ovilia** [comment]
https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/bar/index.js 这个例子里 chart 实例被放在了全局，以后就能 `chart.setOption` 了
