### ISSUE TITLE
为什么echarts官方的demo在真机上运行时，都显示不出来，雷达图还出现一堆错误？

### ISSUE THREAD

**Issue by 513107329** [ecomfe/echarts-for-weixin#91]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
将官方的demo放在本地的微信开发者工具上测试，工具上显示正常，但是到真机上测试时，完全显示不出来，并且雷达图还出现一堆错误。

### 预期效果：
![default](https://user-images.githubusercontent.com/19640501/37817876-39759004-2eb3-11e8-9eb6-3319d1519fb8.png)

（如有需要请提供预期的图）

### 实际效果：
![16_01_12__03_23_2018](https://user-images.githubusercontent.com/19640501/37817926-7293d1f2-2eb3-11e8-92b0-404b8951e4f1.jpg)
![img_0334](https://user-images.githubusercontent.com/19640501/37817969-84950eb6-2eb3-11e8-9d22-e7f19e6c8b76.PNG)

（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
请提供 ECharts 版本号、真机微信版本信息？

**Comment by Ovilia** [comment]
#27
