### ISSUE TITLE
5.4版本在android 手机中，选中地图或者其他饼图，会有一层阴影

### ISSUE THREAD

**Issue by xiaofan10** [ecomfe/echarts-for-weixin#910]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息
下面是android手机中在微信小程序中访问的结果，但是ios就没有这个阴影
- 
![1684394472779](https://github.com/ecomfe/echarts-for-weixin/assets/23414045/f54c647c-6085-4931-a8e0-36f7f855a5d8)

**Comment by xiaofan10** [comment]
哦 对了 我测了好几个android机型，都有这种情况，比如华为mate40pro，但是苹果就没有，如果有遇到同样问题的，请留个言

**Comment by xiaofan10** [comment]
tooltip中都有类似的问题

**Comment by xiaofan10** [comment]
还有个问题，在IOS中地图缩放移动会非常卡，但是android中就很丝滑

**Comment by xiaofan10** [comment]
这个阴影应该是小程序官方基础库的问题，低版本木有这个问题

**Comment by xbsheng** [comment]
https://github.com/ecomfe/echarts-for-weixin/issues/906#issuecomment-1579712860
