### ISSUE TITLE
工具和真机上的柱状图，手指从右上滑向左下时，图表会消失，点击又会出现。

### ISSUE THREAD

**Issue by zhou-z-xin** [ecomfe/echarts-for-weixin#92]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
工具和真机上的柱状图，手指从右上滑向左下时，图表会消失，点击又会出现。

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by rootbre** [comment]
在折线图同样遇到了这个问题，我是自定义时间段取值的，有的时间段又不会，有的会出现。

**Comment by rootbre** [comment]
hoverAnimation: false,  如果series里有写了这个代码，把这个代码注释掉就好了。

**Comment by Ovilia** [comment]
使用新版 canvas 2d 应该可以解决这个问题。如果还有问题请重新 open。
