### ISSUE TITLE
ec-canvas标签如何设置z-index,现在的图表是最高级图层。

### ISSUE THREAD

**Issue by Rainylane** [ecomfe/echarts-for-weixin#93]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
ec-canvas标签如何设置z-index,现在的图表是最高级图层。

### 预期效果：
![image](https://user-images.githubusercontent.com/29814278/37823941-07d0c5d8-2ec6-11e8-979b-b9add42c4a5d.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/29814278/37823905-e8172a2a-2ec5-11e8-8f43-b6ba49011022.png)

### 复现环境：
- [] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by Ovilia** [comment]
#84
