### ISSUE TITLE
echart.js文件超过500k,已跳过 ES6 转 ES5 和压缩的处理

### ISSUE THREAD

**Issue by yoky** [ecomfe/echarts-for-weixin#95]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
微信开发工具中，会有这样的提示。

### 预期效果：
echarts.js的压缩版

### 复现环境：
- [] 在微信开发工具中存在该问题

**Comment by Ovilia** [comment]
本来就是 es5 的代码，跳过 es6 转 es5 完全不会有问题
