### ISSUE TITLE
微信开发者工具显示OK，安卓手机没法显示任何图表

### ISSUE THREAD

**Issue by xswby** [ecomfe/echarts-for-weixin#97]
今天14：00开发手机展示正常，目前没有修改任何代码（下载的实例代码），手机无法显示任何图表，目前尝试很多款手机都不行，可以排查一下原因，
微信开发者工具是最新的

**Comment by Ovilia** [comment]
安卓手机微信的版本是？不行的意思是？有没有看过 console？

**Comment by xswby** [comment]
安卓7.0，测试机型有：荣耀8，
安卓5.1  OPPO r9  360
都无法正常显示，
其实一开始可以的，后来我们没有操作任何东西，就不行了

**Comment by xswby** [comment]
现在的全部白屏

**Comment by Ovilia** [comment]
官方的小程序可以运行吗？（扫首页的二维码）
微信版本号是？

**Comment by FreeFlying0** [comment]
我的也是，还以为自己代码改错了。微信版本6.6.5，之前上传的体验版是可以的，但是最新的开发板就不行了。

**Comment by perny** [comment]
我的也是，前几天还可以，今天突然不行了，微信搞什么鬼？canvas空白一片，苹果安卓都无法显示

**Comment by Ovilia** [comment]
@perny @FreeFlying0 扫首页二维码进的小程序有这个问题吗？

**Comment by LeeeMooo** [comment]
clone的完整代码，只修改了AppID。
- 微信开发工具正常。
- 预览模式除了延迟加载demo正常，其他全部空白
- 远程调试模式，所有全部空白
``首页二维码正常``

**Comment by Ovilia** [comment]
@LeeeMooo 预览模式和远程调试模式分别是指什么？

**Comment by LeeeMooo** [comment]
![snipaste_2018-03-26_17-25-16](https://user-images.githubusercontent.com/23691333/37898179-b78fd698-311a-11e8-8ae1-60a4a63b82ce.png)

**Comment by Ovilia** [comment]
可能是小程序方面的问题，因为我最近的修改是 4 天前发了个版。@xswby 反馈今天 14:00 正常的话，我没有做任何修改。我问下小程序团队~

**Comment by LVLINLIN** [comment]
@Ovilia 有消息请及时发布啊，大神！我们项目等着上线啊，今天突然的问题，又把代码删了，不容易啊

**Comment by LVLINLIN** [comment]
@Ovilia 大神，小程序多个图表在同一个页面怎么切换显示

**Comment by Ovilia** [comment]
小程序自己的问题，现在已经修复了，我验证过ok了

**Comment by Ovilia** [comment]
@LVLINLIN 别的问题再开个 issue 讨论，说清楚具体的问题，可以画图表示

**Comment by perny** [comment]
@FreeFlying0 @LeeeMooo  你们的远程调试图表显示正常了么？我的怎么还是不行？

**Comment by LeeeMooo** [comment]
我远程调试一直就不行，好多天了 @perny

**Comment by Ovilia** [comment]
@perny @LeeeMooo 远程调试不行的话，其他项目可以远程调试吗，还是只是 ECharts Demo 项目？

**Comment by LeeeMooo** [comment]
只是ECharts Demo有问题，其他项目正常 @Ovilia

**Comment by perny** [comment]
项目中的其他代码都可以正常远程调试，就是使用ECharts的画布远程调试都是空白一片

**Comment by xswby** [comment]
荣耀8 ，安卓7.1有问题，多点几次，白屏

**Comment by Ovilia** [comment]
更新到最新版的开发者工具，0315 的版本有问题，0321 修复了

**Comment by LeeeMooo** [comment]
这个情况我想到了，是最新版本，卸载重装还是一样

**Comment by Ovilia** [comment]
我这里更新到 0321 后无法复现这个问题了，0315 是能复现的。@LVLINLIN @perny @xswby

**Comment by antsfreedom** [comment]
版本0321，还是无法显示图表，空白

**Comment by Ovilia** [comment]
亲测 0408 可以远程调试了，但是似乎远程调试时候的定位有问题，已像小程序团队反馈

**Comment by Ovilia** [comment]
远程调试的问题，请更新微信客户端到最新版本，亲测 ios 上 6.6.6 版本远程调试正常了

**Comment by LeeeMooo** [comment]
应该是开发工具问题，0408已经正常了。

**Comment by seed-fe** [comment]
> clone的完整代码，只修改了AppID。
> 
> * 微信开发工具正常。
> * 预览模式除了延迟加载demo正常，其他全部空白
> * 远程调试模式，所有全部空白
>   `首页二维码正常`

@LeeeMooo 很奇怪，昨天在预览里可以看到图表，今天就看不到了，后来找到了这个issue，试着把lazyload设为true，预览可以看到了，问题这个issue是2018年的，费解啊，难道现在必须lazyload才行吗？ @Ovilia

**Comment by Ovilia** [comment]
没有必须 lazyload，看不到具体报什么错呢？可以打开 vconsole 看下报错信息
