### ISSUE TITLE
小程序多个图表做成tab页切换显示，如何实现？以及如何传入后台数据？

### ISSUE THREAD

**Issue by LVLINLIN** [ecomfe/echarts-for-weixin#98]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
？？？

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
？？？
（如有需要请提供截图）
![image](https://user-images.githubusercontent.com/16097878/37942457-ba21de98-31a5-11e8-9d92-2d79c02f9b06.png)

![image](https://user-images.githubusercontent.com/16097878/37942467-c8b71ff4-31a5-11e8-9ae7-2b11cd8b1348.png)

  @@就是如何切换图表显示？

### 复现环境：
- [] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by Ovilia** [comment]
这是小程序布局的问题，跟 ECharts 没有关系
