### ISSUE TITLE
真机远程调试报错

### ISSUE THREAD

**Issue by LeeeMooo** [ecomfe/echarts-for-weixin#99]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
- 下载的最新代码，只更改了AppID, 其他无任何改动
- 微信开发工具测试正常
- 预览模式正常
- 真机测试报错
** 问题已经困扰很多天了， 项目急着用，很急！

### 预期效果：
？？？
（如有需要请提供预期的图）

### 实际效果：
![1](https://user-images.githubusercontent.com/23691333/37942414-7e2b5266-31a5-11e8-8596-51245637d300.png)
![2](https://user-images.githubusercontent.com/23691333/37942419-83112e04-31a5-11e8-93ee-9cf77672fe0a.png)

### 复现环境：
- iPhone8 Plus 微信6.6.5 网络环境：WIFI 4G
- Red MI NOTE3 微信6.6.5 网络环境：WIFI

**Comment by Ovilia** [comment]
#97
